export const colors = {
  primary: '#052E2B',
  primaryDark: '#031F1D',
  primarySoft: '#E6F4F1',
  gold: '#D4AF37',
  goldSoft: '#FFF8E1',
  ink: '#0F172A',
  text: '#0F172A',
  dark: '#052E2B',
  dark3: '#0B3B38',
  slate: '#334155',
  muted: '#64748B',
  bg: '#F8FAFC',
  card: '#FFFFFF',
  border: '#E2E8F0',
  white: '#FFFFFF',
  blue: '#2563EB',
  blueSoft: '#DBEAFE',
  green: '#16A34A',
  greenSoft: '#DCFCE7',
  red: '#DC2626',
  redSoft: '#FEE2E2',
  orange: '#F97316',
  orangeSoft: '#FFEDD5',
  purple: '#7C3AED',
  purpleSoft: '#EDE9FE',
};

export const semanticColors = {
  success: colors.green,
  warning: colors.orange,
  danger: colors.red,
  info: colors.blue,
  premium: colors.gold,
  surface: colors.card,
};
