-- 019_create_functions.sql
-- Consolidated layer for BarberSync 2.0
-- This file references existing module scripts from /ScriptsSQL and should be expanded progressively.
-- Keep tenant/branch indexes and timestamptz defaults in every added table.
