using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BarberSync.Application.Abstractions;
using Npgsql;

namespace BarberSync.Api.Services.Club;

public sealed class ClubStore(IConfiguration configuration, ICurrentUserContext current)
{
    private readonly string connectionString = configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("ConnectionStrings:DefaultConnection não configurada.");
    public Task<JsonElement> Query(string sql, Action<NpgsqlCommand>? bind, CancellationToken ct) => Json(sql, bind, ct);
    public Task<JsonElement> Dashboard(CancellationToken ct) => Json(@"select jsonb_build_object('mrr',coalesce(sum(p.price) filter(where m.status='Active' and p.billing_cycle='Monthly'),0),'activeMemberships',count(*) filter(where m.status='Active'),'suspendedMemberships',count(*) filter(where m.status='Suspended'),'pendingSales',(select count(*) from barber.online_sales_orders o where o.tenant_id=@tenant and o.branch_id=@branch and o.status='PendingPayment'),'sourceStatus','available') from barber.client_memberships m join barber.club_plans p on p.id=m.club_plan_id where m.tenant_id=@tenant and m.branch_id=@branch",null,ct);
    public Task<JsonElement> List(string table, CancellationToken ct) => Json($"select coalesce(jsonb_agg(to_jsonb(x) order by created_at desc),'[]') from barber.{table} x where tenant_id=@tenant and branch_id=@branch",null,ct);
    public Task<JsonElement> Options(CancellationToken ct) => Json(@"select jsonb_build_object('clients',coalesce((select jsonb_agg(jsonb_build_object('value',id,'label',name) order by name) from barber.clients where tenant_id=@tenant and branch_id=@branch and deleted_at is null),'[]'),'plans',coalesce((select jsonb_agg(jsonb_build_object('value',id,'label',name,'price',price) order by name) from barber.club_plans where tenant_id=@tenant and branch_id=@branch and status='Active'),'[]'),'services',coalesce((select jsonb_agg(jsonb_build_object('value',id,'label',name) order by name) from barber.services where tenant_id=@tenant and branch_id=@branch and deleted_at is null),'[]'),'products',coalesce((select jsonb_agg(jsonb_build_object('value',id,'label',name) order by name) from barber.products where tenant_id=@tenant and branch_id=@branch and deleted_at is null),'[]'))",null,ct);
    public async Task<JsonElement> CreatePlan(PlanRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||r.Price<0)throw new ClubValidationException("Nome e valor válido são obrigatórios.");return await Json(@"insert into barber.club_plans(tenant_id,branch_id,name,description,billing_cycle,price,status,allow_auto_renew,cancellation_policy_json,created_by) values(@tenant,@branch,@name,@description,@cycle,@price,'Draft',@renew,@policy::jsonb,@user) returning to_jsonb(club_plans)",c=>{c.Parameters.AddWithValue("name",r.Name.Trim());c.Parameters.AddWithValue("description",r.Description??"");c.Parameters.AddWithValue("cycle",r.BillingCycle);c.Parameters.AddWithValue("price",r.Price);c.Parameters.AddWithValue("renew",r.AllowAutoRenew);c.Parameters.AddWithValue("policy",r.CancellationPolicy.GetRawText());},ct);}
    public Task<JsonElement> Status(string table,Guid id,string status,CancellationToken ct)=>Json($"update barber.{table} set status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch returning to_jsonb({table})",c=>{c.Parameters.AddWithValue("id",id);c.Parameters.AddWithValue("status",status);},ct);
    public async Task<JsonElement> CreateMembership(MembershipRequest r,CancellationToken ct){var status=r.AdministrativeActivation?"Active":"PendingPayment";return await Json(@"with m as (insert into barber.client_memberships(tenant_id,branch_id,client_id,club_plan_id,status,starts_at,ends_at,next_billing_at,auto_renew,created_by) select @tenant,@branch,@client,p.id,@status,@start,@end,@next,@renew,@user from barber.club_plans p where p.id=@plan and p.tenant_id=@tenant and p.branch_id=@branch and p.status='Active' returning *) select to_jsonb(m) from m",c=>{c.Parameters.AddWithValue("client",r.ClientId);c.Parameters.AddWithValue("plan",r.PlanId);c.Parameters.AddWithValue("status",status);c.Parameters.AddWithValue("start",r.StartsAt);c.Parameters.AddWithValue("end",(object?)r.EndsAt??DBNull.Value);c.Parameters.AddWithValue("next",(object?)r.NextBillingAt??DBNull.Value);c.Parameters.AddWithValue("renew",r.AutoRenew);},ct);}
    public async Task<JsonElement> Wallet(Guid clientId,decimal amount,string type,string reason,CancellationToken ct){if(amount<=0||string.IsNullOrWhiteSpace(reason))throw new ClubValidationException("Valor positivo e motivo são obrigatórios.");var debit=type=="Debit";return await Json(@"with w as (insert into barber.client_wallets(tenant_id,branch_id,client_id) values(@tenant,@branch,@client) on conflict(tenant_id,branch_id,client_id) do update set updated_at=now() returning *), u as (update barber.client_wallets set credit_balance=credit_balance+@delta,updated_at=now() where id=(select id from w) and credit_balance+@delta>=0 returning *), t as (insert into barber.wallet_transactions(tenant_id,branch_id,wallet_id,client_id,transaction_type,amount,balance_after,source_type,reason,created_by) select @tenant,@branch,id,@client,@type,@amount,credit_balance,'Admin',@reason,@user from u returning *) select jsonb_build_object('wallet',to_jsonb(u),'transaction',to_jsonb(t)) from u,t",c=>{c.Parameters.AddWithValue("client",clientId);c.Parameters.AddWithValue("delta",debit?-amount:amount);c.Parameters.AddWithValue("amount",amount);c.Parameters.AddWithValue("type",type);c.Parameters.AddWithValue("reason",reason.Trim());},ct);}
    public async Task<(JsonElement Data,string Code)> CreateGift(GiftRequest r,CancellationToken ct){if(r.Amount<=0)throw new ClubValidationException("Valor deve ser positivo.");var code=Convert.ToHexString(RandomNumberGenerator.GetBytes(12));var hash=Hash(code);var data=await Json(@"insert into barber.gift_cards(tenant_id,branch_id,code_hash,display_code_masked,buyer_client_id,beneficiary_client_id,initial_amount,remaining_amount,status,valid_from,valid_until,created_by) values(@tenant,@branch,@hash,@masked,@buyer,@beneficiary,@amount,@amount,'PendingPayment',now(),@until,@user) returning to_jsonb(gift_cards)",c=>{c.Parameters.AddWithValue("hash",hash);c.Parameters.AddWithValue("masked",$"****-****-{code[^4..]}");c.Parameters.AddWithValue("buyer",(object?)r.BuyerClientId??DBNull.Value);c.Parameters.AddWithValue("beneficiary",(object?)r.BeneficiaryClientId??DBNull.Value);c.Parameters.AddWithValue("amount",r.Amount);c.Parameters.AddWithValue("until",r.ValidUntil);},ct);return(data,code);}
    public Task<JsonElement> RedeemGift(CodeRedemption r,CancellationToken ct)=>Json(@"with g as (select * from barber.gift_cards where tenant_id=@tenant and branch_id=@branch and code_hash=@hash and status='Active' and valid_from<=now() and valid_until>now() for update), u as (update barber.gift_cards set remaining_amount=remaining_amount-@amount,status=case when remaining_amount=@amount then 'Redeemed' else status end,updated_at=now() where id=(select id from g) and remaining_amount>=@amount returning *), t as(insert into barber.gift_card_transactions(tenant_id,branch_id,gift_card_id,transaction_type,amount,service_order_id,created_by) select @tenant,@branch,id,'Redeemed',@amount,@order,@user from u returning *) select to_jsonb(u) from u",c=>{c.Parameters.AddWithValue("hash",Hash(r.Code));c.Parameters.AddWithValue("amount",r.Amount);c.Parameters.AddWithValue("order",r.ServiceOrderId);},ct);
    public async Task<JsonElement> Json(string sql,Action<NpgsqlCommand>? bind,CancellationToken ct){await using var cn=new NpgsqlConnection(connectionString);await cn.OpenAsync(ct);await using var c=new NpgsqlCommand(sql,cn);c.Parameters.AddWithValue("tenant",current.TenantId);c.Parameters.AddWithValue("branch",current.BranchId);c.Parameters.AddWithValue("user",current.UserId);bind?.Invoke(c);var value=await c.ExecuteScalarAsync(ct);if(value is null or DBNull)throw new KeyNotFoundException("Registro indisponível nesta unidade ou regra comercial não atendida.");return JsonDocument.Parse(value.ToString()!).RootElement.Clone();}
    public static string Hash(string code)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(code.Trim().ToUpperInvariant()))).ToLowerInvariant();
}
public sealed class ClubValidationException(string message):Exception(message);
public sealed record PlanRequest(string Name,string? Description,string BillingCycle,decimal Price,bool AllowAutoRenew,JsonElement CancellationPolicy);
public sealed record MembershipRequest(Guid ClientId,Guid PlanId,DateTimeOffset StartsAt,DateTimeOffset? EndsAt,DateTimeOffset? NextBillingAt,bool AutoRenew,bool AdministrativeActivation);
public sealed record WalletRequest(decimal Amount,string Reason);
public sealed record GiftRequest(Guid? BuyerClientId,Guid? BeneficiaryClientId,decimal Amount,DateTimeOffset ValidUntil);
public sealed record CodeRedemption(string Code,decimal Amount,Guid ServiceOrderId);
