using System.Data.Common;
using System.Globalization;
using System.Text;
using BarberSync.Api.Services.Team;
using BarberSync.Api.Services.Finance360;

namespace BarberSync.Api.Services.Inventory360;

public sealed record InventoryProductResult(Guid Id,string Status);
public sealed record InventoryProductSearchResult(IReadOnlyList<Dictionary<string,object?>> Items);
public sealed record CreateInventoryProductRequest(string Name,string? Sku,string? Barcode,string UnitOfMeasure,decimal CostPrice,decimal SalePrice,bool StockControlRequired,bool PublicVisible,bool KioskVisible,bool MarketplaceVisible);
public sealed record UpdateInventoryProductRequest(Guid Id,string Name,string? Sku,string? Barcode,string UnitOfMeasure,decimal CostPrice,decimal SalePrice,bool StockControlRequired,bool PublicVisible,bool KioskVisible,bool MarketplaceVisible);
public sealed record ActivateInventoryProductRequest(Guid Id); public sealed record SuspendInventoryProductRequest(Guid Id,string Reason); public sealed record ArchiveInventoryProductRequest(Guid Id,string Reason); public sealed record InventoryProductSearchRequest(string? Query,string? Status);
public sealed record ServiceInputLine(Guid? ProductId,Guid? SupplyId,decimal Quantity,string UnitOfMeasure,string ConsumeOn);
public sealed record ConfigureServiceInputsRequest(Guid ServiceId,IReadOnlyList<ServiceInputLine> Items); public sealed record ServiceInputPreviewRequest(Guid ServiceId,decimal Executions=1); public sealed record ActivateServiceInputRuleRequest(Guid Id); public sealed record ArchiveServiceInputRuleRequest(Guid Id,string Reason);
public sealed record ServiceInputResult(IReadOnlyList<Guid> Ids,string Status); public sealed record ServiceInputPreviewResult(IReadOnlyList<Dictionary<string,object?>> Items,string SourceStatus);
public sealed record ReceiveStockRequest(Guid? ProductId,Guid? SupplyId,decimal Quantity,decimal UnitCost,string SourceType,Guid SourceId,string IdempotencyKey,string? BatchCode,DateOnly? ExpiresAt);
public sealed record ConsumeStockRequest(Guid? ProductId,Guid? SupplyId,decimal Quantity,string SourceType,Guid SourceId,string IdempotencyKey); public sealed record ReserveStockRequest(Guid? ProductId,Guid? SupplyId,decimal Quantity,string SourceType,Guid SourceId,string IdempotencyKey);
public sealed record ReleaseStockReservationRequest(Guid MovementId,string Reason,string IdempotencyKey); public sealed record ReverseStockMovementRequest(Guid MovementId,string Reason,string IdempotencyKey); public sealed record StockBalanceRequest(Guid? ProductId,Guid? SupplyId);
public sealed record StockMovementResult(Guid Id,string Type,decimal Quantity); public sealed record StockBalanceResult(decimal OnHand,decimal Reserved,decimal Available,string SourceStatus);
public sealed record PurchaseLine(Guid? ProductId,Guid? SupplyId,decimal Quantity,decimal UnitCost); public sealed record CreatePurchaseOrderRequest(Guid SupplierId,DateOnly? ExpectedAt,IReadOnlyList<PurchaseLine> Items); public sealed record ApprovePurchaseOrderRequest(Guid Id); public sealed record CancelPurchaseOrderRequest(Guid Id,string Reason);
public sealed record ReceivingLine(Guid PurchaseOrderItemId,decimal Quantity,string? BatchCode,DateOnly? ExpiresAt); public sealed record ReceivePurchaseOrderRequest(Guid Id,DateTimeOffset ReceivedAt,bool CreatePayable,IReadOnlyList<ReceivingLine> Items); public sealed record ReturnToSupplierRequest(Guid Id,string Reason,IReadOnlyList<ReceivingLine> Items);
public sealed record PurchaseOrderResult(Guid Id,string Status,decimal Total); public sealed record PurchaseReceivingResult(Guid Id,string Status); public sealed record SupplierReturnResult(Guid Id,string Status);
public sealed record OpenInventoryCountRequest(DateOnly CountDate); public sealed record RegisterInventoryCountItemRequest(Guid CountId,Guid? ProductId,Guid? SupplyId,Guid? BatchId,decimal CountedQuantity,string? Reason); public sealed record CloseInventoryCountRequest(Guid Id); public sealed record ApplyInventoryAdjustmentRequest(Guid Id);
public sealed record InventoryCountResult(Guid Id,string Status); public sealed record InventoryAdjustmentResult(Guid Id,string Status);
public sealed record ReplenishmentDashboardRequest(); public sealed record GenerateReplenishmentSuggestionsRequest(); public sealed record CreatePurchaseOrderFromSuggestionRequest(Guid Id); public sealed record ReplenishmentDashboardResult(IReadOnlyList<Dictionary<string,object?>> Items); public sealed record ReplenishmentSuggestionResult(int Created,string SourceStatus);
public sealed record CalculateAverageCostRequest(Guid? ProductId,Guid? SupplyId); public sealed record CalculateBatchCostRequest(Guid BatchId); public sealed record CogsRequest(DateOnly From,DateOnly To,Guid? ProductId=null,Guid? SupplyId=null); public sealed record InventoryCostExportRequest(DateOnly From,DateOnly To);
public sealed record InventoryCostResult(decimal? Cost,string SourceStatus); public sealed record CogsResult(decimal? Amount,string SourceStatus); public sealed record InventoryCostExportResult(byte[] Content,string FileName,string SourceStatus);

internal static class InventoryRules
{
    internal static void Quantity(decimal value){if(value<=0)throw new ArgumentException("A quantidade deve ser maior que zero.");}
    internal static void Item(Guid? product,Guid? supply){if((product is null)==(supply is null))throw new ArgumentException("Selecione exatamente um produto ou insumo.");}
    internal static void Origin(string type,Guid id,string key){if(string.IsNullOrWhiteSpace(type)||id==Guid.Empty||string.IsNullOrWhiteSpace(key))throw new ArgumentException("Origem real e chave de idempotência são obrigatórias.");}
    internal static decimal D(object? value)=>Convert.ToDecimal(value??0,CultureInfo.InvariantCulture);
    internal static void Add(DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
}

public sealed class InventoryProductService(TeamDataService data)
{
    public Task<InventoryProductResult> CreateProductAsync(CreateInventoryProductRequest r,CancellationToken ct)=>Save(Guid.NewGuid(),r.Name,r.Sku,r.Barcode,r.UnitOfMeasure,r.CostPrice,r.SalePrice,r.StockControlRequired,r.PublicVisible,r.KioskVisible,r.MarketplaceVisible,"Draft",ct);
    public Task<InventoryProductResult> UpdateProductAsync(UpdateInventoryProductRequest r,CancellationToken ct)=>Save(r.Id,r.Name,r.Sku,r.Barcode,r.UnitOfMeasure,r.CostPrice,r.SalePrice,r.StockControlRequired,r.PublicVisible,r.KioskVisible,r.MarketplaceVisible,null,ct);
    private async Task<InventoryProductResult> Save(Guid id,string name,string? sku,string? barcode,string unit,decimal cost,decimal sale,bool controlled,bool pub,bool kiosk,bool market,string? status,CancellationToken ct){if(string.IsNullOrWhiteSpace(name)||string.IsNullOrWhiteSpace(unit)||cost<0||sale<0)throw new ArgumentException("Nome, unidade e valores não negativos são obrigatórios.");await data.WriteAsync(@"insert into barber.inventory_products(id,tenant_id,branch_id,sku,barcode,name,unit_of_measure,cost_price,sale_price,stock_control_required,public_visible,kiosk_visible,marketplace_visible,status) values(@id,@tenant,@branch,@sku,@barcode,@name,@unit,@cost,@sale,@controlled,@public,@kiosk,@market,coalesce(@status,'Draft')) on conflict(id) do update set sku=excluded.sku,barcode=excluded.barcode,name=excluded.name,unit_of_measure=excluded.unit_of_measure,cost_price=excluded.cost_price,sale_price=excluded.sale_price,stock_control_required=excluded.stock_control_required,public_visible=excluded.public_visible,kiosk_visible=excluded.kiosk_visible,marketplace_visible=excluded.marketplace_visible,updated_at=now() where inventory_products.tenant_id=@tenant and inventory_products.branch_id=@branch and inventory_products.status<>'Archived'","Inventory360.ProductSaved","inventory_products",id,null,c=>{A(c,"sku",sku);A(c,"barcode",barcode);A(c,"name",name.Trim());A(c,"unit",unit);A(c,"cost",cost);A(c,"sale",sale);A(c,"controlled",controlled);A(c,"public",pub);A(c,"kiosk",kiosk);A(c,"market",market);A(c,"status",status);},ct);return new(id,status??"Updated");}
    public Task<InventoryProductResult> ActivateProductAsync(ActivateInventoryProductRequest r,CancellationToken ct)=>Status(r.Id,"Active",null,ct); public Task<InventoryProductResult> SuspendProductAsync(SuspendInventoryProductRequest r,CancellationToken ct)=>Status(r.Id,"Suspended",r.Reason,ct); public Task<InventoryProductResult> ArchiveProductAsync(ArchiveInventoryProductRequest r,CancellationToken ct)=>Status(r.Id,"Archived",r.Reason,ct);
    private async Task<InventoryProductResult> Status(Guid id,string status,string? reason,CancellationToken ct){if(status!="Active"&&string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Motivo obrigatório.");await data.WriteAsync("update barber.inventory_products set status=@status,deleted_at=case when @status='Archived' then now() else null end,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","Inventory360.Product"+status,"inventory_products",id,reason,c=>A(c,"status",status),ct);return new(id,status);}
    public async Task<InventoryProductSearchResult> SearchProductsAsync(InventoryProductSearchRequest r,CancellationToken ct)=>new(await data.QueryAsync("select id,sku,barcode,name,unit_of_measure,cost_price,sale_price,stock_control_required,public_visible,kiosk_visible,marketplace_visible,status from barber.inventory_products where tenant_id=@tenant and branch_id=@branch and deleted_at is null and (@query is null or name ilike '%'||@query||'%' or sku ilike '%'||@query||'%') and (@status is null or status=@status) order by name",c=>{A(c,"query",r.Query);A(c,"status",r.Status);},ct)); private static void A(DbCommand c,string n,object? v)=>InventoryRules.Add(c,n,v);
}

public sealed class ServiceInputService(TeamDataService data)
{
    public async Task<ServiceInputResult> ConfigureServiceInputsAsync(ConfigureServiceInputsRequest r,CancellationToken ct){if(r.Items.Count==0)throw new ArgumentException("Adicione ao menos um insumo.");var ids=new List<Guid>();foreach(var x in r.Items){InventoryRules.Item(x.ProductId,x.SupplyId);InventoryRules.Quantity(x.Quantity);if(string.IsNullOrWhiteSpace(x.UnitOfMeasure)||x.ConsumeOn is not("ServiceStarted" or "ServiceCompleted" or "CheckoutConfirmed"))throw new ArgumentException("Unidade ou momento de consumo inválido.");var id=await data.WriteAsync(@"insert into barber.inventory_service_inputs(id,tenant_id,branch_id,service_id,supply_id,product_id,quantity,unit_of_measure,consume_on,status) select @id,@tenant,@branch,s.id,@supply,@product,@quantity,@unit,@consume,'Active' from barber.services s where s.id=@service and s.tenant_id=@tenant and s.branch_id=@branch", "Inventory360.ServiceInputConfigured","inventory_service_inputs",null,null,c=>{A(c,"service",r.ServiceId);A(c,"supply",x.SupplyId);A(c,"product",x.ProductId);A(c,"quantity",x.Quantity);A(c,"unit",x.UnitOfMeasure);A(c,"consume",x.ConsumeOn);},ct);ids.Add(id);}return new(ids,"Active");}
    public async Task<ServiceInputPreviewResult> PreviewServiceConsumptionAsync(ServiceInputPreviewRequest r,CancellationToken ct){InventoryRules.Quantity(r.Executions);return new(await data.QueryAsync("select id,product_id,supply_id,quantity*@executions quantity,unit_of_measure,consume_on,status from barber.inventory_service_inputs where tenant_id=@tenant and branch_id=@branch and service_id=@service and status='Active' and deleted_at is null",c=>{A(c,"service",r.ServiceId);A(c,"executions",r.Executions);},ct),"Available");}
    public Task<ServiceInputResult> ActivateServiceInputRuleAsync(ActivateServiceInputRuleRequest r,CancellationToken ct)=>Set(r.Id,"Active",null,ct); public Task<ServiceInputResult> ArchiveServiceInputRuleAsync(ArchiveServiceInputRuleRequest r,CancellationToken ct)=>Set(r.Id,"Archived",r.Reason,ct); private async Task<ServiceInputResult> Set(Guid id,string status,string? reason,CancellationToken ct){if(status=="Archived"&&string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Motivo obrigatório.");await data.WriteAsync("update barber.inventory_service_inputs set status=@status,deleted_at=case when @status='Archived' then now() else null end,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","Inventory360.ServiceInput"+status,"inventory_service_inputs",id,reason,c=>A(c,"status",status),ct);return new([id],status);} private static void A(DbCommand c,string n,object? v)=>InventoryRules.Add(c,n,v);
}

public sealed class StockMovementService(TeamDataService data)
{
    public Task<StockMovementResult> ReceiveStockAsync(ReceiveStockRequest r,CancellationToken ct)=>Move("Receive",r.ProductId,r.SupplyId,r.Quantity,r.UnitCost,r.SourceType,r.SourceId,r.IdempotencyKey,null,null,r.BatchCode,r.ExpiresAt,ct);
    public Task<StockMovementResult> ConsumeStockAsync(ConsumeStockRequest r,CancellationToken ct)=>Move("Consume",r.ProductId,r.SupplyId,r.Quantity,null,r.SourceType,r.SourceId,r.IdempotencyKey,null,null,null,null,ct);
    public Task<StockMovementResult> ReserveStockAsync(ReserveStockRequest r,CancellationToken ct)=>Move("Reserve",r.ProductId,r.SupplyId,r.Quantity,null,r.SourceType,r.SourceId,r.IdempotencyKey,null,null,null,null,ct);
    public async Task<StockMovementResult> ReleaseReservationAsync(ReleaseStockReservationRequest r,CancellationToken ct)=>await Reverse(r.MovementId,"Release",r.Reason,r.IdempotencyKey,ct); public async Task<StockMovementResult> ReverseMovementAsync(ReverseStockMovementRequest r,CancellationToken ct)=>await Reverse(r.MovementId,"Reverse",r.Reason,r.IdempotencyKey,ct);
    private async Task<StockMovementResult> Reverse(Guid original,string type,string reason,string key,CancellationToken ct){if(string.IsNullOrWhiteSpace(reason)||string.IsNullOrWhiteSpace(key))throw new ArgumentException("Motivo e idempotência são obrigatórios.");var row=(await data.QueryAsync("select product_id,supply_id,quantity,unit_cost,id from barber.inventory_stock_movements where id=@original and tenant_id=@tenant and branch_id=@branch and reverse_of_movement_id is null",c=>A(c,"original",original),ct)).SingleOrDefault()??throw new InvalidOperationException("Movimento original não encontrado.");return await Move(type,row["product_id"] as Guid?,row["supply_id"] as Guid?,InventoryRules.D(row["quantity"]),row["unit_cost"] is null?null:InventoryRules.D(row["unit_cost"]),"StockMovement",original,key,original,reason,null,null,ct);}
    private async Task<StockMovementResult> Move(string type,Guid? product,Guid? supply,decimal quantity,decimal? cost,string source,Guid sourceId,string key,Guid? reverse,string? reason,string? batch,DateOnly? expires,CancellationToken ct){InventoryRules.Item(product,supply);InventoryRules.Quantity(quantity);InventoryRules.Origin(source,sourceId,key);var sign=type is "Receive" or "Release" or "Reverse"?1:-1;var id=await data.WriteAsync(@"with locked as(select coalesce(quantity_on_hand,0) on_hand,coalesce(quantity_reserved,0) reserved from barber.inventory_stock_balances where tenant_id=@tenant and branch_id=@branch and product_id is not distinct from @product and supply_id is not distinct from @supply for update), guard as(select 1 where @sign>0 or coalesce((select on_hand-reserved from locked),0)>=@quantity), movement as(insert into barber.inventory_stock_movements(id,tenant_id,branch_id,movement_type,product_id,supply_id,quantity,unit_cost,total_cost,source_type,source_id,reverse_of_movement_id,idempotency_key,reason) select @id,@tenant,@branch,@type,@product,@supply,@quantity,@cost,@quantity*@cost,@source,@sourceId,@reverse,@key,@reason from guard on conflict(tenant_id,branch_id,idempotency_key) do update set idempotency_key=excluded.idempotency_key returning id), balance as(insert into barber.inventory_stock_balances(id,tenant_id,branch_id,product_id,supply_id,quantity_on_hand,quantity_reserved,quantity_available,average_cost,last_movement_at) select gen_random_uuid(),@tenant,@branch,@product,@supply,@sign*@quantity,case when @type='Reserve' then @quantity else 0 end,@sign*@quantity-case when @type='Reserve' then @quantity else 0 end,@cost,now() from movement on conflict(tenant_id,branch_id,coalesce(product_id,'00000000-0000-0000-0000-000000000000'::uuid),coalesce(supply_id,'00000000-0000-0000-0000-000000000000'::uuid)) do update set quantity_on_hand=inventory_stock_balances.quantity_on_hand+case when @type='Reserve' then 0 else @sign*@quantity end,quantity_reserved=inventory_stock_balances.quantity_reserved+case when @type='Reserve' then @quantity when @type='Release' then -@quantity else 0 end,quantity_available=inventory_stock_balances.quantity_available+case when @type='Reserve' then -@quantity when @type='Release' then @quantity else @sign*@quantity end,average_cost=case when @type='Receive' and @cost is not null then ((inventory_stock_balances.quantity_on_hand*coalesce(inventory_stock_balances.average_cost,0))+(@quantity*@cost))/nullif(inventory_stock_balances.quantity_on_hand+@quantity,0) else inventory_stock_balances.average_cost end,last_movement_at=now(),updated_at=now()) select id from movement","Inventory360.Stock"+type,"inventory_stock_movements",null,reason,c=>{A(c,"type",type);A(c,"product",product);A(c,"supply",supply);A(c,"quantity",quantity);A(c,"cost",cost);A(c,"source",source);A(c,"sourceId",sourceId);A(c,"reverse",reverse);A(c,"key",key);A(c,"reason",reason);A(c,"sign",sign);},ct);return new(id,type,quantity);}
    public async Task<StockBalanceResult> GetStockBalanceAsync(StockBalanceRequest r,CancellationToken ct){InventoryRules.Item(r.ProductId,r.SupplyId);var row=(await data.QueryAsync("select quantity_on_hand,quantity_reserved,quantity_available from barber.inventory_stock_balances where tenant_id=@tenant and branch_id=@branch and product_id is not distinct from @product and supply_id is not distinct from @supply",c=>{A(c,"product",r.ProductId);A(c,"supply",r.SupplyId);},ct)).SingleOrDefault();return row is null?new(0,0,0,"Unavailable"):new(InventoryRules.D(row["quantity_on_hand"]),InventoryRules.D(row["quantity_reserved"]),InventoryRules.D(row["quantity_available"]),"Available");} private static void A(DbCommand c,string n,object? v)=>InventoryRules.Add(c,n,v);
}

public sealed class InventoryCostingService(TeamDataService data)
{
    public async Task<InventoryCostResult> CalculateAverageCostAsync(CalculateAverageCostRequest r,CancellationToken ct){InventoryRules.Item(r.ProductId,r.SupplyId);var rows=await data.QueryAsync("select average_cost from barber.inventory_stock_balances where tenant_id=@tenant and branch_id=@branch and product_id is not distinct from @product and supply_id is not distinct from @supply and average_cost is not null",c=>{A(c,"product",r.ProductId);A(c,"supply",r.SupplyId);},ct);return rows.Count==0?new(null,"Unavailable"):new(InventoryRules.D(rows[0]["average_cost"]),"AverageCost");}
    public async Task<InventoryCostResult> CalculateBatchCostAsync(CalculateBatchCostRequest r,CancellationToken ct){var rows=await data.QueryAsync("select unit_cost from barber.inventory_stock_batches where id=@batch and tenant_id=@tenant and branch_id=@branch and status not in ('Blocked','Reversed')",c=>A(c,"batch",r.BatchId),ct);return rows.Count==0?new(null,"Unavailable"):new(InventoryRules.D(rows[0]["unit_cost"]),"BatchCost");}
    public async Task<CogsResult> CalculateCogsAsync(CogsRequest r,CancellationToken ct){if(r.To<r.From)throw new ArgumentException("Período inválido.");var row=(await data.QueryAsync("select sum(total_cost) amount,count(total_cost) costed,count(*) total from barber.inventory_stock_movements where tenant_id=@tenant and branch_id=@branch and movement_type in ('Consume','Loss','Return') and created_at::date between @from and @to and (@product is null or product_id=@product) and (@supply is null or supply_id=@supply)",c=>{A(c,"from",r.From);A(c,"to",r.To);A(c,"product",r.ProductId);A(c,"supply",r.SupplyId);},ct)).Single();return InventoryRules.D(row["total"])==0||InventoryRules.D(row["costed"])<InventoryRules.D(row["total"])?new(null,"Unavailable"):new(InventoryRules.D(row["amount"]),"RealCost");}
    public async Task<InventoryCostExportResult> ExportCostingAsync(InventoryCostExportRequest r,CancellationToken ct){var c=await CalculateCogsAsync(new(r.From,r.To),ct);var csv=$"periodo_inicio;periodo_fim;cmv;source_status\n{r.From:yyyy-MM-dd};{r.To:yyyy-MM-dd};{c.Amount?.ToString(CultureInfo.InvariantCulture)??string.Empty};{c.SourceStatus}\n";return new(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv)).ToArray(),$"inventory-costing-{r.From:yyyyMMdd}-{r.To:yyyyMMdd}.csv",c.SourceStatus);} private static void A(DbCommand c,string n,object? v)=>InventoryRules.Add(c,n,v);
}

public sealed class PurchaseOrderService(TeamDataService data,StockMovementService stock,AccountsPayableService payable)
{
    public async Task<PurchaseOrderResult> CreatePurchaseOrderAsync(CreatePurchaseOrderRequest r,CancellationToken ct){if(r.Items.Count==0||r.Items.Any(x=>x.Quantity<=0||x.UnitCost<0))throw new ArgumentException("Itens com quantidade positiva e custo não negativo são obrigatórios.");var id=Guid.NewGuid();var total=r.Items.Sum(x=>x.Quantity*x.UnitCost);await data.WriteAsync("insert into barber.inventory_purchase_orders(id,tenant_id,branch_id,supplier_id,status,order_number,expected_at,total_amount) select @id,@tenant,@branch,s.id,'Draft','PC-'||upper(substr(replace(@id::text,'-',''),1,10)),@expected,@total from barber.inventory_suppliers s where s.id=@supplier and s.tenant_id=@tenant and s.branch_id=@branch and s.status='Active'","Inventory360.PurchaseCreated","inventory_purchase_orders",id,null,c=>{A(c,"supplier",r.SupplierId);A(c,"expected",r.ExpectedAt);A(c,"total",total);},ct);foreach(var x in r.Items){InventoryRules.Item(x.ProductId,x.SupplyId);await data.WriteAsync("insert into barber.inventory_purchase_order_items(id,tenant_id,branch_id,purchase_order_id,product_id,supply_id,quantity,unit_cost,total_cost) values(@id,@tenant,@branch,@order,@product,@supply,@quantity,@cost,@quantity*@cost)","Inventory360.PurchaseItemCreated","inventory_purchase_order_items",null,null,c=>{A(c,"order",id);A(c,"product",x.ProductId);A(c,"supply",x.SupplyId);A(c,"quantity",x.Quantity);A(c,"cost",x.UnitCost);},ct);}return new(id,"Draft",total);}
    public Task<PurchaseOrderResult> ApprovePurchaseOrderAsync(ApprovePurchaseOrderRequest r,CancellationToken ct)=>Set(r.Id,"Approved",null,ct); public Task<PurchaseOrderResult> CancelPurchaseOrderAsync(CancelPurchaseOrderRequest r,CancellationToken ct)=>Set(r.Id,"Cancelled",r.Reason,ct);
    private async Task<PurchaseOrderResult> Set(Guid id,string status,string? reason,CancellationToken ct){if(status=="Cancelled"&&string.IsNullOrWhiteSpace(reason))throw new ArgumentException("Motivo obrigatório.");await data.WriteAsync("update barber.inventory_purchase_orders set status=@status,approved_at=case when @status='Approved' then now() else approved_at end,cancelled_at=case when @status='Cancelled' then now() else cancelled_at end,cancel_reason=@reason,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Draft','PendingApproval','Approved')","Inventory360.Purchase"+status,"inventory_purchase_orders",id,reason,c=>{A(c,"status",status);A(c,"reason",reason);},ct);return new(id,status,0);}
    public async Task<PurchaseReceivingResult> ReceivePurchaseOrderAsync(ReceivePurchaseOrderRequest r,CancellationToken ct){if(r.Items.Count==0)throw new ArgumentException("Itens recebidos são obrigatórios.");foreach(var x in r.Items){InventoryRules.Quantity(x.Quantity);var rows=await data.QueryAsync("select product_id,supply_id,unit_cost,quantity-received_quantity pending from barber.inventory_purchase_order_items where id=@item and purchase_order_id=@order and tenant_id=@tenant and branch_id=@branch",c=>{A(c,"item",x.PurchaseOrderItemId);A(c,"order",r.Id);},ct);if(rows.Count!=1||InventoryRules.D(rows[0]["pending"])<x.Quantity)throw new InvalidOperationException("Quantidade recebida excede o saldo do pedido.");var p=rows[0]["product_id"] as Guid?;var s=rows[0]["supply_id"] as Guid?;await stock.ReceiveStockAsync(new(p,s,x.Quantity,InventoryRules.D(rows[0]["unit_cost"]),"PurchaseOrder",r.Id,$"purchase:{r.Id}:{x.PurchaseOrderItemId}:{InventoryRules.D(rows[0]["pending"])}",x.BatchCode,x.ExpiresAt),ct);await data.WriteAsync("update barber.inventory_purchase_order_items set received_quantity=received_quantity+@quantity,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","Inventory360.PurchaseItemReceived","inventory_purchase_order_items",x.PurchaseOrderItemId,null,c=>A(c,"quantity",x.Quantity),ct);}var receiving=await data.WriteAsync("insert into barber.inventory_receivings(id,tenant_id,branch_id,purchase_order_id,supplier_id,status,received_at) select @id,@tenant,@branch,id,supplier_id,'Confirmed',@received from barber.inventory_purchase_orders where id=@order and tenant_id=@tenant and branch_id=@branch and status in ('Approved','PartiallyReceived')","Inventory360.PurchaseReceived","inventory_receivings",null,null,c=>{A(c,"order",r.Id);A(c,"received",r.ReceivedAt);},ct);await data.WriteAsync("update barber.inventory_purchase_orders o set status=case when exists(select 1 from barber.inventory_purchase_order_items i where i.purchase_order_id=o.id and i.received_quantity<i.quantity) then 'PartiallyReceived' else 'Received' end,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","Inventory360.PurchaseStatus","inventory_purchase_orders",r.Id,null,null,ct);if(r.CreatePayable){var o=(await data.QueryAsync("select supplier_id,total_amount,coalesce(expected_at,current_date) due from barber.inventory_purchase_orders where id=@order and tenant_id=@tenant and branch_id=@branch",c=>A(c,"order",r.Id),ct)).Single();await payable.CreatePayableAsync(new(o["supplier_id"] as Guid?,null,null,"InventoryPurchase",receiving,"Compra de estoque",InventoryRules.D(o["total_amount"]),DateTime.SpecifyKind(((DateOnly)o["due"]!).ToDateTime(TimeOnly.MinValue),DateTimeKind.Utc),false),ct);}return new(receiving,"Confirmed");}
    public async Task<SupplierReturnResult> ReturnToSupplierAsync(ReturnToSupplierRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason)||r.Items.Count==0)throw new ArgumentException("Motivo e itens são obrigatórios.");var id=await data.WriteAsync("insert into barber.inventory_supplier_returns(id,tenant_id,branch_id,supplier_id,purchase_order_id,status,reason) select @id,@tenant,@branch,supplier_id,id,'Confirmed',@reason from barber.inventory_purchase_orders where id=@order and tenant_id=@tenant and branch_id=@branch","Inventory360.SupplierReturnConfirmed","inventory_supplier_returns",null,r.Reason,c=>{A(c,"order",r.Id);A(c,"reason",r.Reason);},ct);foreach(var x in r.Items){var row=(await data.QueryAsync("select product_id,supply_id from barber.inventory_purchase_order_items where id=@item and purchase_order_id=@order and tenant_id=@tenant and branch_id=@branch",c=>{A(c,"item",x.PurchaseOrderItemId);A(c,"order",r.Id);},ct)).Single();await stock.ConsumeStockAsync(new(row["product_id"] as Guid?,row["supply_id"] as Guid?,x.Quantity,"SupplierReturn",id,$"return:{id}:{x.PurchaseOrderItemId}"),ct);}return new(id,"Confirmed");} private static void A(DbCommand c,string n,object? v)=>InventoryRules.Add(c,n,v);
}

public sealed class InventoryCountService(TeamDataService data,StockMovementService stock)
{
    public async Task<InventoryCountResult> OpenCountAsync(OpenInventoryCountRequest r,CancellationToken ct){var id=await data.WriteAsync("insert into barber.inventory_counts(id,tenant_id,branch_id,count_date,status) select @id,@tenant,@branch,@date,'Open' where not exists(select 1 from barber.inventory_counts where tenant_id=@tenant and branch_id=@branch and count_date=@date and status in ('Open','Reviewing'))","Inventory360.CountOpened","inventory_counts",null,null,c=>A(c,"date",r.CountDate),ct);return new(id,"Open");}
    public async Task<InventoryCountResult> RegisterCountItemAsync(RegisterInventoryCountItemRequest r,CancellationToken ct){InventoryRules.Item(r.ProductId,r.SupplyId);if(r.CountedQuantity<0)throw new ArgumentException("Contagem não pode ser negativa.");var expected=(await data.QueryAsync("select coalesce(quantity_on_hand,0) expected from barber.inventory_stock_balances where tenant_id=@tenant and branch_id=@branch and product_id is not distinct from @product and supply_id is not distinct from @supply",c=>{A(c,"product",r.ProductId);A(c,"supply",r.SupplyId);},ct)).SingleOrDefault();var qty=expected is null?0:InventoryRules.D(expected["expected"]);if(qty!=r.CountedQuantity&&string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Divergência exige motivo.");await data.WriteAsync("insert into barber.inventory_count_items(id,tenant_id,branch_id,inventory_count_id,product_id,supply_id,batch_id,system_quantity,expected_quantity,counted_quantity,difference_quantity,notes,reason,status) select @id,@tenant,@branch,c.id,@product,@supply,@batch,@expected,@expected,@counted,@counted-@expected,@reason,@reason,'Reviewed' from barber.inventory_counts c where c.id=@count and c.tenant_id=@tenant and c.branch_id=@branch and c.status='Open'","Inventory360.CountItemRegistered","inventory_count_items",null,r.Reason,c=>{A(c,"count",r.CountId);A(c,"product",r.ProductId);A(c,"supply",r.SupplyId);A(c,"batch",r.BatchId);A(c,"expected",qty);A(c,"counted",r.CountedQuantity);A(c,"reason",r.Reason);},ct);return new(r.CountId,"Open");}
    public async Task<InventoryCountResult> CloseCountAsync(CloseInventoryCountRequest r,CancellationToken ct){await data.WriteAsync("update barber.inventory_counts set status='Reviewing',updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Open' and exists(select 1 from barber.inventory_count_items where inventory_count_id=@id and status='Reviewed')","Inventory360.CountClosed","inventory_counts",r.Id,null,null,ct);return new(r.Id,"Reviewing");}
    public async Task<InventoryAdjustmentResult> ApplyAdjustmentAsync(ApplyInventoryAdjustmentRequest r,CancellationToken ct){var rows=await data.QueryAsync("select id,product_id,supply_id,difference_quantity,reason from barber.inventory_count_items where inventory_count_id=@count and tenant_id=@tenant and branch_id=@branch and status='Reviewed'",c=>A(c,"count",r.Id),ct);foreach(var x in rows){var q=InventoryRules.D(x["difference_quantity"]);if(q>0)await stock.ReceiveStockAsync(new(x["product_id"] as Guid?,x["supply_id"] as Guid?,q,0,"InventoryCount",r.Id,$"count:{r.Id}:{x["id"]}",null,null),ct);else if(q<0)await stock.ConsumeStockAsync(new(x["product_id"] as Guid?,x["supply_id"] as Guid?,-q,"InventoryCount",r.Id,$"count:{r.Id}:{x["id"]}"),ct);}await data.WriteAsync("update barber.inventory_count_items set status='Adjusted',updated_at=now() where inventory_count_id=@id and tenant_id=@tenant and branch_id=@branch; update barber.inventory_counts set status='Closed',closed_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","Inventory360.CountAdjusted","inventory_counts",r.Id,null,null,ct);return new(r.Id,"Closed");} private static void A(DbCommand c,string n,object? v)=>InventoryRules.Add(c,n,v);
}

public sealed class ReplenishmentService(TeamDataService data,PurchaseOrderService purchases)
{
    public async Task<ReplenishmentDashboardResult> GetDashboardAsync(ReplenishmentDashboardRequest r,CancellationToken ct)=>new(await data.QueryAsync("select s.*,p.name product_name,i.name supply_name from barber.inventory_replenishment_suggestions s left join barber.inventory_products p on p.id=s.product_id left join barber.inventory_supplies i on i.id=s.supply_id where s.tenant_id=@tenant and s.branch_id=@branch and s.status='Open' order by s.created_at",null,ct));
    public async Task<ReplenishmentSuggestionResult> GenerateSuggestionsAsync(GenerateReplenishmentSuggestionsRequest r,CancellationToken ct){var rows=await data.QueryAsync(@"insert into barber.inventory_replenishment_suggestions(id,tenant_id,branch_id,product_id,supply_id,suggested_quantity,reason,source_status,status) select gen_random_uuid(),r.tenant_id,r.branch_id,r.product_id,r.supply_id,r.target_quantity-coalesce(b.quantity_available,0),'Saldo abaixo do mínimo',case when b.id is null then 'InsufficientHistory' else 'Available' end,'Open' from barber.inventory_replenishment_rules r left join barber.inventory_stock_balances b on b.tenant_id=r.tenant_id and b.branch_id=r.branch_id and b.product_id is not distinct from r.product_id and b.supply_id is not distinct from r.supply_id where r.tenant_id=@tenant and r.branch_id=@branch and r.status='Active' and coalesce(b.quantity_available,0)<=r.minimum_quantity and not exists(select 1 from barber.inventory_replenishment_suggestions s where s.tenant_id=r.tenant_id and s.branch_id=r.branch_id and s.product_id is not distinct from r.product_id and s.supply_id is not distinct from r.supply_id and s.status='Open') returning id",null,ct);return new(rows.Count,rows.Count==0?"InsufficientData":"Available");}
    public async Task<PurchaseOrderResult> CreatePurchaseOrderFromSuggestionAsync(CreatePurchaseOrderFromSuggestionRequest r,CancellationToken ct){var row=(await data.QueryAsync("select s.product_id,s.supply_id,s.suggested_quantity,r.preferred_supplier_id,coalesce(p.cost_price,i.default_cost) cost from barber.inventory_replenishment_suggestions s join barber.inventory_replenishment_rules r on r.tenant_id=s.tenant_id and r.branch_id=s.branch_id and r.product_id is not distinct from s.product_id and r.supply_id is not distinct from s.supply_id left join barber.inventory_products p on p.id=s.product_id left join barber.inventory_supplies i on i.id=s.supply_id where s.id=@id and s.tenant_id=@tenant and s.branch_id=@branch and s.status='Open' and r.preferred_supplier_id is not null",c=>A(c,"id",r.Id),ct)).SingleOrDefault()??throw new InvalidOperationException("Sugestão sem fornecedor confirmado.");if(row["cost"] is null)throw new InvalidOperationException("Custo indisponível; compra não pode ser criada.");var order=await purchases.CreatePurchaseOrderAsync(new((Guid)row["preferred_supplier_id"]!,null,[new(row["product_id"] as Guid?,row["supply_id"] as Guid?,InventoryRules.D(row["suggested_quantity"]),InventoryRules.D(row["cost"]))]),ct);await data.WriteAsync("update barber.inventory_replenishment_suggestions set status='ConvertedToPurchase',purchase_order_id=@order,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","Inventory360.SuggestionConverted","inventory_replenishment_suggestions",r.Id,null,c=>A(c,"order",order.Id),ct);return order;} private static void A(DbCommand c,string n,object? v)=>InventoryRules.Add(c,n,v);
}
