using System.Data;
using System.Text.Json;
using BarberSync.Api.Security;
using BarberSync.Api.Services.Catalog;
using Npgsql;

namespace BarberSync.Api.Services.ServiceExecution;

public sealed record CheckInRequest(Guid AppointmentId, bool OpenOrder, string? DeviceCode);
public sealed record OpenOrderFromAppointmentRequest(Guid AppointmentId);
public sealed record AddServiceToOrderRequest(Guid ServiceOrderId, Guid ServiceId, Guid ProfessionalId, decimal Quantity = 1m);
public sealed record AddProductToOrderRequest(Guid ServiceOrderId, Guid ProductId, decimal Quantity = 1m);
public sealed record StartServiceRequest(Guid ServiceOrderId, Guid ProfessionalId);
public sealed record CompleteServiceRequest(Guid ServiceOrderId, Guid ProfessionalId);
public sealed record CancelServiceRequest(Guid ServiceOrderId, string Reason);
public sealed record CloseServiceOrderRequest(Guid ServiceOrderId);
public sealed record CheckInResult(Guid AppointmentId, DateTimeOffset CheckedInAt, bool Late, Guid? ServiceOrderId);
public sealed record ServiceOrderResult(Guid ServiceOrderId, string Status, decimal Total);
public sealed record CheckoutPreviewRequest(Guid ServiceOrderId, decimal DiscountAmount = 0m, decimal BenefitAmount = 0m);
public sealed record ApplyDiscountRequest(Guid ServiceOrderId, decimal Amount, string Reason);
public sealed record ApplyBenefitRequest(Guid ServiceOrderId, string BenefitType, Guid BenefitId, decimal Amount);
public sealed record CreatePaymentIntentRequest(Guid ServiceOrderId, string PaymentMethod, decimal Amount, string IdempotencyKey);
public sealed record ConfirmCheckoutRequest(Guid ServiceOrderId, Guid PaymentId);
public sealed record CancelCheckoutRequest(Guid ServiceOrderId, string Reason);
public sealed record CheckoutPreviewResult(Guid ServiceOrderId, decimal Subtotal, decimal Discount, decimal Benefit, decimal Total, bool Mutated = false);
public sealed record DiscountApplicationResult(Guid CheckoutSessionId, decimal Discount, decimal Total);
public sealed record BenefitApplicationResult(Guid CheckoutSessionId, string BenefitType, decimal Amount, decimal Total);
public sealed record PaymentIntentResult(Guid PaymentId, string Status, decimal Amount);
public sealed record CheckoutResult(Guid CheckoutSessionId, string Status, decimal Total);
public sealed record PaymentAllocationRequest(Guid CheckoutSessionId, Guid PaymentId, string PaymentMethod, decimal Amount, bool PartialAllowed);
public sealed record PaymentReversalRequest(Guid PaymentId, string Reason);
public sealed record PaymentAllocationResult(Guid AllocationId, string Status, decimal Amount);
public sealed record PaymentReversalResult(Guid AllocationId, string Status);
public sealed record PaymentStatusResult(Guid PaymentId, string Status, decimal Amount);
public sealed record ConsumptionPreviewRequest(Guid ServiceOrderId);
public sealed record ConsumeForServiceRequest(Guid ServiceOrderId, Guid ServiceId);
public sealed record ConsumeForProductSaleRequest(Guid ServiceOrderId, Guid ProductId, decimal Quantity);
public sealed record ReverseConsumptionRequest(Guid ConsumptionId, string Reason);
public sealed record InventoryConsumptionPreview(Guid ServiceOrderId, IReadOnlyList<Dictionary<string, object?>> Items, bool Mutated = false);
public sealed record InventoryConsumptionResult(Guid ConsumptionId, string Status, decimal Quantity);
public sealed record InventoryReversalResult(Guid ConsumptionId, Guid ReversalMovementId, string Status);
public sealed record CommissionPreviewRequest(Guid ServiceOrderId);
public sealed record AccrueProfessionalCommissionRequest(Guid ServiceOrderId, Guid ProfessionalId, Guid SourceId, string SourceType, decimal BaseAmount, decimal Percent);
public sealed record AccruePartnerCommissionRequest(Guid ServiceOrderId, Guid PartnerId, Guid SourceId, string SourceType, decimal BaseAmount, decimal Percent);
public sealed record ReverseCommissionRequest(Guid CommissionId, string Reason);
public sealed record CommissionPreviewResult(Guid ServiceOrderId, IReadOnlyList<Dictionary<string, object?>> Items, bool Mutated = false);
public sealed record CommissionAccrualResult(Guid CommissionId, string Status, decimal Amount);
public sealed record CommissionReversalResult(Guid CommissionId, string Status);
public sealed record OpenCashSessionRequest(decimal OpeningAmount);
public sealed record CloseCashSessionRequest(Guid CashSessionId, decimal DeclaredAmount, string? Reason);
public sealed record CashSessionSummaryRequest(Guid CashSessionId);
public sealed record CashAdjustmentRequest(Guid CashSessionId, decimal Amount, string Reason);
public sealed record CashSessionResult(Guid CashSessionId, string Status, decimal ExpectedAmount, decimal? Difference);
public sealed record CashSessionSummaryResult(Guid CashSessionId, decimal Opening, decimal Movements, decimal Expected);
public sealed record CashSessionAuditResult(Guid MovementId, decimal Amount);

public sealed class ServiceExecutionStore(IConfiguration configuration, ICurrentUserContext current)
{
    public ICurrentUserContext Current => current;
    public async Task<NpgsqlConnection> Open(CancellationToken ct) { var c = new NpgsqlConnection(configuration.GetConnectionString("DefaultConnection") ?? throw new InvalidOperationException("Banco não configurado.")); await c.OpenAsync(ct); return c; }
    public NpgsqlCommand Command(NpgsqlConnection c, NpgsqlTransaction? tx, string sql) { var cmd = new NpgsqlCommand(sql, c, tx); cmd.Parameters.AddWithValue("tenant", current.TenantId); cmd.Parameters.AddWithValue("branch", current.BranchId); cmd.Parameters.AddWithValue("user", current.UserId); return cmd; }
    public static void Add(NpgsqlCommand c, string name, object? value) => c.Parameters.AddWithValue(name, value ?? DBNull.Value);
    public async Task<IReadOnlyList<Dictionary<string, object?>>> Query(string sql, Action<NpgsqlCommand>? bind, CancellationToken ct) { await using var c=await Open(ct); await using var cmd=Command(c,null,sql);bind?.Invoke(cmd);await using var reader=await cmd.ExecuteReaderAsync(ct);var rows=new List<Dictionary<string,object?>>();while(await reader.ReadAsync(ct)){var row=new Dictionary<string,object?>(StringComparer.OrdinalIgnoreCase);for(var i=0;i<reader.FieldCount;i++)row[reader.GetName(i)]=reader.IsDBNull(i)?null:reader.GetValue(i);rows.Add(row);}return rows; }
}

public sealed class ServiceExecutionOrchestrator(ServiceExecutionStore store, CatalogPricingService pricing)
{
    public async Task<CheckInResult> CheckInAppointmentAsync(CheckInRequest request,CancellationToken ct){await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(IsolationLevel.Serializable,ct);var now=DateTimeOffset.UtcNow;await using var cmd=store.Command(c,tx,@"update barber.appointments set status='CheckedIn',checked_in_at=@now,updated_at=@now where id=@appointment and tenant_id=@tenant and branch_id=@branch and status in ('Scheduled','Confirmed') and checked_in_at is null returning scheduled_start");ServiceExecutionStore.Add(cmd,"appointment",request.AppointmentId);ServiceExecutionStore.Add(cmd,"now",now);var scheduled=await cmd.ExecuteScalarAsync(ct);if(scheduled is null)throw new InvalidOperationException("Agendamento inválido, cancelado, no-show ou já recebeu check-in.");Guid? order=null;if(request.OpenOrder){order=Guid.NewGuid();await using var open=store.Command(c,tx,"insert into barber.service_orders(id,tenant_id,branch_id,appointment_id,client_id,number,status) select @id,@tenant,@branch,id,client_id,'AT-'||to_char(now(),'YYYYMMDD-HH24MISS'),'Open' from barber.appointments where id=@appointment and tenant_id=@tenant and branch_id=@branch and status='CheckedIn' and not exists(select 1 from barber.service_orders where appointment_id=@appointment and tenant_id=@tenant and deleted_at is null)");ServiceExecutionStore.Add(open,"id",order.Value);ServiceExecutionStore.Add(open,"appointment",request.AppointmentId);if(await open.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Já existe comanda para o agendamento.");}await Event(c,tx,order,request.AppointmentId,"CheckIn","Completed",request.DeviceCode is null?"Check-in administrativo":$"Check-in por dispositivo {request.DeviceCode}",ct);await tx.CommitAsync(ct);return new(request.AppointmentId,now,scheduled is DateTimeOffset s&&now>s,order);}
    public async Task<ServiceOrderResult> OpenServiceOrderFromAppointmentAsync(OpenOrderFromAppointmentRequest r,CancellationToken ct){var check=await CheckInAppointmentAsync(new(r.AppointmentId,true,null),ct);return new(check.ServiceOrderId!.Value,"Open",0m);}
    public Task<ServiceOrderResult> AddServiceToOrderAsync(AddServiceToOrderRequest r,CancellationToken ct)=>AddItem(r.ServiceOrderId,"Service",r.ServiceId,r.ProfessionalId,r.Quantity,ct);
    public Task<ServiceOrderResult> AddProductToOrderAsync(AddProductToOrderRequest r,CancellationToken ct)=>AddItem(r.ServiceOrderId,"Product",r.ProductId,null,r.Quantity,ct);
    private async Task<ServiceOrderResult> AddItem(Guid order,string type,Guid item,Guid? professional,decimal quantity,CancellationToken ct){if(quantity<=0)throw new ArgumentException("Quantidade deve ser positiva.");await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(IsolationLevel.Serializable,ct);var sql=type=="Service"?"select p.base_price,p.estimated_cost from barber.catalog_service_profiles p where p.service_id=@item and p.tenant_id=@tenant and p.branch_id=@branch and p.status='Active' and p.deleted_at is null":"select p.sale_price,p.cost_price from barber.catalog_product_profiles p where p.product_id=@item and p.tenant_id=@tenant and p.branch_id=@branch and p.status='Active' and p.deleted_at is null";decimal priceValue,cost;await using(var q=store.Command(c,tx,sql)){ServiceExecutionStore.Add(q,"item",item);await using var reader=await q.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))throw new InvalidOperationException("Item não está ativo no Catálogo.");priceValue=reader.GetDecimal(0);cost=reader.GetDecimal(1);}var calculated=pricing.Calculate(new(item,type,priceValue,cost,[]));var snapshot=Guid.NewGuid();await using(var add=store.Command(c,tx,@"insert into barber.service_order_pricing_snapshots(id,tenant_id,branch_id,service_order_id,source_type,source_id,base_price,final_price,cost_amount,margin_percent,pricing_breakdown_json) select @snapshot,@tenant,@branch,id,@type,@item,@base,@final,@cost,@margin,@breakdown::jsonb from barber.service_orders where id=@order and tenant_id=@tenant and branch_id=@branch and status='Open'")){ServiceExecutionStore.Add(add,"snapshot",snapshot);ServiceExecutionStore.Add(add,"type",type);ServiceExecutionStore.Add(add,"item",item);ServiceExecutionStore.Add(add,"base",priceValue*quantity);ServiceExecutionStore.Add(add,"final",calculated.FinalPrice*quantity);ServiceExecutionStore.Add(add,"cost",cost*quantity);ServiceExecutionStore.Add(add,"margin",calculated.MarginPercent);ServiceExecutionStore.Add(add,"breakdown",JsonSerializer.Serialize(calculated));ServiceExecutionStore.Add(add,"order",order);if(await add.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Comanda não está aberta para edição.");}await using(var total=store.Command(c,tx,"update barber.service_orders set subtotal=subtotal+@amount,total=total+@amount,updated_at=now() where id=@order and tenant_id=@tenant and branch_id=@branch and status='Open' returning total")){ServiceExecutionStore.Add(total,"amount",calculated.FinalPrice*quantity);ServiceExecutionStore.Add(total,"order",order);var value=(decimal)(await total.ExecuteScalarAsync(ct)??throw new InvalidOperationException("Comanda inválida."));await tx.CommitAsync(ct);return new(order,"Open",value);}}
    public Task<ServiceOrderResult> StartServiceAsync(StartServiceRequest r,CancellationToken ct)=>State(r.ServiceOrderId,"Open","InService","ServiceStarted",ct);
    public async Task<ServiceOrderResult> CompleteServiceAsync(CompleteServiceRequest r,CancellationToken ct){var result=await State(r.ServiceOrderId,"InService","ServiceCompleted","ServiceCompleted",ct);return result;}
    public Task<ServiceOrderResult> CancelServiceAsync(CancelServiceRequest r,CancellationToken ct)=>string.IsNullOrWhiteSpace(r.Reason)?throw new ArgumentException("Motivo obrigatório."):State(r.ServiceOrderId,"InService","Cancelled","ServiceCancelled",ct,r.Reason);
    public Task<ServiceOrderResult> CloseServiceOrderAsync(CloseServiceOrderRequest r,CancellationToken ct)=>State(r.ServiceOrderId,"Paid","Closed","OrderClosed",ct);
    private async Task<ServiceOrderResult> State(Guid id,string expected,string next,string eventType,CancellationToken ct,string? description=null){await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);decimal total;Guid? appointment;Guid? client;await using(var cmd=store.Command(c,tx,"update barber.service_orders set status=@next,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status=@expected returning total,appointment_id,client_id")){ServiceExecutionStore.Add(cmd,"id",id);ServiceExecutionStore.Add(cmd,"next",next);ServiceExecutionStore.Add(cmd,"expected",expected);await using var reader=await cmd.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))throw new InvalidOperationException("Transição de estado da comanda não permitida.");total=reader.GetDecimal(0);appointment=reader.IsDBNull(1)?null:reader.GetGuid(1);client=reader.IsDBNull(2)?null:reader.GetGuid(2);}await Event(c,tx,id,appointment,eventType,next,description??eventType,ct);if(next=="ServiceCompleted"&&client.HasValue){await using var timeline=store.Command(c,tx,"insert into barber.client_timeline_events(id,tenant_id,branch_id,client_id,event_type,event_title,event_description,source_type,source_id) values(gen_random_uuid(),@tenant,@branch,@client,'ServiceCompleted','Atendimento concluído','Serviço concluído e disponível no histórico.','ServiceOrder',@id)");ServiceExecutionStore.Add(timeline,"client",client.Value);ServiceExecutionStore.Add(timeline,"id",id);await timeline.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return new(id,next,total);}
    private async Task Event(NpgsqlConnection c,NpgsqlTransaction tx,Guid? order,Guid? appointment,string type,string status,string description,CancellationToken ct){await using var cmd=store.Command(c,tx,"insert into barber.service_execution_events(id,tenant_id,branch_id,service_order_id,appointment_id,event_type,status,description,created_by) values(gen_random_uuid(),@tenant,@branch,@order,@appointment,@type,@status,@description,@user)");ServiceExecutionStore.Add(cmd,"order",order);ServiceExecutionStore.Add(cmd,"appointment",appointment);ServiceExecutionStore.Add(cmd,"type",type);ServiceExecutionStore.Add(cmd,"status",status);ServiceExecutionStore.Add(cmd,"description",description);await cmd.ExecuteNonQueryAsync(ct);}
}

public sealed class CheckoutOrchestrationService(ServiceExecutionStore store, PaymentAllocationService allocations)
{
 public async Task<CheckoutPreviewResult> PreviewCheckoutAsync(CheckoutPreviewRequest r,CancellationToken ct){var rows=await store.Query("select subtotal,discount,total from barber.service_orders where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','ServiceCompleted','Checkout')",c=>ServiceExecutionStore.Add(c,"id",r.ServiceOrderId),ct);if(rows.Count!=1)throw new InvalidOperationException("Comanda indisponível para checkout.");var subtotal=(decimal)rows[0]["subtotal"]!;if(r.DiscountAmount<0||r.BenefitAmount<0||r.DiscountAmount+r.BenefitAmount>subtotal)throw new ArgumentException("Descontos e benefícios não podem superar o subtotal.");return new(r.ServiceOrderId,subtotal,r.DiscountAmount,r.BenefitAmount,decimal.Round(subtotal-r.DiscountAmount-r.BenefitAmount,2),false);}
 public async Task<DiscountApplicationResult> ApplyDiscountAsync(ApplyDiscountRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Motivo obrigatório.");var p=await PreviewCheckoutAsync(new(r.ServiceOrderId,r.Amount),ct);var id=await Upsert(r.ServiceOrderId,p,r.Amount,0m,ct);return new(id,r.Amount,p.Total);}
 public async Task<BenefitApplicationResult> ApplyBenefitAsync(ApplyBenefitRequest r,CancellationToken ct){if(!new[]{"Voucher","Coupon","GiftCard","Wallet","Cashback","Package","Membership"}.Contains(r.BenefitType))throw new ArgumentException("Origem do benefício inválida.");var p=await PreviewCheckoutAsync(new(r.ServiceOrderId,0m,r.Amount),ct);var id=await Upsert(r.ServiceOrderId,p,0m,r.Amount,ct,r.BenefitType,r.BenefitId);return new(id,r.BenefitType,r.Amount,p.Total);}
 private async Task<Guid> Upsert(Guid order,CheckoutPreviewResult p,decimal discount,decimal benefit,CancellationToken ct,string? type=null,Guid? benefitId=null){await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(IsolationLevel.Serializable,ct);var id=Guid.NewGuid();await using var cmd=store.Command(c,tx,@"insert into barber.checkout_sessions(id,tenant_id,branch_id,service_order_id,client_id,status,subtotal,discount_total,benefit_total,total,benefits_json,created_by) select @id,@tenant,@branch,o.id,o.client_id,'Draft',o.subtotal,@discount,@benefit,@total,jsonb_build_object('type',@type,'id',@benefit_id),@user from barber.service_orders o where o.id=@order and o.tenant_id=@tenant and o.branch_id=@branch and o.status in ('Open','ServiceCompleted') and not exists(select 1 from barber.checkout_sessions s where s.service_order_id=o.id and s.status not in ('Cancelled','Failed'))");foreach(var x in new[]{("id",(object?)id),("order",order),("discount",discount),("benefit",benefit),("total",p.Total),("type",type),("benefit_id",benefitId)})ServiceExecutionStore.Add(cmd,x.Item1,x.Item2);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Checkout ativo já existe ou a comanda não permite checkout.");await tx.CommitAsync(ct);return id;}
 public async Task<PaymentIntentResult> CreatePaymentIntentAsync(CreatePaymentIntentRequest r,CancellationToken ct){if(r.Amount<=0||string.IsNullOrWhiteSpace(r.IdempotencyKey)||string.IsNullOrWhiteSpace(r.PaymentMethod))throw new ArgumentException("Método, valor e chave de idempotência são obrigatórios.");await using var c=await store.Open(ct);var id=Guid.NewGuid();await using var cmd=store.Command(c,null,@"insert into barber.payments(id,tenant_id,branch_id,service_order_id,idempotency_key,method,amount,status) select @id,@tenant,@branch,@order,@key,@method,@amount,'Pending' where exists(select 1 from barber.checkout_sessions where service_order_id=@order and tenant_id=@tenant and branch_id=@branch and status='Draft') on conflict(tenant_id,idempotency_key) do nothing");foreach(var x in new[]{("id",(object?)id),("order",r.ServiceOrderId),("key",r.IdempotencyKey),("method",r.PaymentMethod),("amount",r.Amount)})ServiceExecutionStore.Add(cmd,x.Item1,x.Item2);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Intenção duplicada ou checkout inexistente.");return new(id,"Pending",r.Amount);}
 public async Task<CheckoutResult> ConfirmCheckoutAsync(ConfirmCheckoutRequest r,CancellationToken ct){var rows=await store.Query("select id,total from barber.checkout_sessions where service_order_id=@order and tenant_id=@tenant and branch_id=@branch and status='Draft'",c=>ServiceExecutionStore.Add(c,"order",r.ServiceOrderId),ct);if(rows.Count!=1)throw new InvalidOperationException("Checkout não está em rascunho.");var session=(Guid)rows[0]["id"]!;var total=(decimal)rows[0]["total"]!;var status=await allocations.ResolvePaymentStatusAsync(r.PaymentId,ct);if(status.Status!="Confirmed")throw new InvalidOperationException("Pagamento pendente não fecha a comanda.");await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);await using var cmd=store.Command(c,tx,@"update barber.checkout_sessions set status='Paid',completed_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Draft';
update barber.service_orders set status='Paid',updated_at=now() where id=@order and tenant_id=@tenant and branch_id=@branch and status in ('Open','ServiceCompleted','Checkout');
insert into barber.finance_receivables(id,tenant_id,branch_id,client_id,source_type,source_id,description,amount,paid_amount,due_at,status,payment_id,created_by,paid_at)
select gen_random_uuid(),s.tenant_id,s.branch_id,s.client_id,'Checkout',s.id,'Checkout confirmado',s.total,s.total,now(),'Paid',@payment,@user,now() from barber.checkout_sessions s join barber.payments p on p.id=@payment and p.tenant_id=s.tenant_id and p.branch_id=s.branch_id and p.status='Confirmed' where s.id=@id on conflict(tenant_id,branch_id,source_type,source_id) do nothing;
insert into barber.finance_postings(id,tenant_id,branch_id,posting_type,source_type,source_id,amount,direction,status,idempotency_key,posted_at,created_by,metadata_json)
select gen_random_uuid(),s.tenant_id,s.branch_id,'Revenue','Checkout',s.id,s.total,'Credit','Confirmed','checkout:'||s.id,now(),@user,jsonb_build_object('paymentId',@payment) from barber.checkout_sessions s join barber.payments p on p.id=@payment and p.tenant_id=s.tenant_id and p.branch_id=s.branch_id and p.status='Confirmed' where s.id=@id on conflict(tenant_id,branch_id,idempotency_key) do nothing;
insert into barber.finance_audit_events(id,tenant_id,branch_id,event_type,source_type,source_id,description,new_status,amount,created_by,metadata_json)
select gen_random_uuid(),tenant_id,branch_id,'CheckoutPosted','Checkout',id,'Checkout confirmado e lançado no razão','Confirmed',total,@user,jsonb_build_object('paymentId',@payment) from barber.checkout_sessions where id=@id and not exists(select 1 from barber.finance_audit_events where tenant_id=@tenant and branch_id=@branch and event_type='CheckoutPosted' and source_id=@id)");ServiceExecutionStore.Add(cmd,"id",session);ServiceExecutionStore.Add(cmd,"order",r.ServiceOrderId);ServiceExecutionStore.Add(cmd,"payment",r.PaymentId);if(await cmd.ExecuteNonQueryAsync(ct)<1)throw new InvalidOperationException("Checkout não confirmado atomicamente.");await tx.CommitAsync(ct);return new(session,"Paid",total);}
 public async Task<CheckoutResult> CancelCheckoutAsync(CancelCheckoutRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Motivo obrigatório.");await using var c=await store.Open(ct);await using var cmd=store.Command(c,null,"update barber.checkout_sessions set status='Cancelled',cancelled_at=now(),cancel_reason=@reason,updated_at=now() where service_order_id=@order and tenant_id=@tenant and branch_id=@branch and status in ('Draft','PendingPayment') returning id,total");ServiceExecutionStore.Add(cmd,"reason",r.Reason);ServiceExecutionStore.Add(cmd,"order",r.ServiceOrderId);await using var reader=await cmd.ExecuteReaderAsync(ct);if(!await reader.ReadAsync(ct))throw new InvalidOperationException("Checkout não cancelável.");return new(reader.GetGuid(0),"Cancelled",reader.GetDecimal(1));}
}

public sealed class PaymentAllocationService(ServiceExecutionStore store)
{
 public async Task<PaymentAllocationResult> AllocatePaymentAsync(PaymentAllocationRequest r,CancellationToken ct){if(r.Amount<=0)throw new ArgumentException("Valor inválido.");await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(IsolationLevel.Serializable,ct);var id=Guid.NewGuid();await using var cmd=store.Command(c,tx,@"insert into barber.checkout_payment_allocations(id,tenant_id,branch_id,checkout_session_id,payment_id,payment_method,amount,status,confirmed_at) select @id,@tenant,@branch,s.id,p.id,@method,@amount,'Confirmed',now() from barber.checkout_sessions s join barber.payments p on p.id=@payment and p.service_order_id=s.service_order_id and p.tenant_id=s.tenant_id where s.id=@session and s.tenant_id=@tenant and s.branch_id=@branch and p.status='Confirmed' and @amount<=s.total and not exists(select 1 from barber.checkout_payment_allocations where payment_id=p.id and status<>'Reversed')");foreach(var x in new[]{("id",(object?)id),("session",r.CheckoutSessionId),("payment",r.PaymentId),("method",r.PaymentMethod),("amount",r.Amount)})ServiceExecutionStore.Add(cmd,x.Item1,x.Item2);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Pagamento não confirmado, duplicado ou excede o checkout.");await tx.CommitAsync(ct);return new(id,"Confirmed",r.Amount);}
 public async Task<PaymentReversalResult> ReversePaymentAllocationAsync(PaymentReversalRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Motivo obrigatório.");await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);Guid id;await using(var cmd=store.Command(c,tx,"update barber.checkout_payment_allocations set status='Reversed',reversed_at=now(),metadata_json=jsonb_build_object('reason',@reason) where payment_id=@payment and tenant_id=@tenant and branch_id=@branch and status='Confirmed' returning id")){ServiceExecutionStore.Add(cmd,"reason",r.Reason);ServiceExecutionStore.Add(cmd,"payment",r.PaymentId);id=(Guid)(await cmd.ExecuteScalarAsync(ct)??throw new InvalidOperationException("Allocation não reversível."));}await using(var reopen=store.Command(c,tx,"update barber.payments set status='Reversed',updated_at=now() where id=@payment and tenant_id=@tenant and branch_id=@branch; update barber.checkout_sessions s set status='PendingPayment',updated_at=now() from barber.payments p where p.id=@payment and p.service_order_id=s.service_order_id and s.status='Paid'")){ServiceExecutionStore.Add(reopen,"payment",r.PaymentId);await reopen.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return new(id,"Reversed");}
 public async Task<PaymentStatusResult> ResolvePaymentStatusAsync(Guid paymentId,CancellationToken ct){var rows=await store.Query("select id,status,amount from barber.payments where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null",c=>ServiceExecutionStore.Add(c,"id",paymentId),ct);if(rows.Count!=1)throw new InvalidOperationException("Pagamento inexistente.");return new(paymentId,(string)rows[0]["status"]!,(decimal)rows[0]["amount"]!);}
}

public sealed class InventoryConsumptionService(ServiceExecutionStore store)
{
 public async Task<InventoryConsumptionPreview> PreviewConsumptionAsync(ConsumptionPreviewRequest r,CancellationToken ct)=>new(r.ServiceOrderId,await store.Query("select s.source_id product_id,1::numeric quantity,s.cost_amount unit_cost from barber.service_order_pricing_snapshots s where s.service_order_id=@order and s.tenant_id=@tenant and s.branch_id=@branch and s.source_type='Product'",c=>ServiceExecutionStore.Add(c,"order",r.ServiceOrderId),ct),false);
 public Task<InventoryConsumptionResult> ConsumeForServiceAsync(ConsumeForServiceRequest r,CancellationToken ct)=>Consume(r.ServiceOrderId,r.ServiceId,1m,ct);
 public Task<InventoryConsumptionResult> ConsumeForProductSaleAsync(ConsumeForProductSaleRequest r,CancellationToken ct)=>Consume(r.ServiceOrderId,r.ProductId,r.Quantity,ct);
 private async Task<InventoryConsumptionResult> Consume(Guid order,Guid product,decimal quantity,CancellationToken ct){if(quantity<=0)throw new ArgumentException("Quantidade inválida.");await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(IsolationLevel.Serializable,ct);var movement=Guid.NewGuid();var consumption=Guid.NewGuid();await using var cmd=store.Command(c,tx,@"with changed as(update barber.products set current_stock=current_stock-@quantity,updated_at=now() where id=@product and tenant_id=@tenant and branch_id=@branch and deleted_at is null and (allow_negative_stock or current_stock>=@quantity) returning current_stock,cost_price), moved as(insert into barber.stock_movements(id,tenant_id,branch_id,product_id,service_order_id,type,quantity,balance_after,reason,created_by) select @movement,@tenant,@branch,@product,@order,'Consumption',-@quantity,current_stock,'Consumo Atendimento 360',@user from changed returning id) insert into barber.inventory_consumption_snapshots(id,tenant_id,branch_id,service_order_id,product_id,stock_movement_id,quantity,unit_cost,total_cost,status) select @id,@tenant,@branch,@order,@product,@movement,@quantity,cost_price,cost_price*@quantity,'Consumed' from changed where exists(select 1 from moved)");foreach(var x in new[]{("quantity",(object?)quantity),("product",product),("order",order),("movement",movement),("id",consumption)})ServiceExecutionStore.Add(cmd,x.Item1,x.Item2);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Produto inexistente ou estoque insuficiente.");await tx.CommitAsync(ct);return new(consumption,"Consumed",quantity);}
 public async Task<InventoryReversalResult> ReverseConsumptionAsync(ReverseConsumptionRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Motivo obrigatório.");await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(IsolationLevel.Serializable,ct);var movement=Guid.NewGuid();await using var cmd=store.Command(c,tx,@"with original as(update barber.inventory_consumption_snapshots set status='Reversed',updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Consumed' returning product_id,service_order_id,quantity), changed as(update barber.products p set current_stock=p.current_stock+o.quantity,updated_at=now() from original o where p.id=o.product_id returning p.id,p.current_stock,o.service_order_id,o.quantity) insert into barber.stock_movements(id,tenant_id,branch_id,product_id,service_order_id,type,quantity,balance_after,reason,created_by) select @movement,@tenant,@branch,id,service_order_id,'ConsumptionReversal',quantity,current_stock,@reason,@user from changed");ServiceExecutionStore.Add(cmd,"id",r.ConsumptionId);ServiceExecutionStore.Add(cmd,"movement",movement);ServiceExecutionStore.Add(cmd,"reason",r.Reason);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Consumo não reversível.");await tx.CommitAsync(ct);return new(r.ConsumptionId,movement,"Reversed");}
}

public sealed class CommissionAccrualService(ServiceExecutionStore store,CatalogCommissionService catalog)
{
 public async Task<CommissionPreviewResult> PreviewCommissionsAsync(CommissionPreviewRequest r,CancellationToken ct)=>new(r.ServiceOrderId,await store.Query("select source_type,source_id,final_price base_amount from barber.service_order_pricing_snapshots where service_order_id=@order and tenant_id=@tenant and branch_id=@branch",c=>ServiceExecutionStore.Add(c,"order",r.ServiceOrderId),ct),false);
 public Task<CommissionAccrualResult> AccrueProfessionalCommissionAsync(AccrueProfessionalCommissionRequest r,CancellationToken ct)=>Accrue("Professional",r.ProfessionalId,r.ServiceOrderId,r.SourceId,r.SourceType,r.BaseAmount,r.Percent,ct);
 public Task<CommissionAccrualResult> AccruePartnerCommissionAsync(AccruePartnerCommissionRequest r,CancellationToken ct)=>Accrue("Partner",r.PartnerId,r.ServiceOrderId,r.SourceId,r.SourceType,r.BaseAmount,r.Percent,ct);
 private async Task<CommissionAccrualResult> Accrue(string ownerType,Guid owner,Guid order,Guid source,string sourceType,decimal basis,decimal percent,CancellationToken ct){var result=catalog.Calculate(new(owner,source,sourceType,"Percentage",basis,null,percent,"ServiceCompleted"));if(!result.Eligible)throw new InvalidOperationException("Evento ainda não elegível para comissão.");var id=Guid.NewGuid();var key=$"{ownerType}:{owner}:{sourceType}:{source}";await using var c=await store.Open(ct);await using var cmd=store.Command(c,null,@"insert into barber.commission_accrual_events(id,tenant_id,branch_id,owner_type,owner_id,source_type,source_id,base_amount,commission_amount,status,idempotency_key,metadata_json) select @id,@tenant,@branch,@owner_type,@owner,@source_type,@source,@base,@amount,'Payable',@key,jsonb_build_object('serviceOrderId',@order) where exists(select 1 from barber.service_orders where id=@order and tenant_id=@tenant and branch_id=@branch and status in ('ServiceCompleted','Paid','Closed')) on conflict(tenant_id,idempotency_key) do nothing");foreach(var x in new[]{("id",(object?)id),("owner_type",ownerType),("owner",owner),("source_type",sourceType),("source",source),("base",basis),("amount",result.CommissionAmount),("key",key),("order",order)})ServiceExecutionStore.Add(cmd,x.Item1,x.Item2);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Comissão duplicada ou evento de origem não concluído.");return new(id,"Payable",result.CommissionAmount);}
 public async Task<CommissionReversalResult> ReverseCommissionAsync(ReverseCommissionRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Motivo obrigatório.");await using var c=await store.Open(ct);await using var cmd=store.Command(c,null,"update barber.commission_accrual_events set status='Reversed',reversed_at=now(),metadata_json=metadata_json||jsonb_build_object('reversalReason',@reason) where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Pending','Payable') returning id");ServiceExecutionStore.Add(cmd,"reason",r.Reason);ServiceExecutionStore.Add(cmd,"id",r.CommissionId);if(await cmd.ExecuteScalarAsync(ct) is null)throw new InvalidOperationException("Comissão paga não pode ser editada; use o processo contábil de estorno.");return new(r.CommissionId,"Reversed");}
}

public sealed class CashSessionService(ServiceExecutionStore store)
{
 public async Task<CashSessionResult> OpenCashSessionAsync(OpenCashSessionRequest r,CancellationToken ct){if(r.OpeningAmount<0)throw new ArgumentException("Valor inicial inválido.");var id=Guid.NewGuid();await using var c=await store.Open(ct);await using var tx=await c.BeginTransactionAsync(IsolationLevel.Serializable,ct);await using var cmd=store.Command(c,tx,@"insert into barber.cash_sessions(id,tenant_id,branch_id,operator_user_id,status,opening_amount,expected_amount) select @id,@tenant,@branch,@user,'Open',@amount,@amount where not exists(select 1 from barber.cash_sessions where tenant_id=@tenant and branch_id=@branch and operator_user_id=@user and status='Open')");ServiceExecutionStore.Add(cmd,"id",id);ServiceExecutionStore.Add(cmd,"amount",r.OpeningAmount);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Operador já possui caixa aberto nesta filial.");await tx.CommitAsync(ct);return new(id,"Open",r.OpeningAmount,null);}
 public async Task<CashSessionSummaryResult> GetCashSessionSummaryAsync(CashSessionSummaryRequest r,CancellationToken ct){var rows=await store.Query("select s.opening_amount,coalesce(sum(m.amount) filter(where m.movement_type<>'Opening'),0) movements,s.opening_amount+coalesce(sum(m.amount) filter(where m.movement_type<>'Opening'),0) expected from barber.cash_sessions s left join barber.cash_session_movements m on m.cash_session_id=s.id where s.id=@id and s.tenant_id=@tenant and s.branch_id=@branch group by s.id",c=>ServiceExecutionStore.Add(c,"id",r.CashSessionId),ct);if(rows.Count!=1)throw new InvalidOperationException("Caixa inexistente.");return new(r.CashSessionId,(decimal)rows[0]["opening_amount"]!,(decimal)rows[0]["movements"]!,(decimal)rows[0]["expected"]!);}
 public async Task<CashSessionResult> CloseCashSessionAsync(CloseCashSessionRequest r,CancellationToken ct){var s=await GetCashSessionSummaryAsync(new(r.CashSessionId),ct);var difference=r.DeclaredAmount-s.Expected;if(difference!=0m&&string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Divergência exige justificativa.");await using var c=await store.Open(ct);await using var cmd=store.Command(c,null,"update barber.cash_sessions set status='Closed',closed_at=now(),expected_amount=@expected,declared_amount=@declared,difference_amount=@difference,close_reason=@reason,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Open'");foreach(var x in new[]{("expected",(object?)s.Expected),("declared",r.DeclaredAmount),("difference",difference),("reason",r.Reason),("id",r.CashSessionId)})ServiceExecutionStore.Add(cmd,x.Item1,x.Item2);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Caixa não está aberto.");return new(r.CashSessionId,"Closed",s.Expected,difference);}
 public async Task<CashSessionAuditResult> RegisterCashAdjustmentAsync(CashAdjustmentRequest r,CancellationToken ct){if(r.Amount==0||string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Ajuste exige valor e motivo.");var id=Guid.NewGuid();await using var c=await store.Open(ct);await using var cmd=store.Command(c,null,"insert into barber.cash_session_movements(id,tenant_id,branch_id,cash_session_id,movement_type,source_type,amount,description,created_by) select @id,@tenant,@branch,id,'Adjustment','Manual',@amount,@reason,@user from barber.cash_sessions where id=@session and tenant_id=@tenant and branch_id=@branch and status='Open'");ServiceExecutionStore.Add(cmd,"id",id);ServiceExecutionStore.Add(cmd,"session",r.CashSessionId);ServiceExecutionStore.Add(cmd,"amount",r.Amount);ServiceExecutionStore.Add(cmd,"reason",r.Reason);if(await cmd.ExecuteNonQueryAsync(ct)!=1)throw new InvalidOperationException("Caixa fechado não recebe ajuste.");return new(id,r.Amount);}
}
