[CmdletBinding(SupportsShouldProcess)] param([string]$BaseUrl = "http://localhost:5080")
$ErrorActionPreference = "Stop"; Set-StrictMode -Version Latest
$Names = "ADMIN_EMAIL","ADMIN_PASSWORD","CASHIER_EMAIL","CASHIER_PASSWORD","PROFESSIONAL_EMAIL","PROFESSIONAL_PASSWORD","CLIENT_EMAIL","CLIENT_PASSWORD","TENANT_ID","BRANCH_ID","KIOSK_DEVICE_CODE"
foreach ($Name in $Names) { if (-not [Environment]::GetEnvironmentVariable("READINESS_$Name")) { throw "READINESS_$Name is required" } }
if ($WhatIfPreference) { Write-Host "Validated authenticated smoke configuration (no credentials printed)."; return }
$Slug = if ($env:READINESS_TENANT_SLUG) {$env:READINESS_TENANT_SLUG} else {"production-readiness"}
function Request([string]$Method,[string]$Path,[string]$Token="",[object]$Body=$null,[int[]]$Expected=@(200)) {
  $Headers=@{}; if($Token){$Headers.Authorization="Bearer $Token"}; $Params=@{Uri="$BaseUrl$Path";Method=$Method;Headers=$Headers}
  if($null-ne $Body){$Params.ContentType="application/json";$Params.Body=($Body|ConvertTo-Json -Compress)}
  try {$R=Invoke-WebRequest @Params} catch [System.Net.WebException] {$R=$_.Exception.Response; if($null-eq $R){throw}}; if($Expected-notcontains [int]$R.StatusCode){throw "$Method $Path returned $($R.StatusCode)"}; if($R.Content){$R.Content|ConvertFrom-Json}else{$null}
}
function Login($Email,$Password){(Request POST /api/auth/login "" @{email=$Email;password=$Password;tenantSlug=$Slug}).data.accessToken}
$Bad=Request POST /api/auth/login "" @{email="invalid@readiness.local";password="invalid-password";tenantSlug=$Slug} @(400,401); if(-not $Bad.traceId){throw "Invalid login has no traceId"}
$Admin=Login $env:READINESS_ADMIN_EMAIL $env:READINESS_ADMIN_PASSWORD; "EVIDENCE:AUTH_SMOKE_LOGIN:PASS"
$Dashboard=Request GET /api/dashboard/summary $Admin; if(($Dashboard|ConvertTo-Json -Depth 20)-notmatch $env:READINESS_TENANT_ID){throw "Dashboard tenant mismatch"}; "EVIDENCE:AUTH_SMOKE_DASHBOARD:PASS"
$Team=Request GET /api/team/dashboard $Admin; if(($Team|ConvertTo-Json -Depth 20)-notmatch 'active_professionals'){throw "Team dashboard contract failed"}; $Professionals=Request GET /api/professionals $Admin; if(($Professionals|ConvertTo-Json -Depth 20)-notmatch 'Readiness'){throw "Professionals contract failed"}; "EVIDENCE:AUTH_SMOKE_TEAM:PASS"
$Finance=Request GET /api/finance/dashboard $Admin; if(($Finance|ConvertTo-Json -Depth 20)-notmatch 'revenue_month'){throw "Finance dashboard contract failed"}; $Categories=Request GET /api/finance/categories $Admin; $Suppliers=Request GET /api/suppliers $Admin; $Payables=Request GET /api/finance/payables $Admin; $Receivables=Request GET /api/finance/receivables $Admin; if((@($Categories,$Suppliers,$Payables,$Receivables)|ConvertTo-Json -Depth 20)-notmatch 'Readiness'){throw "Finance readiness contracts failed"}; "EVIDENCE:AUTH_SMOKE_FINANCE:PASS"
$Client=Login $env:READINESS_CLIENT_EMAIL $env:READINESS_CLIENT_PASSWORD; $C=Request GET /api/mobile/summary $Client; $CJ=$C|ConvertTo-Json -Depth 20; if($CJ-notmatch 'Client' -or $CJ-match 'commissions|blocks'){throw "Client ownership contract failed"}; "EVIDENCE:AUTH_SMOKE_MOBILE_CLIENT:PASS"
$Professional=Login $env:READINESS_PROFESSIONAL_EMAIL $env:READINESS_PROFESSIONAL_PASSWORD; $P=Request GET /api/mobile/summary $Professional; $PJ=$P|ConvertTo-Json -Depth 20; if($PJ-notmatch 'Professional' -or $PJ-notmatch 'appointments' -or $PJ-notmatch 'commissions' -or $PJ-notmatch 'goals' -or $PJ-notmatch 'blocks'){throw "Professional ownership contract failed"}; "EVIDENCE:AUTH_SMOKE_MOBILE_PROFESSIONAL:PASS"; "EVIDENCE:AUTH_SMOKE_PROFESSIONAL_MOBILE:PASS"
$Before=Request GET /api/notifications $Admin; if(($Before|ConvertTo-Json -Depth 20)-notmatch 'Readiness notification'){throw "Seed notification missing"}; Request POST /api/notifications/read-all $Admin $null @(200,204)|Out-Null; $After=Request GET /api/notifications $Admin; if(($After|ConvertTo-Json -Depth 20)-match '"status":\s*"Unread"'){throw "Read-all was not persisted"}; "EVIDENCE:AUTH_SMOKE_NOTIFICATIONS:PASS"
$Stock=Request GET /api/stock $Admin; if(($Stock|ConvertTo-Json -Depth 20)-notmatch 'READINESS-PRODUCT'){throw "Readiness stock missing"}; "EVIDENCE:AUTH_SMOKE_STOCK:PASS"
$Cashier=Login $env:READINESS_CASHIER_EMAIL $env:READINESS_CASHIER_PASSWORD; $Cash=Request GET /api/cash-registers/current $Cashier; if(($Cash|ConvertTo-Json -Depth 20)-notmatch $env:READINESS_BRANCH_ID){throw "Cash branch mismatch"}; "EVIDENCE:AUTH_SMOKE_CASH_REGISTER:PASS"
$ClientId="70000000-0000-4000-8000-000000000013"; $ProfessionalId="70000000-0000-4000-8000-000000000012"; $ServiceId="70000000-0000-4000-8000-000000000030"; $ProductId="70000000-0000-4000-8000-000000000040"
$InitialProduct=$Stock.data|Where-Object {$_.id-eq $ProductId}|Select-Object -First 1; if($null-eq $InitialProduct){throw "Readiness product was not returned by /api/stock"}; $InitialStock=[decimal]$InitialProduct.currentStock
$Order=Request POST /api/service-orders/open $Cashier @{clientId=$ClientId;notes="Production readiness authenticated smoke"} @(201); $OrderId=$Order.id
Request POST "/api/service-orders/$OrderId/items/services" $Cashier @{serviceId=$ServiceId;professionalId=$ProfessionalId;quantity=1}|Out-Null
$WithProduct=Request POST "/api/service-orders/$OrderId/items/products" $Cashier @{productId=$ProductId;quantity=1}; if([decimal]$WithProduct.total-ne 65){throw "POS total is not 65.00"}; "EVIDENCE:AUTH_SMOKE_SERVICE_ORDER:PASS"
$Payment=Request POST "/api/service-orders/$OrderId/payments" $Cashier @{idempotencyKey="readiness-$OrderId";splits=@(@{method="Cash";amount=65;receivedAmount=65});note="Production readiness"}; if($Payment.orderStatus-ne "Paid"){throw "Order was not paid"}; $PaymentId=$Payment.id
$Paid=Request GET "/api/service-orders/$OrderId" $Cashier; if($Paid.status-ne "Paid" -or [decimal]$Paid.balance-ne 0){throw "Paid service order state was not persisted"}; "EVIDENCE:AUTH_SMOKE_PAYMENT:PASS"
$StockAfter=Request GET /api/stock $Admin; $FinalProduct=$StockAfter.data|Where-Object {$_.id-eq $ProductId}|Select-Object -First 1; if($null-eq $FinalProduct -or [decimal]$FinalProduct.currentStock-ne ($InitialStock-1)){throw "Product stock did not decrease exactly once"}
$StockMovements=Request GET /api/stock/movements $Admin; if(($StockMovements|ConvertTo-Json -Depth 20)-notmatch $OrderId){throw "Stock movement missing"}; "EVIDENCE:AUTH_SMOKE_STOCK_MOVEMENT:PASS"
$CashAfter=Request GET /api/cash-registers/current $Cashier; $CashJson=$CashAfter|ConvertTo-Json -Depth 20; if($CashJson-notmatch 'Sale' -or $CashJson-notmatch $PaymentId){throw "Cash sale movement missing"}; "EVIDENCE:AUTH_SMOKE_CASH_MOVEMENT:PASS"
$Finance=Request GET /api/finance $Admin; $FinanceJson=$Finance|ConvertTo-Json -Depth 20; if($FinanceJson-notmatch $PaymentId -or $FinanceJson-notmatch $OrderId){throw "Financial entry missing"}; "EVIDENCE:AUTH_SMOKE_FINANCIAL_ENTRY:PASS"
$Commissions=Request GET /api/commissions $Admin; $CommissionJson=$Commissions|ConvertTo-Json -Depth 20; if($CommissionJson-notmatch $PaymentId -or $CommissionJson-notmatch $ProfessionalId){throw "Commission missing"}; "EVIDENCE:AUTH_SMOKE_COMMISSION:PASS"
$Audit=Request GET /api/audit $Admin; $AuditJson=$Audit|ConvertTo-Json -Depth 20; if($AuditJson-notmatch $PaymentId -or $AuditJson-notmatch 'Payment.Register'){throw "Payment audit missing"}; "EVIDENCE:AUTH_SMOKE_POS:PASS"
Request GET /api/kiosk/services "" $null @(400)|Out-Null; $Kiosk=Request GET "/api/kiosk/services?deviceCode=$($env:READINESS_KIOSK_DEVICE_CODE)"; $KJ=$Kiosk|ConvertTo-Json -Depth 20; if($KJ-notmatch 'Readiness Haircut' -or $KJ-match 'KIOSK-001'){throw "Kiosk device contract failed"}; "EVIDENCE:AUTH_SMOKE_KIOSK:PASS"
