using System.Data.Common;
using System.Text;
using System.Text.Json;
using BarberSync.Api.Security;
using BarberSync.Api.Services.Catalog;
using BarberSync.Api.Services.Team;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BarberSync.Api.Controllers;

[ApiController, Authorize]
public abstract class CatalogControllerBase(TeamDataService data) : ControllerBase
{
    protected TeamDataService Data => data;
    protected object Envelope(object? value) => new { success=true, data=value, traceId=HttpContext.TraceIdentifier };
    protected IActionResult Invalid(string detail) => Problem(statusCode:422,title:"Dados de catálogo inválidos",detail:detail,extensions:new Dictionary<string,object?>{{"traceId",HttpContext.TraceIdentifier}});
    protected static void Add(DbCommand command,string name,object? value)=>TeamDataService.Add(command,name,value);
}

[Route("api/catalog")]
public sealed class CatalogController(TeamDataService data) : CatalogControllerBase(data)
{
    [HttpGet("dashboard"),RequirePermission("Catalog.Read")]
    public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(Envelope((await Data.QueryAsync(@"select
      (select count(*) from barber.catalog_service_profiles where tenant_id=@tenant and branch_id=@branch and deleted_at is null) services,
      (select count(*) from barber.catalog_product_profiles where tenant_id=@tenant and branch_id=@branch and deleted_at is null) products,
      (select count(*) from barber.catalog_combo_definitions where tenant_id=@tenant and branch_id=@branch and status='Active') active_combos,
      (select count(*) from barber.catalog_package_definitions where tenant_id=@tenant and branch_id=@branch and status='Active') active_packages,
      (select count(*) from barber.catalog_service_profiles where tenant_id=@tenant and branch_id=@branch and estimated_margin_percent<20 and deleted_at is null)+(select count(*) from barber.catalog_product_profiles where tenant_id=@tenant and branch_id=@branch and margin_percent<20 and deleted_at is null) margin_alerts,
      (select coalesce(sum(commission_amount),0) from barber.catalog_commission_events where tenant_id=@tenant and branch_id=@branch and status='Payable') commission_payable",null,ct)).Single()));
    [HttpGet("filter-options"),RequirePermission("Catalog.Read")]
    public async Task<IActionResult> Options(CancellationToken ct)=>Ok(Envelope(new { services=await Data.QueryAsync("select id,name from barber.services where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null order by name",null,ct), products=await Data.QueryAsync("select id,name from barber.products where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null order by name",null,ct), professionals=await Data.QueryAsync("select id,name from barber.professionals where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null order by name",null,ct), partners=await Data.QueryAsync("select id,name from barber.partner_profiles where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null order by name",null,ct), categories=await Data.QueryAsync("select id,name from barber.product_categories where tenant_id=@tenant and branch_id=@branch order by name",null,ct), suppliers=await Data.QueryAsync("select id,name from barber.suppliers where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null order by name",null,ct) }));
}

[Route("api/catalog/services")]
public sealed class CatalogServicesController(TeamDataService data, ICurrentUserContext current):CatalogControllerBase(data)
{
 [HttpGet,RequirePermission("Catalog.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select p.*,s.name,s.description from barber.catalog_service_profiles p join barber.services s on s.id=p.service_id where p.tenant_id=@tenant and p.branch_id=@branch and p.deleted_at is null order by s.name",null,ct)));
 [HttpPost("profile"),RequirePermission("Catalog.Services.Manage")] public Task<IActionResult> Create(CatalogServiceProfileRequest r,CancellationToken ct)=>Save(null,r,ct);
 [HttpPut("{id:guid}/profile"),RequirePermission("Catalog.Services.Manage")] public Task<IActionResult> Update(Guid id,CatalogServiceProfileRequest r,CancellationToken ct)=>Save(id,r,ct);
 async Task<IActionResult> Save(Guid? id,CatalogServiceProfileRequest r,CancellationToken ct){if(r.ServiceId==Guid.Empty||r.BasePrice<0||r.EstimatedCost<0||r.DefaultDurationMinutes<=0)return Invalid("Selecione um serviço e informe preço, custo e duração válidos.");var entity=id??Guid.NewGuid();var sql=id is null?"insert into barber.catalog_service_profiles(id,tenant_id,branch_id,service_id,category_id,base_price,estimated_cost,estimated_margin_percent,default_duration_minutes,public_visible,kiosk_visible,marketplace_visible,requires_consent,requires_anamnesis,status,created_by) select @id,@tenant,@branch,id,@category,@price,@cost,case when @price=0 then 0 else (@price-@cost)/@price*100 end,@duration,@public,@kiosk,@marketplace,@consent,@anamnesis,@status,@user from barber.services where id=@service and tenant_id=@tenant and branch_id=@branch and deleted_at is null":"update barber.catalog_service_profiles set category_id=@category,base_price=@price,estimated_cost=@cost,estimated_margin_percent=case when @price=0 then 0 else (@price-@cost)/@price*100 end,default_duration_minutes=@duration,public_visible=@public,kiosk_visible=@kiosk,marketplace_visible=@marketplace,requires_consent=@consent,requires_anamnesis=@anamnesis,status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null";await Data.WriteAsync(sql,id is null?"CatalogServiceCreated":"CatalogServiceUpdated","catalog_service_profiles",entity,r.Reason,c=>{Add(c,"service",r.ServiceId);Add(c,"category",r.CategoryId);Add(c,"price",r.BasePrice);Add(c,"cost",r.EstimatedCost);Add(c,"duration",r.DefaultDurationMinutes);Add(c,"public",r.PublicVisible);Add(c,"kiosk",r.KioskVisible);Add(c,"marketplace",r.MarketplaceVisible);Add(c,"consent",r.RequiresConsent);Add(c,"anamnesis",r.RequiresAnamnesis);Add(c,"status",r.Status);Add(c,"user",current.UserId);},ct);return id is null?Created($"/api/catalog/services/{entity}/profile",Envelope(new{id=entity})):Ok(Envelope(new{id=entity}));}
}

[Route("api/catalog/products")]
public sealed class CatalogProductsController(TeamDataService data,ICurrentUserContext current):CatalogControllerBase(data)
{
 [HttpGet,RequirePermission("Catalog.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select c.*,p.name,p.current_stock stock from barber.catalog_product_profiles c join barber.products p on p.id=c.product_id where c.tenant_id=@tenant and c.branch_id=@branch and c.deleted_at is null order by p.name",null,ct)));
 [HttpPost("profile"),RequirePermission("Catalog.Products.Manage")] public Task<IActionResult> Create(CatalogProductProfileRequest r,CancellationToken ct)=>Save(null,r,ct);
 [HttpPut("{id:guid}/profile"),RequirePermission("Catalog.Products.Manage")] public Task<IActionResult> Update(Guid id,CatalogProductProfileRequest r,CancellationToken ct)=>Save(id,r,ct);
 async Task<IActionResult> Save(Guid? id,CatalogProductProfileRequest r,CancellationToken ct){if(r.ProductId==Guid.Empty||r.CostPrice<0||r.SalePrice<0)return Invalid("Selecione um produto e informe custo e preço válidos.");var entity=id??Guid.NewGuid();var sql=id is null?"insert into barber.catalog_product_profiles(id,tenant_id,branch_id,product_id,category_id,supplier_id,cost_price,sale_price,margin_percent,public_visible,marketplace_visible,stock_control_required,status,created_by) select @id,@tenant,@branch,id,@category,@supplier,@cost,@price,case when @price=0 then 0 else (@price-@cost)/@price*100 end,@public,@marketplace,@stock,@status,@user from barber.products where id=@product and tenant_id=@tenant and branch_id=@branch and deleted_at is null":"update barber.catalog_product_profiles set category_id=@category,supplier_id=@supplier,cost_price=@cost,sale_price=@price,margin_percent=case when @price=0 then 0 else (@price-@cost)/@price*100 end,public_visible=@public,marketplace_visible=@marketplace,stock_control_required=@stock,status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null";await Data.WriteAsync(sql,id is null?"CatalogProductCreated":"CatalogProductUpdated","catalog_product_profiles",entity,r.Reason,c=>{Add(c,"product",r.ProductId);Add(c,"category",r.CategoryId);Add(c,"supplier",r.SupplierId);Add(c,"cost",r.CostPrice);Add(c,"price",r.SalePrice);Add(c,"public",r.PublicVisible);Add(c,"marketplace",r.MarketplaceVisible);Add(c,"stock",r.StockControlRequired);Add(c,"status",r.Status);Add(c,"user",current.UserId);},ct);return id is null?Created($"/api/catalog/products/{entity}/profile",Envelope(new{id=entity})):Ok(Envelope(new{id=entity}));}
}

[Route("api/catalog/combos")]
public sealed class CatalogCombosController(TeamDataService data,ICurrentUserContext current):CatalogControllerBase(data)
{
 [HttpGet,RequirePermission("Catalog.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select c.*,coalesce(jsonb_agg(jsonb_build_object('id',i.id,'itemType',i.item_type,'quantity',i.quantity,'unitPrice',i.unit_price_snapshot)) filter(where i.id is not null),'[]') items from barber.catalog_combo_definitions c left join barber.catalog_combo_items i on i.combo_id=c.id where c.tenant_id=@tenant and c.branch_id=@branch and c.deleted_at is null group by c.id order by c.updated_at desc",null,ct)));
 [HttpPost,RequirePermission("Catalog.Combos.Manage")] public Task<IActionResult> Create(CatalogBundleRequest r,CancellationToken ct)=>Save(null,r,ct);
 [HttpPut("{id:guid}"),RequirePermission("Catalog.Combos.Manage")] public Task<IActionResult> Update(Guid id,CatalogBundleRequest r,CancellationToken ct)=>Save(id,r,ct);
 async Task<IActionResult> Save(Guid? id,CatalogBundleRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||r.Price<0||r.Items.Count==0||r.Items.Any(x=>x.Quantity<=0||x.UnitPrice<0))return Invalid("O combo exige nome, preço e ao menos um item válido.");var baseTotal=r.Items.Sum(x=>x.Quantity*x.UnitPrice);if(r.Price>baseTotal)return Invalid("O preço do combo não pode exceder o total sem uma regra de acréscimo.");var entity=id??Guid.NewGuid();await Data.WriteAsync(id is null?"insert into barber.catalog_combo_definitions(id,tenant_id,branch_id,name,description,base_total,combo_price,margin_percent,status,public_visible,kiosk_visible,marketplace_visible,created_by) values(@id,@tenant,@branch,@name,@description,@base,@price,case when @price=0 then 0 else (@price-@cost)/@price*100 end,'Draft',@public,@kiosk,@marketplace,@user)":"update barber.catalog_combo_definitions set name=@name,description=@description,base_total=@base,combo_price=@price,margin_percent=case when @price=0 then 0 else (@price-@cost)/@price*100 end,public_visible=@public,kiosk_visible=@kiosk,marketplace_visible=@marketplace,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status<>'Archived'","CatalogComboSaved","catalog_combo_definitions",entity,r.Reason,c=>{Add(c,"name",r.Name.Trim());Add(c,"description",r.Description);Add(c,"base",baseTotal);Add(c,"price",r.Price);Add(c,"cost",r.Items.Sum(x=>x.Quantity*x.Cost));Add(c,"public",r.PublicVisible);Add(c,"kiosk",r.KioskVisible);Add(c,"marketplace",r.MarketplaceVisible);Add(c,"user",current.UserId);},ct);await Data.WriteAsync("delete from barber.catalog_combo_items where combo_id=@combo and tenant_id=@tenant and branch_id=@branch; insert into barber.catalog_combo_items(id,tenant_id,branch_id,combo_id,item_type,service_id,product_id,quantity,unit_price_snapshot,cost_snapshot,sort_order) select gen_random_uuid(),@tenant,@branch,@combo,x.item_type,x.service_id,x.product_id,x.quantity,x.unit_price,x.cost,x.sort_order from jsonb_to_recordset(@items::jsonb) x(item_type varchar,service_id uuid,product_id uuid,quantity numeric,unit_price numeric,cost numeric,sort_order int)","CatalogComboItemsSaved","catalog_combo_definitions",entity,r.Reason,c=>{Add(c,"combo",entity);Add(c,"items",JsonSerializer.Serialize(r.Items.Select((x,i)=>new{item_type=x.ItemType,service_id=x.ServiceId,product_id=x.ProductId,quantity=x.Quantity,unit_price=x.UnitPrice,cost=x.Cost,sort_order=i})));},ct);return Ok(Envelope(new{id=entity,status="Draft",baseTotal}));}
 [HttpPost("{id:guid}/activate"),RequirePermission("Catalog.Combos.Manage")] public Task<IActionResult> Activate(Guid id,CatalogReasonRequest r,CancellationToken ct)=>State(id,"Active",r,ct);
 [HttpPost("{id:guid}/archive"),RequirePermission("Catalog.Combos.Manage")] public Task<IActionResult> Archive(Guid id,CatalogReasonRequest r,CancellationToken ct)=>State(id,"Archived",r,ct);
 async Task<IActionResult> State(Guid id,string state,CatalogReasonRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return Invalid("Informe o motivo da alteração.");await Data.WriteAsync("update barber.catalog_combo_definitions c set status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null and (@status='Archived' or exists(select 1 from barber.catalog_combo_items i where i.combo_id=c.id))","CatalogComboStatusChanged","catalog_combo_definitions",id,r.Reason,c=>Add(c,"status",state),ct);return Ok(Envelope(new{id,status=state}));}
}

[Route("api/catalog/packages")]
public sealed class CatalogPackagesController(TeamDataService data,ICurrentUserContext current):CatalogControllerBase(data)
{
 [HttpGet,RequirePermission("Catalog.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.catalog_package_definitions where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by updated_at desc",null,ct)));
 [HttpPost,RequirePermission("Catalog.Packages.Manage")] public Task<IActionResult> Create(CatalogPackageRequest r,CancellationToken ct)=>Save(null,r,ct);
 [HttpPut("{id:guid}"),RequirePermission("Catalog.Packages.Manage")] public Task<IActionResult> Update(Guid id,CatalogPackageRequest r,CancellationToken ct)=>Save(id,r,ct);
 async Task<IActionResult> Save(Guid? id,CatalogPackageRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||r.Price<0||r.ValidityDays<=0||r.Items.Count==0||r.Items.Any(x=>x.Quantity<=0))return Invalid("Pacote exige nome, validade, preço e itens com saldo positivo.");var entity=id??Guid.NewGuid();await Data.WriteAsync(id is null?"insert into barber.catalog_package_definitions(id,tenant_id,branch_id,name,description,package_type,price,validity_days,status,public_visible,kiosk_visible,marketplace_visible,created_by) values(@id,@tenant,@branch,@name,@description,@type,@price,@validity,'Draft',@public,@kiosk,@marketplace,@user)":"update barber.catalog_package_definitions set name=@name,description=@description,package_type=@type,price=@price,validity_days=@validity,public_visible=@public,kiosk_visible=@kiosk,marketplace_visible=@marketplace,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status<>'Archived'","CatalogPackageSaved","catalog_package_definitions",entity,r.Reason,c=>{Add(c,"name",r.Name.Trim());Add(c,"description",r.Description);Add(c,"type",r.PackageType);Add(c,"price",r.Price);Add(c,"validity",r.ValidityDays);Add(c,"public",r.PublicVisible);Add(c,"kiosk",r.KioskVisible);Add(c,"marketplace",r.MarketplaceVisible);Add(c,"user",current.UserId);},ct);await Data.WriteAsync("delete from barber.catalog_package_items where package_id=@package and tenant_id=@tenant and branch_id=@branch; insert into barber.catalog_package_items(id,tenant_id,branch_id,package_id,item_type,service_id,product_id,quantity,unit_price_snapshot) select gen_random_uuid(),@tenant,@branch,@package,x.item_type,x.service_id,x.product_id,x.quantity,x.unit_price from jsonb_to_recordset(@items::jsonb) x(item_type varchar,service_id uuid,product_id uuid,quantity numeric,unit_price numeric)","CatalogPackageItemsSaved","catalog_package_definitions",entity,r.Reason,c=>{Add(c,"package",entity);Add(c,"items",JsonSerializer.Serialize(r.Items.Select(x=>new{item_type=x.ItemType,service_id=x.ServiceId,product_id=x.ProductId,quantity=x.Quantity,unit_price=x.UnitPrice})));},ct);return Ok(Envelope(new{id=entity,status="Draft"}));}
 [HttpPost("{id:guid}/activate"),RequirePermission("Catalog.Packages.Manage")] public Task<IActionResult> Activate(Guid id,CatalogReasonRequest r,CancellationToken ct)=>State(id,"Active",r,ct); [HttpPost("{id:guid}/archive"),RequirePermission("Catalog.Packages.Manage")] public Task<IActionResult> Archive(Guid id,CatalogReasonRequest r,CancellationToken ct)=>State(id,"Archived",r,ct);
 async Task<IActionResult> State(Guid id,string status,CatalogReasonRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return Invalid("Informe o motivo da alteração.");await Data.WriteAsync("update barber.catalog_package_definitions set status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null","CatalogPackageStatusChanged","catalog_package_definitions",id,r.Reason,c=>Add(c,"status",status),ct);return Ok(Envelope(new{id,status}));}
}

[Route("api/catalog/pricing-rules")]
public sealed class CatalogPricingRulesController(TeamDataService data,ICurrentUserContext current):CatalogControllerBase(data)
{
 [HttpGet,RequirePermission("Catalog.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.catalog_price_rules where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by priority desc,created_at desc",null,ct)));
 [HttpPost,RequirePermission("Catalog.Pricing.Manage")] public Task<IActionResult> Create(CatalogPricingRuleRequest r,CancellationToken ct)=>Save(null,r,ct); [HttpPut("{id:guid}"),RequirePermission("Catalog.Pricing.Manage")] public Task<IActionResult> Update(Guid id,CatalogPricingRuleRequest r,CancellationToken ct)=>Save(id,r,ct);
 async Task<IActionResult> Save(Guid? id,CatalogPricingRuleRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||(r.EndsAt.HasValue&&r.StartsAt.HasValue&&r.EndsAt.Value<=r.StartsAt.Value)||r.Priority<0)return Invalid("Informe nome, prioridade e vigência coerente.");var entity=id??Guid.NewGuid();await Data.WriteAsync(id is null?"insert into barber.catalog_price_rules(id,tenant_id,branch_id,name,rule_type,priority,starts_at,ends_at,status,settings_json,created_by) values(@id,@tenant,@branch,@name,@type,@priority,@starts,@ends,'Draft',@settings::jsonb,@user)":"update barber.catalog_price_rules set name=@name,rule_type=@type,priority=@priority,starts_at=@starts,ends_at=@ends,settings_json=@settings::jsonb,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status<>'Archived'","CatalogPricingRuleSaved","catalog_price_rules",entity,r.Reason,c=>{Add(c,"name",r.Name.Trim());Add(c,"type",r.RuleType);Add(c,"priority",r.Priority);Add(c,"starts",r.StartsAt);Add(c,"ends",r.EndsAt);Add(c,"settings",r.Settings.GetRawText());Add(c,"user",current.UserId);},ct);return Ok(Envelope(new{id=entity,status="Draft"}));}
 [HttpPost("{id:guid}/activate"),RequirePermission("Catalog.Pricing.Manage")] public Task<IActionResult> Activate(Guid id,CatalogReasonRequest r,CancellationToken ct)=>State(id,"Active",r,ct); [HttpPost("{id:guid}/archive"),RequirePermission("Catalog.Pricing.Manage")] public Task<IActionResult> Archive(Guid id,CatalogReasonRequest r,CancellationToken ct)=>State(id,"Archived",r,ct); async Task<IActionResult> State(Guid id,string status,CatalogReasonRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return Invalid("Informe o motivo.");await Data.WriteAsync("update barber.catalog_price_rules set status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null","CatalogPricingRuleStatusChanged","catalog_price_rules",id,r.Reason,c=>Add(c,"status",status),ct);return Ok(Envelope(new{id,status}));}
}

[Route("api/catalog/margin-rules")]
public sealed class CatalogMarginsController(TeamDataService data,ICurrentUserContext current):CatalogControllerBase(data)
{
 [HttpGet,RequirePermission("Catalog.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.catalog_margin_rules where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by created_at desc",null,ct)));
 [HttpPost,RequirePermission("Catalog.Margins.Manage")] public Task<IActionResult> Create(CatalogMarginRuleRequest r,CancellationToken ct)=>Save(null,r,ct); [HttpPut("{id:guid}"),RequirePermission("Catalog.Margins.Manage")] public Task<IActionResult> Update(Guid id,CatalogMarginRuleRequest r,CancellationToken ct)=>Save(id,r,ct);
 async Task<IActionResult> Save(Guid? id,CatalogMarginRuleRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||r.MinimumMarginPercent is <0 or >100)return Invalid("Informe nome e margem entre 0 e 100%.");var entity=id??Guid.NewGuid();await Data.WriteAsync(id is null?"insert into barber.catalog_margin_rules(id,tenant_id,branch_id,name,target_type,target_id,minimum_margin_percent,action_type,status,created_by) values(@id,@tenant,@branch,@name,@type,@target,@margin,@action,'Active',@user)":"update barber.catalog_margin_rules set name=@name,target_type=@type,target_id=@target,minimum_margin_percent=@margin,action_type=@action,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null","CatalogMarginRuleSaved","catalog_margin_rules",entity,r.Reason,c=>{Add(c,"name",r.Name.Trim());Add(c,"type",r.TargetType);Add(c,"target",r.TargetId);Add(c,"margin",r.MinimumMarginPercent);Add(c,"action",r.ActionType);Add(c,"user",current.UserId);},ct);return Ok(Envelope(new{id=entity}));}
}

[Route("api/catalog/commission-rules")]
public sealed class CatalogCommissionsController(TeamDataService data,ICurrentUserContext current):CatalogControllerBase(data)
{
 [HttpGet,RequirePermission("Catalog.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.catalog_commission_rules where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by created_at desc",null,ct)));
 [HttpPost,RequirePermission("Catalog.Commissions.Manage")] public Task<IActionResult> Create(CatalogCommissionRuleRequest r,CancellationToken ct)=>Save(null,r,ct); [HttpPut("{id:guid}"),RequirePermission("Catalog.Commissions.Manage")] public Task<IActionResult> Update(Guid id,CatalogCommissionRuleRequest r,CancellationToken ct)=>Save(id,r,ct);
 async Task<IActionResult> Save(Guid? id,CatalogCommissionRuleRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||r.OwnerId==Guid.Empty||r.TargetId==Guid.Empty||(r.CommissionType=="Percentage"&&(r.Percent is null or <=0 or >100))||(r.CommissionType=="FixedAmount"&&(r.Amount is null or <=0)))return Invalid("Selecione responsável e item e informe comissão válida.");var entity=id??Guid.NewGuid();await Data.WriteAsync(id is null?"insert into barber.catalog_commission_rules(id,tenant_id,branch_id,name,commission_owner_type,owner_id,target_type,target_id,commission_type,amount,percent,trigger_type,status,created_by) values(@id,@tenant,@branch,@name,@owner_type,@owner,@target_type,@target,@type,@amount,@percent,@trigger,'Active',@user)":"update barber.catalog_commission_rules set name=@name,commission_owner_type=@owner_type,owner_id=@owner,target_type=@target_type,target_id=@target,commission_type=@type,amount=@amount,percent=@percent,trigger_type=@trigger,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null","CatalogCommissionRuleSaved","catalog_commission_rules",entity,r.Reason,c=>{Add(c,"name",r.Name.Trim());Add(c,"owner_type",r.OwnerType);Add(c,"owner",r.OwnerId);Add(c,"target_type",r.TargetType);Add(c,"target",r.TargetId);Add(c,"type",r.CommissionType);Add(c,"amount",r.Amount);Add(c,"percent",r.Percent);Add(c,"trigger",r.TriggerType);Add(c,"user",current.UserId);},ct);return Ok(Envelope(new{id=entity}));}
}

[Route("api/catalog")]
public sealed class CatalogSimulatorController(TeamDataService data,CatalogSimulationService simulator):CatalogControllerBase(data)
{
 [HttpPost("simulate-price"),RequirePermission("Catalog.Read")] public async Task<IActionResult> Price(CatalogPriceRequest r,CancellationToken ct){try{return Ok(Envelope(await simulator.Price(r,ct)));}catch(ArgumentException e){return Invalid(e.Message);}}
 [HttpPost("simulate-commission"),RequirePermission("Catalog.Read")] public async Task<IActionResult> Commission(CatalogCommissionRequest r,CancellationToken ct){try{return Ok(Envelope(await simulator.Commission(r,ct)));}catch(ArgumentException e){return Invalid(e.Message);}}
}
[Route("api/catalog/audit")]
public sealed class CatalogAuditController(TeamDataService data):CatalogControllerBase(data){[HttpGet,RequirePermission("Catalog.Read")]public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.catalog_audit_events where tenant_id=@tenant and branch_id=@branch order by created_at desc limit 500",null,ct)));}
[Route("api/catalog/reports")]
public sealed class CatalogReportsController(TeamDataService data):CatalogControllerBase(data){[HttpGet("export"),RequirePermission("Catalog.Reports.Export")]public async Task<IActionResult> Export(CancellationToken ct){var rows=await Data.QueryAsync("select item_type,item_id,old_price,new_price,reason,changed_at from barber.catalog_price_history where tenant_id=@tenant and branch_id=@branch order by changed_at desc",null,ct);var csv=new StringBuilder("tipo;item;preco_anterior;preco_novo;motivo;alterado_em\r\n");foreach(var row in rows)csv.AppendLine(string.Join(';',row.Values.Select(x=>$"\"{Convert.ToString(x)?.Replace("\"","\"\"")}\"")));return File(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv.ToString())).ToArray(),"text/csv",$"catalogo-{DateTime.UtcNow:yyyyMMdd}.csv");}}

[ApiController,Authorize,Route("api/mobile/catalog")]
public sealed class MobileCatalogController(TeamDataService data,CatalogSimulationService simulator):ControllerBase
{
 object Out(object value)=>new{success=true,data=value,sourceStatus="available",traceId=HttpContext.TraceIdentifier};
 [HttpGet("services")]public async Task<IActionResult> Services(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select p.service_id id,s.name,s.description,p.base_price price,p.default_duration_minutes duration_minutes from barber.catalog_service_profiles p join barber.services s on s.id=p.service_id where p.tenant_id=@tenant and p.branch_id=@branch and p.status='Active' and p.public_visible and s.status='Active' and p.deleted_at is null",null,ct)));
 [HttpGet("products")]public async Task<IActionResult> Products(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select p.product_id id,x.name,p.sale_price price from barber.catalog_product_profiles p join barber.products x on x.id=p.product_id where p.tenant_id=@tenant and p.branch_id=@branch and p.status='Active' and p.public_visible and x.status='Active' and p.deleted_at is null and (not p.stock_control_required or x.current_stock>0)",null,ct)));
 [HttpGet("combos")]public async Task<IActionResult> Combos(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select id,name,description,combo_price price from barber.catalog_combo_definitions where tenant_id=@tenant and branch_id=@branch and status='Active' and public_visible and deleted_at is null and not exists(select 1 from barber.catalog_combo_items i left join barber.catalog_service_profiles s on s.service_id=i.service_id left join barber.catalog_product_profiles p on p.product_id=i.product_id where i.combo_id=catalog_combo_definitions.id and coalesce(s.status,p.status,'Inactive')<>'Active')",null,ct)));
 [HttpPost("simulate-price")]public async Task<IActionResult> Price(CatalogPriceRequest r,CancellationToken ct)=>Ok(Out(await simulator.Price(r,ct)));
}

public sealed record CatalogServiceProfileRequest(Guid ServiceId,Guid? CategoryId,decimal BasePrice,decimal EstimatedCost,int DefaultDurationMinutes,bool PublicVisible,bool KioskVisible,bool MarketplaceVisible,bool RequiresConsent,bool RequiresAnamnesis,string Status,string? Reason);
public sealed record CatalogProductProfileRequest(Guid ProductId,Guid? CategoryId,Guid? SupplierId,decimal CostPrice,decimal SalePrice,bool PublicVisible,bool MarketplaceVisible,bool StockControlRequired,string Status,string? Reason);
public sealed record CatalogBundleItem(string ItemType,Guid? ServiceId,Guid? ProductId,decimal Quantity,decimal UnitPrice,decimal Cost);
public sealed record CatalogBundleRequest(string Name,string? Description,decimal Price,bool PublicVisible,bool KioskVisible,bool MarketplaceVisible,IReadOnlyList<CatalogBundleItem> Items,string? Reason);
public sealed record CatalogPackageRequest(string Name,string? Description,string PackageType,decimal Price,int ValidityDays,bool PublicVisible,bool KioskVisible,bool MarketplaceVisible,IReadOnlyList<CatalogBundleItem> Items,string? Reason);
public sealed record CatalogPricingRuleRequest(string Name,string RuleType,int Priority,DateTimeOffset? StartsAt,DateTimeOffset? EndsAt,JsonElement Settings,string? Reason);
public sealed record CatalogMarginRuleRequest(string Name,string TargetType,Guid? TargetId,decimal MinimumMarginPercent,string ActionType,string? Reason);
public sealed record CatalogCommissionRuleRequest(string Name,string OwnerType,Guid OwnerId,string TargetType,Guid TargetId,string CommissionType,decimal? Amount,decimal? Percent,string TriggerType,string? Reason);
public sealed record CatalogReasonRequest(string Reason);
