using System.Data.Common;
using System.Globalization;
using System.Text;
using BarberSync.Api.Security;
using BarberSync.Api.Services.Team;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BarberSync.Api.Controllers;

[ApiController, Authorize]
public abstract class FinanceControllerBase(TeamDataService data) : ControllerBase
{
    protected TeamDataService Data { get; } = data;
    protected object Envelope(object? value) => new { success = true, data = value };
    protected IActionResult Invalid(string field, string message) => BadRequest(new { message = "Revise os campos informados.", traceId = HttpContext.TraceIdentifier, errors = new Dictionary<string,string[]> { [field] = [message] } });
    protected static void Add(DbCommand c,string name,object? value)=>TeamDataService.Add(c,name,value);
}

[Route("api/finance")]
public sealed class FinanceController(TeamDataService data) : FinanceControllerBase(data)
{
    [HttpGet("dashboard"), RequirePermission("Finance.Read")]
    public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(Envelope((await Data.QueryAsync(@"select
      coalesce((select sum(amount) from barber.accounts_receivable where tenant_id=@tenant and branch_id=@branch and status='Received' and received_at::date=current_date),0) revenue_today,
      coalesce((select sum(amount) from barber.accounts_receivable where tenant_id=@tenant and branch_id=@branch and status='Received' and received_at>=date_trunc('month',now())),0) revenue_month,
      coalesce((select sum(amount) from barber.accounts_payable where tenant_id=@tenant and branch_id=@branch and status in ('Open','Overdue')),0) open_expenses,
      coalesce((select sum(amount) from barber.accounts_receivable where tenant_id=@tenant and branch_id=@branch and status in ('Open','Overdue')),0) open_receivables,
      coalesce((select sum(amount) from barber.accounts_receivable where tenant_id=@tenant and branch_id=@branch and status='Received'),0)-coalesce((select sum(amount) from barber.accounts_payable where tenant_id=@tenant and branch_id=@branch and status='Paid'),0) realized_balance",null,ct)).Single()));
    [HttpGet("cash-flow"), RequirePermission("Finance.Read")]
    public async Task<IActionResult> CashFlow([FromQuery]DateOnly? from,[FromQuery]DateOnly? to,CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync(@"select due_date day,sum(revenue) revenue,sum(expense) expense,sum(revenue-expense) net from (select due_date,amount revenue,0::numeric expense from barber.accounts_receivable where tenant_id=@tenant and branch_id=@branch and status<>'Cancelled' union all select due_date,0,amount from barber.accounts_payable where tenant_id=@tenant and branch_id=@branch and status<>'Cancelled') x where due_date between @from and @to group by due_date order by due_date",c=>{Add(c,"from",from??DateOnly.FromDateTime(DateTime.UtcNow));Add(c,"to",to??DateOnly.FromDateTime(DateTime.UtcNow.AddDays(30)));},ct)));
    [HttpGet("dre"), RequirePermission("Finance.Read")]
    public async Task<IActionResult> Dre([FromQuery]DateOnly? from,[FromQuery]DateOnly? to,CancellationToken ct)=>Ok(Envelope((await Data.QueryAsync(@"select coalesce((select sum(amount) from barber.accounts_receivable where tenant_id=@tenant and branch_id=@branch and status='Received' and received_at::date between @from and @to),0) revenue,coalesce((select sum(amount) from barber.accounts_payable where tenant_id=@tenant and branch_id=@branch and status='Paid' and paid_at::date between @from and @to),0) expense",c=>{Add(c,"from",from??new DateOnly(DateTime.UtcNow.Year,DateTime.UtcNow.Month,1));Add(c,"to",to??DateOnly.FromDateTime(DateTime.UtcNow));},ct)).Single()));
}

[Route("api/finance/categories")]
public sealed class FinancialCategoriesController(TeamDataService data) : FinanceControllerBase(data)
{
    [HttpGet, RequirePermission("Finance.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select id,name,type,parent_id,color,icon,status from barber.financial_categories where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by type,name",null,ct)));
    [HttpPost, RequirePermission("Finance.Manage")] [HttpPut("{id:guid}"), RequirePermission("Finance.Manage")]
    public async Task<IActionResult> Save(CategoryRequest request,CancellationToken ct,Guid? id=null){if(string.IsNullOrWhiteSpace(request.Name))return Invalid("name","Nome é obrigatório.");if(!new[]{"Revenue","Expense","Transfer","Adjustment"}.Contains(request.Type))return Invalid("type","Tipo inválido.");var key=await Data.WriteAsync(@"insert into barber.financial_categories(id,tenant_id,branch_id,name,type,parent_id,color,icon,status) values(@id,@tenant,@branch,@name,@type,@parent,@color,@icon,@status) on conflict(id) do update set name=excluded.name,type=excluded.type,parent_id=excluded.parent_id,color=excluded.color,icon=excluded.icon,status=excluded.status,updated_at=now() where financial_categories.tenant_id=@tenant and financial_categories.branch_id=@branch","Finance.CategorySaved","financial_categories",id,null,c=>{Add(c,"name",request.Name.Trim());Add(c,"type",request.Type);Add(c,"parent",request.ParentId);Add(c,"color",request.Color);Add(c,"icon",request.Icon);Add(c,"status",request.Status);},ct);return Ok(Envelope(new{id=key}));}
    public sealed record CategoryRequest(string Name,string Type,Guid? ParentId,string? Color,string? Icon,string Status="Active");
}

[Route("api/suppliers")]
public sealed class SuppliersController(TeamDataService data) : FinanceControllerBase(data)
{
    [HttpGet, RequirePermission("Finance.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select id,name,document_number,email,phone,status from barber.suppliers where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by name",null,ct)));
    [HttpPost, RequirePermission("Finance.Manage")] [HttpPut("{id:guid}"), RequirePermission("Finance.Manage")]
    public async Task<IActionResult> Save(SupplierRequest request,CancellationToken ct,Guid? id=null){if(string.IsNullOrWhiteSpace(request.Name))return Invalid("name","Nome é obrigatório.");var key=await Data.WriteAsync(@"insert into barber.suppliers(id,tenant_id,branch_id,name,document_number,email,phone,address_json,notes,status) values(@id,@tenant,@branch,@name,@document,@email,@phone,@address::jsonb,@notes,@status) on conflict(id) do update set name=excluded.name,document_number=excluded.document_number,email=excluded.email,phone=excluded.phone,address_json=excluded.address_json,notes=excluded.notes,status=excluded.status,updated_at=now() where suppliers.tenant_id=@tenant and suppliers.branch_id=@branch","Finance.SupplierSaved","suppliers",id,null,c=>{Add(c,"name",request.Name.Trim());Add(c,"document",request.DocumentNumber);Add(c,"email",request.Email);Add(c,"phone",request.Phone);Add(c,"address",request.AddressJson??"{}");Add(c,"notes",request.Notes);Add(c,"status",request.Status);},ct);return Ok(Envelope(new{id=key}));}
    public sealed record SupplierRequest(string Name,string? DocumentNumber,string? Email,string? Phone,string? AddressJson,string? Notes,string Status="Active");
}

public sealed record AccountRequest(Guid CategoryId,string Description,decimal Amount,DateOnly DueDate,Guid? PartyId,string? PaymentMethod,string? Reference,string? Notes);
public sealed record SettlementRequest(string PaymentMethod,string Reference);
public sealed record CancelFinanceRequest(string Reason);

[Route("api/finance/payables")]
public sealed class AccountsPayableController(TeamDataService data) : FinanceControllerBase(data)
{
    [HttpGet, RequirePermission("Finance.Read")] public async Task<IActionResult> List([FromQuery]string? status,CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select a.*,s.name supplier_name,c.name category_name from barber.accounts_payable a left join barber.suppliers s on s.id=a.supplier_id join barber.financial_categories c on c.id=a.category_id where a.tenant_id=@tenant and a.branch_id=@branch and a.deleted_at is null and (@status is null or a.status=@status) order by a.due_date",c=>Add(c,"status",status),ct)));
    [HttpPost, RequirePermission("Finance.Manage")] [HttpPut("{id:guid}"), RequirePermission("Finance.Manage")]
    public Task<IActionResult> Save(AccountRequest r,CancellationToken ct,Guid? id=null)=>SaveCore(r,id,ct);
    private async Task<IActionResult> SaveCore(AccountRequest r,Guid? id,CancellationToken ct){if(r.Amount<=0)return Invalid("amount","O valor deve ser maior que zero.");if(string.IsNullOrWhiteSpace(r.Description))return Invalid("description","Descrição é obrigatória.");var key=await Data.WriteAsync(@"insert into barber.accounts_payable(id,tenant_id,branch_id,supplier_id,category_id,description,amount,due_date,payment_method,reference,notes) select @id,@tenant,@branch,@party,c.id,@description,@amount,@due,@method,@reference,@notes from barber.financial_categories c where c.id=@category and c.tenant_id=@tenant and c.branch_id=@branch and c.status='Active' and (@party is null or exists(select 1 from barber.suppliers s where s.id=@party and s.tenant_id=@tenant and s.branch_id=@branch and s.status='Active' and s.deleted_at is null)) on conflict(id) do update set supplier_id=excluded.supplier_id,category_id=excluded.category_id,description=excluded.description,amount=excluded.amount,due_date=excluded.due_date,payment_method=excluded.payment_method,reference=excluded.reference,notes=excluded.notes,updated_at=now() where accounts_payable.tenant_id=@tenant and accounts_payable.branch_id=@branch and accounts_payable.status in ('Open','Overdue')","Finance.PayableSaved","accounts_payable",id,null,c=>Bind(c,r),ct);return Ok(Envelope(new{id=key}));}
    [HttpPost("{id:guid}/mark-paid"), RequirePermission("Finance.Manage")] public async Task<IActionResult> Paid(Guid id,SettlementRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.PaymentMethod)||string.IsNullOrWhiteSpace(r.Reference))return Invalid("paymentMethod","Forma e referência são obrigatórias.");await Data.WriteAsync("update barber.accounts_payable set status='Paid',paid_at=now(),payment_method=@method,reference=@reference,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','Overdue')","Finance.PayablePaid","accounts_payable",id,r.Reference,c=>{Add(c,"method",r.PaymentMethod);Add(c,"reference",r.Reference);},ct);return Ok(Envelope(new{id}));}
    [HttpPost("{id:guid}/cancel"), RequirePermission("Finance.Manage")] public async Task<IActionResult> Cancel(Guid id,CancelFinanceRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return Invalid("reason","Motivo é obrigatório.");await Data.WriteAsync("update barber.accounts_payable set status='Cancelled',cancellation_reason=@reason,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','Overdue')","Finance.PayableCancelled","accounts_payable",id,r.Reason,c=>Add(c,"reason",r.Reason),ct);return Ok(Envelope(new{id}));}
    private static void Bind(DbCommand c,AccountRequest r){Add(c,"party",r.PartyId);Add(c,"category",r.CategoryId);Add(c,"description",r.Description.Trim());Add(c,"amount",r.Amount);Add(c,"due",r.DueDate);Add(c,"method",r.PaymentMethod);Add(c,"reference",r.Reference);Add(c,"notes",r.Notes);Add(c,"user",Guid.Empty);}
}

[Route("api/finance/receivables")]
public sealed class AccountsReceivableController(TeamDataService data) : FinanceControllerBase(data)
{
    [HttpGet, RequirePermission("Finance.Read")] public async Task<IActionResult> List([FromQuery]string? status,CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select a.*,c.name category_name,cl.name client_name from barber.accounts_receivable a left join barber.clients cl on cl.id=a.client_id join barber.financial_categories c on c.id=a.category_id where a.tenant_id=@tenant and a.branch_id=@branch and a.deleted_at is null and (@status is null or a.status=@status) order by a.due_date",c=>Add(c,"status",status),ct)));
    [HttpPost, RequirePermission("Finance.Manage")] [HttpPut("{id:guid}"), RequirePermission("Finance.Manage")]
    public async Task<IActionResult> Save(AccountRequest r,CancellationToken ct,Guid? id=null){if(r.Amount<=0)return Invalid("amount","O valor deve ser maior que zero.");if(string.IsNullOrWhiteSpace(r.Description))return Invalid("description","Descrição é obrigatória.");var key=await Data.WriteAsync(@"insert into barber.accounts_receivable(id,tenant_id,branch_id,client_id,category_id,description,amount,due_date,payment_method,reference,notes) select @id,@tenant,@branch,@party,c.id,@description,@amount,@due,@method,@reference,@notes from barber.financial_categories c where c.id=@category and c.tenant_id=@tenant and c.branch_id=@branch and c.status='Active' and (@party is null or exists(select 1 from barber.clients cl where cl.id=@party and cl.tenant_id=@tenant and cl.branch_id=@branch)) on conflict(id) do update set client_id=excluded.client_id,category_id=excluded.category_id,description=excluded.description,amount=excluded.amount,due_date=excluded.due_date,payment_method=excluded.payment_method,reference=excluded.reference,notes=excluded.notes,updated_at=now() where accounts_receivable.tenant_id=@tenant and accounts_receivable.branch_id=@branch and accounts_receivable.status in ('Open','Overdue')","Finance.ReceivableSaved","accounts_receivable",id,null,c=>{Add(c,"party",r.PartyId);Add(c,"category",r.CategoryId);Add(c,"description",r.Description.Trim());Add(c,"amount",r.Amount);Add(c,"due",r.DueDate);Add(c,"method",r.PaymentMethod);Add(c,"reference",r.Reference);Add(c,"notes",r.Notes);Add(c,"user",Guid.Empty);},ct);return Ok(Envelope(new{id=key}));}
    [HttpPost("{id:guid}/mark-received"), RequirePermission("Finance.Manage")] public async Task<IActionResult> Received(Guid id,SettlementRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.PaymentMethod)||string.IsNullOrWhiteSpace(r.Reference))return Invalid("paymentMethod","Forma e referência são obrigatórias.");await Data.WriteAsync("update barber.accounts_receivable set status='Received',received_at=now(),payment_method=@method,reference=@reference,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','Overdue')","Finance.ReceivableReceived","accounts_receivable",id,r.Reference,c=>{Add(c,"method",r.PaymentMethod);Add(c,"reference",r.Reference);},ct);return Ok(Envelope(new{id}));}
    [HttpPost("{id:guid}/cancel"), RequirePermission("Finance.Manage")] public async Task<IActionResult> Cancel(Guid id,CancelFinanceRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return Invalid("reason","Motivo é obrigatório.");await Data.WriteAsync("update barber.accounts_receivable set status='Cancelled',cancellation_reason=@reason,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','Overdue')","Finance.ReceivableCancelled","accounts_receivable",id,r.Reason,c=>Add(c,"reason",r.Reason),ct);return Ok(Envelope(new{id}));}
}

[Route("api/finance/recurring-rules")]
public sealed class RecurringFinancialRulesController(TeamDataService data) : FinanceControllerBase(data)
{
    [HttpGet, RequirePermission("Finance.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.recurring_financial_rules where tenant_id=@tenant and branch_id=@branch order by next_run_at",null,ct)));
    [HttpPost, RequirePermission("Finance.Manage")] public async Task<IActionResult> Save(RecurringRequest r,CancellationToken ct){if(r.Amount<=0)return Invalid("amount","O valor deve ser maior que zero.");if(r.EndsAt<r.StartsAt)return Invalid("endsAt","A data final deve ser posterior à inicial.");if(!new[]{"Payable","Receivable"}.Contains(r.Type)||!new[]{"Monthly","Weekly","Yearly"}.Contains(r.Frequency))return Invalid("frequency","Tipo ou frequência inválidos.");var id=await Data.WriteAsync("insert into barber.recurring_financial_rules(id,tenant_id,branch_id,category_id,supplier_id,type,description,amount,frequency,day_of_month,starts_at,ends_at,next_run_at) select @id,@tenant,@branch,c.id,@supplier,@type,@description,@amount,@frequency,@day,@starts,@ends,@starts from barber.financial_categories c where c.id=@category and c.tenant_id=@tenant and c.branch_id=@branch and c.status='Active'","Finance.RecurringCreated","recurring_financial_rules",null,null,c=>{Add(c,"category",r.CategoryId);Add(c,"supplier",r.SupplierId);Add(c,"type",r.Type);Add(c,"description",r.Description);Add(c,"amount",r.Amount);Add(c,"frequency",r.Frequency);Add(c,"day",r.DayOfMonth);Add(c,"starts",r.StartsAt);Add(c,"ends",r.EndsAt);Add(c,"user",Guid.Empty);},ct);return Ok(Envelope(new{id}));}
    [HttpPost("{id:guid}/run"), RequirePermission("Finance.Manage")] public async Task<IActionResult> Run(Guid id,CancellationToken ct){var created=await Data.WriteAsync(@"insert into barber.accounts_payable(id,tenant_id,branch_id,supplier_id,category_id,description,amount,due_date) select @id,tenant_id,branch_id,supplier_id,category_id,description,amount,next_run_at from barber.recurring_financial_rules where id=@rule and tenant_id=@tenant and branch_id=@branch and type='Payable' and status='Active' and next_run_at<=current_date","Finance.RecurringGenerated","accounts_payable",null,null,c=>Add(c,"rule",id),ct);await Data.WriteAsync("update barber.recurring_financial_rules set next_run_at=case frequency when 'Weekly' then next_run_at+7 when 'Monthly' then (next_run_at+interval '1 month')::date else (next_run_at+interval '1 year')::date end,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","Finance.RecurringAdvanced","recurring_financial_rules",id,null,null,ct);return Ok(Envelope(new{id=created}));}
    public sealed record RecurringRequest(Guid CategoryId,Guid? SupplierId,string Type,string Description,decimal Amount,string Frequency,int? DayOfMonth,DateOnly StartsAt,DateOnly? EndsAt);
}

[Route("api/finance/reconciliations")]
public sealed class FinancialReconciliationController(TeamDataService data) : FinanceControllerBase(data)
{
    [HttpGet, RequirePermission("Finance.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.financial_reconciliations where tenant_id=@tenant and branch_id=@branch order by period_start desc",null,ct)));
    [HttpPost, RequirePermission("Finance.Manage")] public async Task<IActionResult> Create(ReconciliationRequest r,CancellationToken ct){if(r.PeriodEnd<r.PeriodStart)return Invalid("periodEnd","Período inválido.");var id=await Data.WriteAsync(@"insert into barber.financial_reconciliations(id,tenant_id,branch_id,cash_register_id,period_start,period_end,expected_amount,actual_amount,difference_amount) select @id,@tenant,@branch,cr.id,@start,@end,@expected,@actual,@actual-@expected from barber.cash_registers cr where cr.id=@cash and cr.tenant_id=@tenant and cr.branch_id=@branch","Finance.ReconciliationCreated","financial_reconciliations",null,null,c=>{Add(c,"cash",r.CashRegisterId);Add(c,"start",r.PeriodStart);Add(c,"end",r.PeriodEnd);Add(c,"expected",r.ExpectedAmount);Add(c,"actual",r.ActualAmount);},ct);return Ok(Envelope(new{id}));}
    [HttpPost("{id:guid}/close"), RequirePermission("Finance.Manage")] public async Task<IActionResult> Close(Guid id,CancellationToken ct){await Data.WriteAsync("update barber.financial_reconciliations set status='Closed',closed_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Draft'","Finance.ReconciliationClosed","financial_reconciliations",id,null,null,ct);return Ok(Envelope(new{id}));}
    public sealed record ReconciliationRequest(Guid CashRegisterId,DateTimeOffset PeriodStart,DateTimeOffset PeriodEnd,decimal ExpectedAmount,decimal ActualAmount);
}

[Route("api/finance/reports")]
public sealed class FinancialReportsController(TeamDataService data) : FinanceControllerBase(data)
{
    private static readonly string[] Types=["cash-flow","dre","payables","receivables","revenue-category","expense-category","payment-method","supplier","delinquency","reconciliations"];
    [HttpGet("export"), RequirePermission("Finance.Export")]
    public async Task<IActionResult> Export([FromQuery]string? type,[FromQuery]DateOnly? from,[FromQuery]DateOnly? to,CancellationToken ct){if(type is null||!Types.Contains(type))return Invalid("type","Selecione um relatório válido.");if(from is null)return Invalid("from","Data inicial obrigatória.");if(to is null||to<from)return Invalid("to","Data final inválida.");var rows=await Data.QueryAsync("select 'Payable' kind,description,amount,due_date date,status from barber.accounts_payable where tenant_id=@tenant and branch_id=@branch and due_date between @from and @to union all select 'Receivable',description,amount,due_date,status from barber.accounts_receivable where tenant_id=@tenant and branch_id=@branch and due_date between @from and @to order by date",c=>{Add(c,"from",from);Add(c,"to",to);},ct);var csv=new StringBuilder("tipo;descricao;valor;data;status\n");foreach(var row in rows)csv.AppendLine(string.Join(';',new[]{row["kind"],row["description"],row["amount"],row["date"],row["status"]}.Select(v=>$"\"{v?.ToString()?.Replace("\"","\"\"")}\"")));return File(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv.ToString())).ToArray(),"text/csv",$"finance-{type}-{from:yyyyMMdd}-{to:yyyyMMdd}.csv");}
}
