using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BarberSync.Api.Security;
using BarberSync.Api.Services.Governance;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Npgsql;

namespace BarberSync.Api.Controllers;

[ApiController, Authorize(Roles="Owner,SuperAdmin,Admin,Manager"), Route("api/governance")]
public sealed class GovernanceController(GovernanceStore store, IPlanLimitService limits) : ControllerBase
{
    public sealed record BranchRequest(string Name, string? Document, string Timezone, string Status, string[] Modules);
    public sealed record InviteRequest(string Email, string RoleCode, Guid[] Branches, int ExpiresInHours = 72);
    public sealed record RoleRequest(string Code, string Name, string? Description, string Status);
    public sealed record MatrixRequest(Dictionary<string,string[]> Roles);
    public sealed record PrivacyRequest(string RequestType,string SubjectType,Guid SubjectId,string Reason);
    public sealed record ItemRequest(string? Reason);
    private object Error(string message, object? errors=null, bool upgrade=false) => new { message, traceId=HttpContext.TraceIdentifier, errors, upgradeRequired=upgrade };

    [HttpGet("dashboard"), RequirePermission("Governance.Read")]
    public async Task<IActionResult> Dashboard(CancellationToken ct)
    {
        const string sql="""select p.name plan,s.status subscription_status,s.trial_ends_at,(select count(*) from barber.users u where u.tenant_id=@tenant and u.deleted_at is null) users,(select count(*) from barber.branches b where b.tenant_id=@tenant and b.deleted_at is null) branches,p.max_users,p.max_branches,(select count(*) from barber.user_invitations i where i.tenant_id=@tenant and i.status='Pending') pending_invitations,(select count(*) from barber.privacy_requests r where r.tenant_id=@tenant and r.status in ('Open','Processing')) open_privacy_requests from barber.tenant_subscriptions s join barber.saas_plans p on p.id=s.plan_id where s.tenant_id=@tenant order by s.created_at desc limit 1""";
        var rows=await store.QueryAsync(sql,null,ct); return rows.Count==0 ? NotFound(Error("Assinatura não configurada para este tenant.")) : Ok(rows[0]);
    }
    [HttpGet("tenants"),RequirePermission("Tenant.Manage")] public Task<List<Dictionary<string,object?>>> Tenants(CancellationToken ct)=>store.QueryAsync("select id,name,status,created_at from barber.tenants where id=@tenant and deleted_at is null",null,ct);
    [HttpGet("branches"),RequirePermission("Governance.Read")] public Task<List<Dictionary<string,object?>>> Branches(CancellationToken ct)=>store.QueryAsync("select id,name,status,timezone,payload->>'document' document from barber.branches where tenant_id=@tenant and deleted_at is null order by name",null,ct);
    [HttpPost("branches"),RequirePermission("Branch.Manage")]
    public async Task<IActionResult> CreateBranch(BranchRequest request,CancellationToken ct){if(string.IsNullOrWhiteSpace(request.Name)||string.IsNullOrWhiteSpace(request.Timezone))return BadRequest(Error("Informe nome e timezone da filial."));var check=await limits.CheckAsync("branches",ct);if(!check.Allowed)return Conflict(Error("Limite do plano atingido",new{plan=new[]{check.Message}},true));var id=await store.ExecuteInsertAsync("insert into barber.branches(id,tenant_id,name,timezone,status,payload,created_at) values(gen_random_uuid(),@tenant,@name,@timezone,@status,jsonb_build_object('document',@document::text),now()) returning id",p=>{p.AddWithValue("name",request.Name.Trim());p.AddWithValue("document",(object?)request.Document??DBNull.Value);p.AddWithValue("timezone",request.Timezone);p.AddWithValue("status",request.Status);},ct);return Created($"/api/governance/branches/{id}",new{id});}
    [HttpPut("branches/{id:guid}"),RequirePermission("Branch.Manage")] public async Task<IActionResult> UpdateBranch(Guid id,BranchRequest r,CancellationToken ct){var count=await store.ExecuteAsync("update barber.branches set name=@name,payload=jsonb_set(payload,'{document}',to_jsonb(@document::text),true),timezone=@timezone,status=@status,updated_at=now() where id=@id and tenant_id=@tenant and deleted_at is null",p=>{p.AddWithValue("id",id);p.AddWithValue("name",r.Name);p.AddWithValue("document",(object?)r.Document??DBNull.Value);p.AddWithValue("timezone",r.Timezone);p.AddWithValue("status",r.Status);},ct);return count==0?NotFound(Error("Filial não encontrada.")):Ok(new{id});}
    [HttpGet("users"),RequirePermission("Governance.Read")] public Task<List<Dictionary<string,object?>>> Users(CancellationToken ct)=>store.QueryAsync("select u.id,u.full_name name,u.email,coalesce(string_agg(r.name,', '),'Sem perfil') role,u.status,u.payload->>'lastLoginAt' last_login_at from barber.users u left join barber.user_roles ur on ur.user_id=u.id left join barber.roles r on r.id=ur.role_id where u.tenant_id=@tenant and u.deleted_at is null group by u.id order by u.full_name",null,ct);
    [HttpPost("users/invite"),RequirePermission("Users.Manage")] public async Task<IActionResult> Invite(InviteRequest r,CancellationToken ct){if(!r.Email.Contains('@')||string.IsNullOrWhiteSpace(r.RoleCode)||r.Branches.Length==0)return BadRequest(Error("Informe e-mail válido, perfil e ao menos uma filial."));var check=await limits.CheckAsync("users",ct);if(!check.Allowed)return Conflict(Error("Limite do plano atingido",new{plan=new[]{check.Message}},true));var token=Convert.ToHexString(RandomNumberGenerator.GetBytes(32));var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token)));var id=await store.ExecuteInsertAsync("insert into barber.user_invitations(id,tenant_id,branch_id,email,role_code,status,token_hash,expires_at,created_by,created_at,updated_at) values(gen_random_uuid(),@tenant,@branch,@email,@role,'Pending',@hash,now()+(@hours||' hours')::interval,@user,now(),now()) returning id",p=>{p.AddWithValue("email",r.Email.Trim().ToLowerInvariant());p.AddWithValue("role",r.RoleCode);p.AddWithValue("hash",hash);p.AddWithValue("hours",r.ExpiresInHours.ToString());},ct);return Accepted(new{id,status="Pending",expiresInHours=r.ExpiresInHours});}
    [HttpPost("users/{id:guid}/disable"),RequirePermission("Users.Manage")] public Task<IActionResult> Disable(Guid id,CancellationToken ct)=>UserStatus(id,"Inactive",ct);
    [HttpPost("users/{id:guid}/enable"),RequirePermission("Users.Manage")] public async Task<IActionResult> Enable(Guid id,CancellationToken ct){var check=await limits.CheckAsync("users",ct);if(!check.Allowed)return Conflict(Error("Limite do plano atingido",new{plan=new[]{check.Message}},true));return await UserStatus(id,"Active",ct);}
    private async Task<IActionResult>UserStatus(Guid id,string status,CancellationToken ct){var n=await store.ExecuteAsync("update barber.users set status=@status,updated_at=now() where id=@id and tenant_id=@tenant and deleted_at is null",p=>{p.AddWithValue("id",id);p.AddWithValue("status",status);},ct);return n==0?NotFound(Error("Usuário não encontrado.")):Ok(new{id,status});}
    [HttpGet("roles"),RequirePermission("Governance.Read")]public Task<List<Dictionary<string,object?>>>Roles(CancellationToken ct)=>store.QueryAsync("select id,code,name,description,status from barber.custom_roles where tenant_id=@tenant and deleted_at is null order by name",null,ct);
    [HttpPost("roles"),RequirePermission("Roles.Manage")]public async Task<IActionResult>CreateRole(RoleRequest r,CancellationToken ct){if(!System.Text.RegularExpressions.Regex.IsMatch(r.Code??"","^[A-Z][A-Z0-9_.-]{2,49}$"))return BadRequest(Error("Código de perfil inválido."));try{var id=await store.ExecuteInsertAsync("insert into barber.custom_roles(id,tenant_id,branch_id,code,name,description,status,created_by,created_at,updated_at) values(gen_random_uuid(),@tenant,@branch,@code,@name,@description,@status,@user,now(),now()) returning id",p=>{p.AddWithValue("code",r.Code);p.AddWithValue("name",r.Name);p.AddWithValue("description",(object?)r.Description??DBNull.Value);p.AddWithValue("status",r.Status);},ct);return Created($"/api/governance/roles/{id}",new{id});}catch(PostgresException e)when(e.SqlState=="23505"){return Conflict(Error("Já existe um perfil com este código ou nome."));}}
    [HttpPut("roles/{id:guid}"),RequirePermission("Roles.Manage")]public async Task<IActionResult>UpdateRole(Guid id,RoleRequest r,CancellationToken ct){var n=await store.ExecuteAsync("update barber.custom_roles set name=@name,description=@description,status=@status,updated_at=now() where id=@id and tenant_id=@tenant and deleted_at is null",p=>{p.AddWithValue("id",id);p.AddWithValue("name",r.Name);p.AddWithValue("description",(object?)r.Description??DBNull.Value);p.AddWithValue("status",r.Status);},ct);return n==0?NotFound(Error("Perfil não encontrado.")):Ok(new{id});}
    [HttpGet("permissions/matrix"),RequirePermission("Governance.Read")]public Task<List<Dictionary<string,object?>>>Matrix(CancellationToken ct)=>store.QueryAsync("select r.code role_code,r.name role_name,p.code permission_code,p.description from barber.custom_roles r cross join barber.permissions p where r.tenant_id=@tenant and r.deleted_at is null order by p.code,r.name",null,ct);
    [HttpPut("permissions/matrix"),RequirePermission("Permissions.Manage")]public async Task<IActionResult>SaveMatrix(MatrixRequest r,CancellationToken ct){if(r.Roles.Count==0)return BadRequest(Error("Selecione ao menos um perfil e suas permissões."));foreach(var role in r.Roles){await store.ExecuteAsync("delete from barber.custom_role_permissions where tenant_id=@tenant and role_id=(select id from barber.custom_roles where tenant_id=@tenant and code=@role)",p=>p.AddWithValue("role",role.Key),ct);foreach(var permission in role.Value)await store.ExecuteAsync("insert into barber.custom_role_permissions(tenant_id,branch_id,role_id,permission_code,created_by) select @tenant,@branch,id,@permission,@user from barber.custom_roles where tenant_id=@tenant and code=@role",p=>{p.AddWithValue("role",role.Key);p.AddWithValue("permission",permission);},ct);}return Ok(new{saved=true});}
    [HttpGet("plans"),RequirePermission("Governance.Read")]public Task<List<Dictionary<string,object?>>>Plans(CancellationToken ct)=>store.QueryAsync("select id,code,name,description,monthly_price,annual_price,max_branches,max_users,max_professionals,max_clients,status from barber.saas_plans where status='Active' order by monthly_price",null,ct);
    [HttpGet("subscription"),RequirePermission("Governance.Read")]public Task<List<Dictionary<string,object?>>>Subscription(CancellationToken ct)=>store.QueryAsync("select s.id,p.name plan,s.status,s.billing_cycle,s.starts_at,s.ends_at,s.trial_ends_at from barber.tenant_subscriptions s join barber.saas_plans p on p.id=s.plan_id where s.tenant_id=@tenant order by s.created_at desc limit 1",null,ct);
    [HttpGet("modules"),RequirePermission("Governance.Read")]public Task<List<Dictionary<string,object?>>>Modules(CancellationToken ct)=>store.QueryAsync("select module_key,is_enabled,settings_json,updated_at from barber.tenant_module_settings where tenant_id=@tenant order by module_key",null,ct);
    [HttpPut("modules/{moduleKey}"),RequirePermission("Governance.Manage")]public async Task<IActionResult>Module(string moduleKey,[FromBody]JsonElement body,CancellationToken ct){if(!body.TryGetProperty("isEnabled",out var enabled))return BadRequest(Error("Informe se o módulo deve estar habilitado."));await store.ExecuteAsync("insert into barber.tenant_module_settings(tenant_id,module_key,is_enabled,settings_json,updated_by) values(@tenant,@key,@enabled,@settings::jsonb,@user) on conflict(tenant_id,module_key) do update set is_enabled=excluded.is_enabled,settings_json=excluded.settings_json,updated_by=@user,updated_at=now()",p=>{p.AddWithValue("key",moduleKey);p.AddWithValue("enabled",enabled.GetBoolean());p.AddWithValue("settings",body.TryGetProperty("settings",out var s)?s.GetRawText():"{}");},ct);return Ok(new{moduleKey,isEnabled=enabled.GetBoolean()});}
    [HttpGet("security/policies"),RequirePermission("Security.Read")]public Task<List<Dictionary<string,object?>>>Policies(CancellationToken ct)=>store.QueryAsync("select policy_key,policy_value_json,status,updated_at from barber.security_policies where tenant_id=@tenant and (branch_id=@branch or branch_id is null) order by policy_key",null,ct);
    [HttpGet("security/events"),RequirePermission("Security.Read")]public Task<List<Dictionary<string,object?>>>SecurityEvents(CancellationToken ct)=>store.QueryAsync("select id,event_type,severity,ip_address,created_at from barber.security_events where tenant_id=@tenant and branch_id=@branch order by created_at desc limit 200",null,ct);
    [HttpGet("privacy/requests"),RequirePermission("Privacy.Manage")]public Task<List<Dictionary<string,object?>>>Privacy(CancellationToken ct)=>store.QueryAsync("select id,request_type,subject_type,status,reason,created_at,completed_at from barber.privacy_requests where tenant_id=@tenant and branch_id=@branch order by created_at desc",null,ct);
    [HttpPost("privacy/requests"),RequirePermission("Privacy.Manage")]public async Task<IActionResult>CreatePrivacy(PrivacyRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return BadRequest(Error("O motivo da solicitação é obrigatório."));var id=await store.ExecuteInsertAsync("insert into barber.privacy_requests(id,tenant_id,branch_id,request_type,subject_type,user_id,status,reason,requested_by,created_at,updated_at) values(gen_random_uuid(),@tenant,@branch,@type,@subject,@subjectId,'Open',@reason,@user,now(),now()) returning id",p=>{p.AddWithValue("type",r.RequestType);p.AddWithValue("subject",r.SubjectType);p.AddWithValue("subjectId",r.SubjectId);p.AddWithValue("reason",r.Reason);},ct);return Accepted(new{id,status="Open"});}
    [HttpPost("privacy/requests/{id:guid}/complete"),RequirePermission("Privacy.Manage")]public async Task<IActionResult>CompletePrivacy(Guid id,CancellationToken ct){var n=await store.ExecuteAsync("update barber.privacy_requests set status='Completed',completed_by=@user,completed_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','Processing')",p=>p.AddWithValue("id",id),ct);return n==0?Conflict(Error("Solicitação não encontrada ou já finalizada.")):Ok(new{id,status="Completed"});}
    [HttpGet("onboarding"),RequirePermission("Governance.Read")]public Task<List<Dictionary<string,object?>>>Onboarding(CancellationToken ct)=>store.QueryAsync("select i.item_key,i.title,i.description,i.status,i.completed_at from barber.onboarding_checklist_items i join barber.onboarding_checklists c on c.id=i.checklist_id where c.tenant_id=@tenant and c.branch_id=@branch order by i.created_at",null,ct);
    [HttpPost("onboarding/items/{itemKey}/complete"),RequirePermission("Onboarding.Manage")]public Task<IActionResult>CompleteItem(string itemKey,[FromBody]ItemRequest r,CancellationToken ct)=>SetItem(itemKey,"Completed",r,ct);
    [HttpPost("onboarding/items/{itemKey}/skip"),RequirePermission("Onboarding.Manage")]public Task<IActionResult>SkipItem(string itemKey,[FromBody]ItemRequest r,CancellationToken ct)=>string.IsNullOrWhiteSpace(r.Reason)?Task.FromResult<IActionResult>(BadRequest(Error("Informe o motivo para pular o item."))):SetItem(itemKey,"Skipped",r,ct);
    private async Task<IActionResult>SetItem(string key,string status,ItemRequest r,CancellationToken ct){var n=await store.ExecuteAsync("update barber.onboarding_checklist_items set status=@status,skip_reason=@reason,completed_by=@user,completed_at=now(),updated_at=now() where tenant_id=@tenant and branch_id=@branch and item_key=@key",p=>{p.AddWithValue("key",key);p.AddWithValue("status",status);p.AddWithValue("reason",(object?)r.Reason??DBNull.Value);},ct);return n==0?NotFound(Error("Item de onboarding não encontrado.")):Ok(new{itemKey=key,status});}
    [HttpGet("exports"),RequirePermission("Exports.Manage")]public Task<List<Dictionary<string,object?>>>Exports(CancellationToken ct)=>store.QueryAsync("select id,export_type,status,file_name,created_at,completed_at,failure_reason from barber.tenant_exports where tenant_id=@tenant and branch_id=@branch order by created_at desc",null,ct);
    [HttpPost("exports"),RequirePermission("Exports.Manage")]public async Task<IActionResult>CreateExport([FromBody]JsonElement body,CancellationToken ct){if(!body.TryGetProperty("exportType",out var type))return BadRequest(Error("Selecione o tipo da exportação."));var id=await store.ExecuteInsertAsync("insert into barber.tenant_exports(id,tenant_id,branch_id,export_type,status,filters_json,requested_by,created_at) values(gen_random_uuid(),@tenant,@branch,@type,'Pending',@filters::jsonb,@user,now()) returning id",p=>{p.AddWithValue("type",type.GetString()!);p.AddWithValue("filters",body.TryGetProperty("filters",out var f)?f.GetRawText():"{}");},ct);return Accepted(new{id,status="Pending"});}
}
