using System.Data.Common;
using System.Globalization;
using System.Text;
using BarberSync.Api.Security;
using BarberSync.Api.Services.Team;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BarberSync.Api.Controllers;

[ApiController, Authorize]
public abstract class InventoryControllerBase(TeamDataService data) : ControllerBase
{
    protected TeamDataService Data { get; } = data;
    protected object Envelope(object? value) => new { success = true, data = value };
    protected IActionResult Invalid(string field, string message) => BadRequest(new { message = "Revise os campos informados.", traceId = HttpContext.TraceIdentifier, errors = new Dictionary<string, string[]> { [field] = [message] } });
    protected static void Add(DbCommand command, string name, object? value) => TeamDataService.Add(command, name, value);
}

[Route("api/inventory")]
public sealed class InventoryController(TeamDataService data) : InventoryControllerBase(data)
{
    [HttpGet("branches"), RequirePermission("Inventory.Read")]
    public async Task<IActionResult> Branches(CancellationToken ct) => Ok(Envelope(await Data.QueryAsync("select id,name from barber.branches where tenant_id=@tenant and deleted_at is null and status='Active' order by name", null, ct)));

    [HttpGet("dashboard"), RequirePermission("Inventory.Read")]
    public async Task<IActionResult> Dashboard(CancellationToken ct) => Ok(Envelope((await Data.QueryAsync(@"select
count(*) filter(where p.status='Active') active_products,count(*) filter(where p.current_stock<=p.minimum_stock) below_minimum,
count(*) filter(where p.current_stock<=0) out_of_stock,coalesce(sum(p.current_stock*p.cost_price),0) stock_value,
(select count(*) from barber.purchase_orders o where o.tenant_id=@tenant and o.branch_id=@branch and o.status in ('Draft','PendingApproval','Approved','PartiallyReceived')) open_purchases,
(select count(*) from barber.inventory_counts c where c.tenant_id=@tenant and c.branch_id=@branch and c.status in ('Draft','Counting')) open_counts,
(select count(*) from barber.stock_transfers t where t.tenant_id=@tenant and (t.source_branch_id=@branch or t.target_branch_id=@branch) and t.status='Sent') pending_transfers,
(select count(*) from barber.replenishment_suggestions r where r.tenant_id=@tenant and r.branch_id=@branch and r.status='Open') replenishment,
(select count(*) from barber.product_lots l where l.tenant_id=@tenant and l.branch_id=@branch and l.expires_at between current_date and current_date+30) expiring_lots
from barber.products p where p.tenant_id=@tenant and p.branch_id=@branch and p.deleted_at is null", null, ct)).Single()));

    [HttpGet("products"), RequirePermission("Inventory.Read")]
    public async Task<IActionResult> Products(CancellationToken ct) => Ok(Envelope(await Data.QueryAsync(@"select p.id,p.sku,p.name,p.category_id,c.name category_name,p.usage_type,p.unit,p.cost_price,p.sale_price,p.current_stock,p.minimum_stock,p.reorder_point,p.status,ps.supplier_id,s.name supplier_name from barber.products p left join barber.product_categories c on c.id=p.category_id left join barber.product_suppliers ps on ps.product_id=p.id and ps.tenant_id=@tenant and ps.branch_id=@branch and ps.is_primary and ps.status='Active' left join barber.suppliers s on s.id=ps.supplier_id where p.tenant_id=@tenant and p.branch_id=@branch and p.deleted_at is null order by p.name", null, ct)));
    [HttpGet("products/{id:guid}"), RequirePermission("Inventory.Read")]
    public async Task<IActionResult> Product(Guid id, CancellationToken ct) { var rows = await Data.QueryAsync("select * from barber.products where id=@product and tenant_id=@tenant and branch_id=@branch and deleted_at is null", c => Add(c, "product", id), ct); return rows.Count == 0 ? NotFound(new { message = "Produto não encontrado.", traceId = HttpContext.TraceIdentifier }) : Ok(Envelope(rows[0])); }
    [HttpPost("products"), RequirePermission("Inventory.Manage")]
    [HttpPut("products/{id:guid}"), RequirePermission("Inventory.Manage")]
    public async Task<IActionResult> SaveProduct(ProductRequest r, CancellationToken ct, Guid? id = null)
    {
        if (string.IsNullOrWhiteSpace(r.Name)) return Invalid("name", "Nome é obrigatório.");
        if (r.CostPrice < 0 || r.SalePrice < 0 || r.MinimumStock < 0) return Invalid("costPrice", "Valores e estoque mínimo não podem ser negativos.");
        if (r.ReorderPoint < r.MinimumStock) return Invalid("reorderPoint", "O ponto de reposição deve ser maior ou igual ao estoque mínimo.");
        if (!new[] { "Sale", "Input", "Both" }.Contains(r.UsageType) || !new[] { "Unit", "Ml", "G", "Kg", "L" }.Contains(r.Unit)) return Invalid("usageType", "Tipo de uso ou unidade inválida.");
        var key = await Data.WriteAsync(@"with saved as (insert into barber.products(id,tenant_id,branch_id,sku,name,category_id,usage_type,unit,cost_price,sale_price,minimum_stock,reorder_point,status,is_active) select @id,@tenant,@branch,@sku,@name,c.id,@usage,@unit,@cost,@sale,@minimum,@reorder,@status,@status='Active' from barber.product_categories c where c.id=@category and c.tenant_id=@tenant and c.branch_id=@branch and c.status='Active' on conflict(id) do update set sku=excluded.sku,name=excluded.name,category_id=excluded.category_id,usage_type=excluded.usage_type,unit=excluded.unit,cost_price=excluded.cost_price,sale_price=excluded.sale_price,minimum_stock=excluded.minimum_stock,reorder_point=excluded.reorder_point,status=excluded.status,is_active=excluded.is_active,updated_at=now() where products.tenant_id=@tenant and products.branch_id=@branch returning id) insert into barber.product_suppliers(id,tenant_id,branch_id,product_id,supplier_id,is_primary,status) select gen_random_uuid(),@tenant,@branch,saved.id,s.id,true,'Active' from saved join barber.suppliers s on s.id=@supplier and s.tenant_id=@tenant and s.branch_id=@branch and s.status='Active' on conflict(tenant_id,branch_id,product_id,supplier_id) do update set is_primary=true,status='Active',updated_at=now()", "Inventory.ProductSaved", "products", id, null, c => { Add(c,"sku",r.Sku);Add(c,"name",r.Name.Trim());Add(c,"category",r.CategoryId);Add(c,"usage",r.UsageType);Add(c,"unit",r.Unit);Add(c,"cost",r.CostPrice);Add(c,"sale",r.SalePrice);Add(c,"minimum",r.MinimumStock);Add(c,"reorder",r.ReorderPoint);Add(c,"supplier",r.PrimarySupplierId);Add(c,"status",r.Status); }, ct);
        return Ok(Envelope(new { id = key }));
    }
    public sealed record ProductRequest(string Name, Guid CategoryId, Guid PrimarySupplierId, string? Sku, string UsageType, string Unit, decimal CostPrice, decimal SalePrice, decimal MinimumStock, decimal ReorderPoint, string Status = "Active");
}

[Route("api/inventory/product-categories")]
public sealed class ProductCategoriesController(TeamDataService data) : InventoryControllerBase(data)
{
    [HttpGet, RequirePermission("Inventory.Read")] public async Task<IActionResult> List(CancellationToken ct) => Ok(Envelope(await Data.QueryAsync("select id,name,description,parent_id,status from barber.product_categories where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by name", null, ct)));
    [HttpPost, RequirePermission("Inventory.Manage")][HttpPut("{id:guid}"), RequirePermission("Inventory.Manage")]
    public async Task<IActionResult> Save(CategoryRequest r, CancellationToken ct, Guid? id = null) { if (string.IsNullOrWhiteSpace(r.Name)) return Invalid("name", "Nome é obrigatório."); var key = await Data.WriteAsync("insert into barber.product_categories(id,tenant_id,branch_id,name,description,parent_id,status) values(@id,@tenant,@branch,@name,@description,@parent,@status) on conflict(id) do update set name=excluded.name,description=excluded.description,parent_id=excluded.parent_id,status=excluded.status,updated_at=now() where product_categories.tenant_id=@tenant and product_categories.branch_id=@branch", "Inventory.CategorySaved", "product_categories", id, null, c => { Add(c,"name",r.Name.Trim());Add(c,"description",r.Description);Add(c,"parent",r.ParentId);Add(c,"status",r.Status); }, ct); return Ok(Envelope(new { id = key })); }
    public sealed record CategoryRequest(string Name, string? Description, Guid? ParentId, string Status = "Active");
}

public sealed record PurchaseItemRequest(Guid ProductId, decimal Quantity, decimal UnitCost, decimal DiscountAmount = 0);
public sealed record PurchaseOrderRequest(Guid SupplierId, Guid? FinancialCategoryId, DateOnly? ExpectedDate, decimal FreightAmount, decimal DiscountAmount, string? Notes, IReadOnlyList<PurchaseItemRequest> Items);
public sealed record ReasonRequest(string Reason);

[Route("api/inventory/purchase-orders")]
public sealed class PurchaseOrdersController(TeamDataService data) : InventoryControllerBase(data)
{
    [HttpGet, RequirePermission("Inventory.Read")] public async Task<IActionResult> List(CancellationToken ct) => Ok(Envelope(await Data.QueryAsync("select o.*,s.name supplier_name,c.name financial_category_name from barber.purchase_orders o join barber.suppliers s on s.id=o.supplier_id left join barber.financial_categories c on c.id=o.financial_category_id where o.tenant_id=@tenant and o.branch_id=@branch order by o.created_at desc", null, ct)));
    [HttpPost, RequirePermission("Inventory.Purchase")][HttpPut("{id:guid}"), RequirePermission("Inventory.Purchase")]
    public async Task<IActionResult> Save(PurchaseOrderRequest r, CancellationToken ct, Guid? id = null)
    {
        if (r.Items.Count == 0) return Invalid("items", "Adicione pelo menos um produto selecionado.");
        if (r.Items.Any(x => x.Quantity <= 0 || x.UnitCost < 0) || r.Items.Select(x => x.ProductId).Distinct().Count() != r.Items.Count) return Invalid("items", "Quantidade, custo ou produtos duplicados são inválidos.");
        var items = System.Text.Json.JsonSerializer.Serialize(r.Items.Select(x => new { productId=x.ProductId,quantity=x.Quantity,unitCost=x.UnitCost,discountAmount=x.DiscountAmount }));
        var key = await Data.WriteAsync(@"with supplier as (select id from barber.suppliers where id=@supplier and tenant_id=@tenant and branch_id=@branch and status='Active'), saved as (insert into barber.purchase_orders(id,tenant_id,branch_id,supplier_id,financial_category_id,code,expected_date,subtotal_amount,discount_amount,freight_amount,total_amount,notes) select @id,@tenant,@branch,supplier.id,@category,'PC-'||upper(substr(replace(@id::text,'-',''),1,10)),@expected,x.subtotal,@discount,@freight,x.subtotal-@discount+@freight,@notes from supplier cross join lateral(select coalesce(sum((i->>'quantity')::numeric*(i->>'unitCost')::numeric-(i->>'discountAmount')::numeric),0) subtotal from jsonb_array_elements(@items::jsonb)i)x on conflict(id) do update set supplier_id=excluded.supplier_id,financial_category_id=excluded.financial_category_id,expected_date=excluded.expected_date,subtotal_amount=excluded.subtotal_amount,discount_amount=excluded.discount_amount,freight_amount=excluded.freight_amount,total_amount=excluded.total_amount,notes=excluded.notes,updated_at=now() where purchase_orders.tenant_id=@tenant and purchase_orders.branch_id=@branch and purchase_orders.status='Draft' returning id), cleared as(delete from barber.purchase_order_items where purchase_order_id in(select id from saved)) insert into barber.purchase_order_items(id,tenant_id,branch_id,purchase_order_id,product_id,quantity,unit_cost,discount_amount,total_amount) select gen_random_uuid(),@tenant,@branch,saved.id,p.id,(i->>'quantity')::numeric,(i->>'unitCost')::numeric,(i->>'discountAmount')::numeric,(i->>'quantity')::numeric*(i->>'unitCost')::numeric-(i->>'discountAmount')::numeric from saved,jsonb_array_elements(@items::jsonb)i join barber.products p on p.id=(i->>'productId')::uuid and p.tenant_id=@tenant and p.branch_id=@branch and p.status='Active'", "Inventory.PurchaseSaved", "purchase_orders", id, null, c => { Add(c,"supplier",r.SupplierId);Add(c,"category",r.FinancialCategoryId);Add(c,"expected",r.ExpectedDate);Add(c,"discount",r.DiscountAmount);Add(c,"freight",r.FreightAmount);Add(c,"notes",r.Notes);Add(c,"items",items); }, ct); return Ok(Envelope(new { id = key }));
    }
    [HttpPost("{id:guid}/approve"), RequirePermission("Inventory.Purchase")] public async Task<IActionResult> Approve(Guid id,CancellationToken ct) { await Data.WriteAsync("update barber.purchase_orders set status='Approved',approved_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Draft','PendingApproval') and exists(select 1 from barber.purchase_order_items i where i.purchase_order_id=@id)","Inventory.PurchaseApproved","purchase_orders",id,null,null,ct);return Ok(Envelope(new{id})); }
    [HttpPost("{id:guid}/cancel"), RequirePermission("Inventory.Purchase")] public async Task<IActionResult> Cancel(Guid id,ReasonRequest r,CancellationToken ct) { if(string.IsNullOrWhiteSpace(r.Reason))return Invalid("reason","Motivo do cancelamento é obrigatório.");await Data.WriteAsync("update barber.purchase_orders set status='Cancelled',cancel_reason=@reason,cancelled_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status not in ('Received','Cancelled')","Inventory.PurchaseCancelled","purchase_orders",id,r.Reason,c=>Add(c,"reason",r.Reason.Trim()),ct);return Ok(Envelope(new{id})); }
}

public sealed record ReceiptItemRequest(Guid PurchaseOrderItemId, decimal Quantity, string? LotCode, DateOnly? ExpiresAt);
public sealed record ReceiptRequest(Guid PurchaseOrderId, DateTimeOffset ReceivedAt, bool CreatePayable, string? Notes, IReadOnlyList<ReceiptItemRequest> Items);
[Route("api/inventory/purchase-receipts")]
public sealed class PurchaseReceiptsController(TeamDataService data) : InventoryControllerBase(data)
{
    [HttpGet, RequirePermission("Inventory.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select r.*,o.code purchase_code,s.name supplier_name from barber.purchase_receipts r join barber.purchase_orders o on o.id=r.purchase_order_id join barber.suppliers s on s.id=r.supplier_id where r.tenant_id=@tenant and r.branch_id=@branch order by r.created_at desc",null,ct)));
    [HttpPost, RequirePermission("Inventory.Receive")] public async Task<IActionResult> Create(ReceiptRequest r,CancellationToken ct) { if(r.Items.Count==0)return Invalid("items","Informe ao menos um item recebido.");if(r.Items.Any(x=>x.Quantity<=0||x.ExpiresAt<=DateOnly.FromDateTime(DateTime.UtcNow)))return Invalid("items","Quantidade deve ser positiva e validade, quando informada, deve ser futura.");var items=System.Text.Json.JsonSerializer.Serialize(r.Items.Select(x=>new{purchaseOrderItemId=x.PurchaseOrderItemId,quantity=x.Quantity,lotCode=x.LotCode,expiresAt=x.ExpiresAt}));var id=await Data.WriteAsync(@"with receipt as(insert into barber.purchase_receipts(id,tenant_id,branch_id,purchase_order_id,supplier_id,received_at,notes,create_payable) select @id,@tenant,@branch,o.id,o.supplier_id,@received,@notes,@payable from barber.purchase_orders o where o.id=@order and o.tenant_id=@tenant and o.branch_id=@branch and o.status in ('Approved','PartiallyReceived') returning id) insert into barber.purchase_receipt_items(id,tenant_id,branch_id,purchase_receipt_id,purchase_order_item_id,product_id,quantity,unit_cost,lot_code,expires_at) select gen_random_uuid(),@tenant,@branch,receipt.id,oi.id,oi.product_id,(i->>'quantity')::numeric,oi.unit_cost,nullif(i->>'lotCode',''),nullif(i->>'expiresAt','')::date from receipt,jsonb_array_elements(@items::jsonb)i join barber.purchase_order_items oi on oi.id=(i->>'purchaseOrderItemId')::uuid and oi.purchase_order_id=@order where (i->>'quantity')::numeric<=oi.quantity-oi.received_quantity", "Inventory.ReceiptCreated","purchase_receipts",null,null,c=>{Add(c,"order",r.PurchaseOrderId);Add(c,"received",r.ReceivedAt);Add(c,"notes",r.Notes);Add(c,"payable",r.CreatePayable);Add(c,"items",items);},ct);return Ok(Envelope(new{id})); }
    [HttpPost("{id:guid}/post"), RequirePermission("Inventory.Receive")] public async Task<IActionResult> Post(Guid id,CancellationToken ct) { await Data.WriteAsync(@"with receipt as(update barber.purchase_receipts set status='Posted',posted_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Draft' and exists(select 1 from barber.purchase_receipt_items where purchase_receipt_id=@id) returning *), moved as(insert into barber.stock_movements(id,tenant_id,branch_id,product_id,type,quantity,balance_after,reason) select gen_random_uuid(),@tenant,@branch,i.product_id,'PurchaseReceipt',i.quantity,p.current_stock+i.quantity,'Recebimento de compra' from receipt r join barber.purchase_receipt_items i on i.purchase_receipt_id=r.id join barber.products p on p.id=i.product_id returning product_id,quantity), stock as(update barber.products p set current_stock=p.current_stock+m.quantity,updated_at=now() from moved m where p.id=m.product_id), item_update as(update barber.purchase_order_items oi set received_quantity=oi.received_quantity+i.quantity,updated_at=now() from receipt r join barber.purchase_receipt_items i on i.purchase_receipt_id=r.id where oi.id=i.purchase_order_item_id returning oi.purchase_order_id), order_update as(update barber.purchase_orders o set status=case when not exists(select 1 from barber.purchase_order_items x where x.purchase_order_id=o.id and x.received_quantity<x.quantity) then 'Received' else 'PartiallyReceived' end,updated_at=now() where o.id in(select purchase_order_id from item_update)), payable as(insert into barber.accounts_payable(id,tenant_id,branch_id,supplier_id,category_id,description,amount,due_date,source_purchase_id) select gen_random_uuid(),@tenant,@branch,r.supplier_id,o.financial_category_id,'Compra '||o.code,sum(i.quantity*i.unit_cost),coalesce(o.expected_date,current_date),r.id from receipt r join barber.purchase_orders o on o.id=r.purchase_order_id join barber.purchase_receipt_items i on i.purchase_receipt_id=r.id where r.create_payable and o.financial_category_id is not null group by r.id,r.supplier_id,o.financial_category_id,o.code,o.expected_date on conflict(source_purchase_id) do nothing returning id) update barber.purchase_receipts set notes=notes where id in(select id from receipt)", "Inventory.ReceiptPosted","purchase_receipts",id,null,null,ct);return Ok(Envelope(new{id})); }
}

public sealed record CountItemRequest(Guid ProductId, decimal CountedQuantity, string? Notes);
public sealed record CountRequest(string? Notes, IReadOnlyList<CountItemRequest> Items);
[Route("api/inventory/counts")]
public sealed class InventoryCountsController(TeamDataService data) : InventoryControllerBase(data)
{
    [HttpGet, RequirePermission("Inventory.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.inventory_counts where tenant_id=@tenant and branch_id=@branch order by created_at desc",null,ct)));
    [HttpPost, RequirePermission("Inventory.Count")][HttpPut("{id:guid}"),RequirePermission("Inventory.Count")] public async Task<IActionResult> Save(CountRequest r,CancellationToken ct,Guid? id=null){if(r.Items.Count==0||r.Items.Any(x=>x.CountedQuantity<0))return Invalid("items","Selecione produtos e informe contagens não negativas.");if(r.Items.Any(x=>string.IsNullOrWhiteSpace(x.Notes)))return Invalid("notes","O motivo da contagem é obrigatório para permitir divergências auditáveis.");var items=System.Text.Json.JsonSerializer.Serialize(r.Items);var key=await Data.WriteAsync(@"with saved as(insert into barber.inventory_counts(id,tenant_id,branch_id,code,status,started_at,notes) values(@id,@tenant,@branch,'INV-'||upper(substr(replace(@id::text,'-',''),1,10)),'Counting',now(),@notes) on conflict(id) do update set notes=excluded.notes,updated_at=now() where inventory_counts.tenant_id=@tenant and inventory_counts.branch_id=@branch and inventory_counts.status in ('Draft','Counting') returning id),cleared as(delete from barber.inventory_count_items where inventory_count_id in(select id from saved)) insert into barber.inventory_count_items(id,tenant_id,branch_id,inventory_count_id,product_id,system_quantity,counted_quantity,difference_quantity,notes) select gen_random_uuid(),@tenant,@branch,saved.id,p.id,p.current_stock,(i->>'CountedQuantity')::numeric,(i->>'CountedQuantity')::numeric-p.current_stock,i->>'Notes' from saved,jsonb_array_elements(@items::jsonb)i join barber.products p on p.id=(i->>'ProductId')::uuid and p.tenant_id=@tenant and p.branch_id=@branch", "Inventory.CountSaved","inventory_counts",id,null,c=>{Add(c,"notes",r.Notes);Add(c,"items",items);},ct);return Ok(Envelope(new{id=key}));}
    [HttpPost("{id:guid}/close"),RequirePermission("Inventory.Count")] public async Task<IActionResult> Close(Guid id,CancellationToken ct){await Data.WriteAsync(@"with closed as(update barber.inventory_counts set status='Closed',closed_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Draft','Counting') and exists(select 1 from barber.inventory_count_items where inventory_count_id=@id) returning id),adjustment as(insert into barber.inventory_adjustments(id,tenant_id,branch_id,inventory_count_id,type,reason) select gen_random_uuid(),@tenant,@branch,id,'Count','Fechamento de inventário físico' from closed returning id,inventory_count_id),items as(insert into barber.inventory_adjustment_items(id,tenant_id,branch_id,inventory_adjustment_id,product_id,quantity) select gen_random_uuid(),@tenant,@branch,a.id,i.product_id,i.difference_quantity from adjustment a join barber.inventory_count_items i on i.inventory_count_id=a.inventory_count_id where i.difference_quantity<>0 returning product_id,quantity),moved as(insert into barber.stock_movements(id,tenant_id,branch_id,product_id,type,quantity,balance_after,reason) select gen_random_uuid(),@tenant,@branch,i.product_id,'InventoryAdjustment',i.quantity,p.current_stock+i.quantity,'Divergência de inventário' from items i join barber.products p on p.id=i.product_id returning product_id,quantity), stock as(update barber.products p set current_stock=p.current_stock+m.quantity,updated_at=now() from moved m where p.id=m.product_id) update barber.inventory_counts set updated_at=now() where id in(select id from closed)", "Inventory.CountClosed","inventory_counts",id,"Fechamento auditado",null,ct);return Ok(Envelope(new{id}));}
}

public sealed record TransferItemRequest(Guid ProductId,decimal Quantity);
public sealed record TransferRequest(Guid SourceBranchId,Guid TargetBranchId,string? Notes,IReadOnlyList<TransferItemRequest> Items);
[Route("api/inventory/transfers")]
public sealed class StockTransfersController(TeamDataService data):InventoryControllerBase(data)
{
    [HttpGet,RequirePermission("Inventory.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select t.*,s.name source_branch_name,d.name target_branch_name from barber.stock_transfers t join barber.branches s on s.id=t.source_branch_id join barber.branches d on d.id=t.target_branch_id where t.tenant_id=@tenant and (t.source_branch_id=@branch or t.target_branch_id=@branch) order by t.created_at desc",null,ct)));
    [HttpPost,RequirePermission("Inventory.Transfer")] public async Task<IActionResult> Create(TransferRequest r,CancellationToken ct){if(r.SourceBranchId==r.TargetBranchId)return Invalid("targetBranchId","Origem e destino devem ser diferentes.");if(r.Items.Count==0||r.Items.Any(x=>x.Quantity<=0))return Invalid("items","Selecione produtos e quantidades positivas.");var items=System.Text.Json.JsonSerializer.Serialize(r.Items);var id=await Data.WriteAsync(@"with saved as(insert into barber.stock_transfers(id,tenant_id,source_branch_id,target_branch_id,code,notes) select @id,@tenant,s.id,d.id,'TR-'||upper(substr(replace(@id::text,'-',''),1,10)),@notes from barber.branches s join barber.branches d on d.id=@target and d.tenant_id=@tenant where s.id=@source and s.id=@branch and s.tenant_id=@tenant returning id) insert into barber.stock_transfer_items(id,tenant_id,stock_transfer_id,product_id,quantity) select gen_random_uuid(),@tenant,saved.id,p.id,(i->>'Quantity')::numeric from saved,jsonb_array_elements(@items::jsonb)i join barber.products p on p.id=(i->>'ProductId')::uuid and p.tenant_id=@tenant and p.branch_id=@source and p.current_stock>=(i->>'Quantity')::numeric", "Inventory.TransferCreated","stock_transfers",null,null,c=>{Add(c,"source",r.SourceBranchId);Add(c,"target",r.TargetBranchId);Add(c,"notes",r.Notes);Add(c,"items",items);},ct);return Ok(Envelope(new{id}));}
    [HttpPost("{id:guid}/send"),RequirePermission("Inventory.Transfer")] public async Task<IActionResult> Send(Guid id,CancellationToken ct){await Data.WriteAsync(@"with sent as(update barber.stock_transfers set status='Sent',sent_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and source_branch_id=@branch and status='Draft' returning id),items as(select i.product_id,i.quantity from sent join barber.stock_transfer_items i on i.stock_transfer_id=sent.id),moved as(insert into barber.stock_movements(id,tenant_id,branch_id,product_id,type,quantity,balance_after,reason) select gen_random_uuid(),@tenant,@branch,i.product_id,'TransferOut',-i.quantity,p.current_stock-i.quantity,'Transferência enviada' from items i join barber.products p on p.id=i.product_id where p.current_stock>=i.quantity returning product_id,quantity) update barber.products p set current_stock=p.current_stock+m.quantity,updated_at=now() from moved m where p.id=m.product_id", "Inventory.TransferSent","stock_transfers",id,null,null,ct);return Ok(Envelope(new{id}));}
    [HttpPost("{id:guid}/receive"),RequirePermission("Inventory.Transfer")] public async Task<IActionResult> Receive(Guid id,CancellationToken ct){await Data.WriteAsync(@"with received as(update barber.stock_transfers set status='Received',received_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and target_branch_id=@branch and status='Sent' returning id),items as(select i.product_id,i.quantity from received join barber.stock_transfer_items i on i.stock_transfer_id=received.id),moved as(insert into barber.stock_movements(id,tenant_id,branch_id,product_id,type,quantity,balance_after,reason) select gen_random_uuid(),@tenant,@branch,p.id,'TransferIn',i.quantity,p.current_stock+i.quantity,'Transferência recebida' from items i join barber.products p on p.id=i.product_id and p.branch_id=@branch returning product_id,quantity) update barber.products p set current_stock=p.current_stock+m.quantity,updated_at=now() from moved m where p.id=m.product_id", "Inventory.TransferReceived","stock_transfers",id,null,null,ct);return Ok(Envelope(new{id}));}
}

public sealed record RecipeItemRequest(Guid ProductId,decimal Quantity,string Unit);
public sealed record RecipeRequest(Guid ServiceId,string Name,string Status,IReadOnlyList<RecipeItemRequest> Items);
[Route("api/inventory/service-input-recipes")]
public sealed class ServiceInputRecipesController(TeamDataService data):InventoryControllerBase(data)
{
    [HttpGet,RequirePermission("Inventory.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select r.id,r.name,r.status,r.service_id,s.name service_name,count(i.id) item_count from barber.service_input_recipes r join barber.services s on s.id=r.service_id left join barber.service_input_recipe_items i on i.recipe_id=r.id where r.tenant_id=@tenant and r.branch_id=@branch and r.deleted_at is null group by r.id,s.name order by s.name",null,ct)));
    [HttpPost,RequirePermission("Inventory.Manage")][HttpPut("{id:guid}"),RequirePermission("Inventory.Manage")] public async Task<IActionResult> Save(RecipeRequest r,CancellationToken ct,Guid? id=null){if(string.IsNullOrWhiteSpace(r.Name)||r.Items.Count==0||r.Items.Any(x=>x.Quantity<=0)||r.Items.Select(x=>x.ProductId).Distinct().Count()!=r.Items.Count)return Invalid("items","Nome, insumos únicos e quantidades positivas são obrigatórios.");var items=System.Text.Json.JsonSerializer.Serialize(r.Items);var key=await Data.WriteAsync(@"with saved as(insert into barber.service_input_recipes(id,tenant_id,branch_id,service_id,name,status) select @id,@tenant,@branch,s.id,@name,@status from barber.services s where s.id=@service and s.tenant_id=@tenant and s.branch_id=@branch and s.status='Active' on conflict(id) do update set name=excluded.name,status=excluded.status,updated_at=now() where service_input_recipes.tenant_id=@tenant and service_input_recipes.branch_id=@branch returning id),cleared as(delete from barber.service_input_recipe_items where recipe_id in(select id from saved)) insert into barber.service_input_recipe_items(id,tenant_id,branch_id,recipe_id,product_id,quantity,unit) select gen_random_uuid(),@tenant,@branch,saved.id,p.id,(i->>'Quantity')::numeric,i->>'Unit' from saved,jsonb_array_elements(@items::jsonb)i join barber.products p on p.id=(i->>'ProductId')::uuid and p.tenant_id=@tenant and p.branch_id=@branch and p.status='Active' and p.usage_type in ('Input','Both')", "Inventory.RecipeSaved","service_input_recipes",id,null,c=>{Add(c,"service",r.ServiceId);Add(c,"name",r.Name.Trim());Add(c,"status",r.Status);Add(c,"items",items);},ct);return Ok(Envelope(new{id=key}));}
}

[Route("api/inventory/replenishment")]
public sealed class ReplenishmentController(TeamDataService data):InventoryControllerBase(data)
{
    [HttpGet,RequirePermission("Inventory.Read")] public async Task<IActionResult> List(CancellationToken ct){await Data.QueryAsync(@"insert into barber.replenishment_suggestions(id,tenant_id,branch_id,product_id,supplier_id,suggested_quantity,reason) select gen_random_uuid(),p.tenant_id,p.branch_id,p.id,ps.supplier_id,greatest(p.reorder_point-p.current_stock,1),'Estoque abaixo do ponto de reposição' from barber.products p left join barber.product_suppliers ps on ps.product_id=p.id and ps.is_primary and ps.status='Active' where p.tenant_id=@tenant and p.branch_id=@branch and p.status='Active' and p.current_stock<=p.reorder_point and not exists(select 1 from barber.replenishment_suggestions r where r.product_id=p.id and r.status='Open') returning id",null,ct);return Ok(Envelope(await Data.QueryAsync("select r.*,p.name product_name,s.name supplier_name from barber.replenishment_suggestions r join barber.products p on p.id=r.product_id left join barber.suppliers s on s.id=r.supplier_id where r.tenant_id=@tenant and r.branch_id=@branch and r.status='Open' order by r.created_at",null,ct)));}
    [HttpPost("{id:guid}/convert-to-purchase"),RequirePermission("Inventory.Purchase")] public async Task<IActionResult> Convert(Guid id,CancellationToken ct){var order=Guid.NewGuid();await Data.WriteAsync(@"with suggestion as(update barber.replenishment_suggestions set status='ConvertedToPurchase',purchase_order_id=@order,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Open' and supplier_id is not null returning *),purchase as(insert into barber.purchase_orders(id,tenant_id,branch_id,supplier_id,code,status,subtotal_amount,total_amount,notes) select @order,@tenant,@branch,supplier_id,'PC-'||upper(substr(replace(@order::text,'-',''),1,10)),'Draft',suggested_quantity*p.cost_price,suggested_quantity*p.cost_price,'Gerado por sugestão real de reposição' from suggestion join barber.products p on p.id=suggestion.product_id returning id) insert into barber.purchase_order_items(id,tenant_id,branch_id,purchase_order_id,product_id,quantity,unit_cost,total_amount) select gen_random_uuid(),@tenant,@branch,purchase.id,s.product_id,s.suggested_quantity,p.cost_price,s.suggested_quantity*p.cost_price from purchase join suggestion s on true join barber.products p on p.id=s.product_id", "Inventory.ReplenishmentConverted","replenishment_suggestions",id,null,c=>Add(c,"order",order),ct);return Ok(Envelope(new{id=order}));}
    [HttpPost("{id:guid}/dismiss"),RequirePermission("Inventory.Manage")] public async Task<IActionResult> Dismiss(Guid id,ReasonRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return Invalid("reason","Motivo do descarte é obrigatório.");await Data.WriteAsync("update barber.replenishment_suggestions set status='Dismissed',dismiss_reason=@reason,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Open'", "Inventory.ReplenishmentDismissed","replenishment_suggestions",id,r.Reason,c=>Add(c,"reason",r.Reason.Trim()),ct);return Ok(Envelope(new{id}));}
}

[Route("api/inventory/reports")]
public sealed class InventoryReportsController(TeamDataService data):InventoryControllerBase(data)
{
    [HttpGet("export"),RequirePermission("Inventory.Export")] public async Task<IActionResult> Export([FromQuery]string type,[FromQuery]DateOnly from,[FromQuery]DateOnly to,CancellationToken ct){if(to<from)return Invalid("to","A data final deve ser igual ou posterior à inicial.");var allowed=new[]{"stock-position","below-minimum","movements","purchases","receipts","counts","adjustments","transfers","service-consumption","replenishment"};if(!allowed.Contains(type))return Invalid("type","Selecione um relatório válido.");var rows=await Data.QueryAsync("select created_at,type,quantity,reason,product_id from barber.stock_movements where tenant_id=@tenant and branch_id=@branch and created_at::date between @from and @to order by created_at",c=>{Add(c,"from",from);Add(c,"to",to);},ct);var csv=new StringBuilder("created_at,type,quantity,reason,product\n");foreach(var x in rows)csv.AppendLine(string.Join(',',x.Values.Select(v=>'\"'+Convert.ToString(v,CultureInfo.InvariantCulture)?.Replace("\"","\"\"")+'\"')));return File(Encoding.UTF8.GetBytes(csv.ToString()),"text/csv",$"inventory-{type}-{from}-{to}.csv");}
}
