using System.Data.Common;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BarberSync.Api.Security;
using BarberSync.Api.Services.Team;
using BarberSync.Application.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Npgsql;

namespace BarberSync.Api.Controllers;

[ApiController, Authorize]
public abstract class MarketingControllerBase(TeamDataService data, ICurrentUserContext user) : ControllerBase
{
    protected TeamDataService Data { get; } = data;
    protected ICurrentUserContext Current { get; } = user;
    protected static void Add(DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
    protected IActionResult Invalid(string field,string message)=>BadRequest(new{title="Dados de marketing inválidos",status=400,traceId=HttpContext.TraceIdentifier,errors=new Dictionary<string,string[]>{{field,[message]}}});
    protected object Envelope(object? value)=>new{success=true,data=value,traceId=HttpContext.TraceIdentifier};
}

[Route("api/marketing")]
public sealed class MarketingController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u)
{
 [HttpGet("dashboard"),RequirePermission("Marketing.Read")] public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(Envelope((await Data.QueryAsync(@"select count(*) filter(where status in('Scheduled','Running','Paused')) active_campaigns,coalesce(sum(sent_count),0) impacted,coalesce(sum(views_count),0) views,coalesce(sum(clicks_count),0) clicks,coalesce(sum(conversions_count),0) conversions,coalesce(sum(bookings_count),0) bookings,coalesce(sum(orders_count),0) orders,coalesce(sum(revenue_amount),0) revenue,case when sum(views_count)>0 then round(100.0*sum(clicks_count)/sum(views_count),2) else 0 end ctr from barber.marketing_campaign_results r join barber.marketing_campaigns c on c.id=r.campaign_id where r.tenant_id=@tenant and r.branch_id=@branch",null,ct)).Single()));
 [HttpGet("filter-options"),RequirePermission("Marketing.Read")] public async Task<IActionResult> Options(CancellationToken ct)=>Ok(Envelope(new{segments=await Data.QueryAsync("select id,name from barber.marketing_segments where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null order by name",null,ct),templates=await Data.QueryAsync("select id,name,channel_type from barber.communication_templates where tenant_id=@tenant and branch_id=@branch and status='Active' order by name",null,ct),coupons=await Data.QueryAsync("select id,code from barber.coupons where tenant_id=@tenant and branch_id=@branch and status='Active' order by code",null,ct),landings=await Data.QueryAsync("select id,title name from barber.marketing_landing_pages where tenant_id=@tenant and branch_id=@branch and status in('Draft','Active') and deleted_at is null order by title",null,ct),campaigns=await Data.QueryAsync("select id,name from barber.marketing_campaigns where tenant_id=@tenant and branch_id=@branch and status not in('Completed','Cancelled') order by name",null,ct),links=await Data.QueryAsync("select id,public_slug name from barber.marketing_promo_links where tenant_id=@tenant and branch_id=@branch and status='Active' order by public_slug",null,ct)}));
}

[Route("api/marketing/segments")]
public sealed class MarketingSegmentsController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u)
{
 static readonly HashSet<string> Types=["Static","Dynamic"];
 [HttpGet,RequirePermission("Marketing.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select s.*,count(m.id) members_count from barber.marketing_segments s left join barber.marketing_segment_members m on m.segment_id=s.id where s.tenant_id=@tenant and s.branch_id=@branch and s.deleted_at is null group by s.id order by s.updated_at desc",null,ct)));
 [HttpPost,RequirePermission("Marketing.Segments.Manage")] public Task<IActionResult> Create(SegmentRequest r,CancellationToken ct)=>Save(Guid.NewGuid(),r,false,ct);
 [HttpPut("{id:guid}"),RequirePermission("Marketing.Segments.Manage")] public Task<IActionResult> Update(Guid id,SegmentRequest r,CancellationToken ct)=>Save(id,r,true,ct);
 [HttpPost("{id:guid}/recalculate"),RequirePermission("Marketing.Segments.Manage")] public async Task<IActionResult> Recalculate(Guid id,CancellationToken ct){await Data.WriteAsync("update barber.marketing_segments set updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and segment_type='Dynamic' and deleted_at is null","Marketing.SegmentRecalculated","marketing_segments",id,null,null,ct);return Ok(Envelope(new{id,calculatedAt=DateTimeOffset.UtcNow}));}
 async Task<IActionResult> Save(Guid id,SegmentRequest r,bool update,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||!Types.Contains(r.SegmentType)||r.Criteria.ValueKind!=JsonValueKind.Array||r.Criteria.GetArrayLength()==0)return Invalid("criteria","Informe nome, tipo e pelo menos um critério do builder.");var sql=update?"update barber.marketing_segments set name=@name,description=@description,segment_type=@type,criteria_json=@criteria::jsonb,status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null":"insert into barber.marketing_segments(id,tenant_id,branch_id,name,segment_key,description,segment_type,criteria_json,status,created_by) values(@id,@tenant,@branch,@name,@key,@description,@type,@criteria::jsonb,@status,@user)";await Data.WriteAsync(sql,"Marketing.SegmentSaved","marketing_segments",id,null,c=>{Add(c,"name",r.Name.Trim());Add(c,"key",r.SegmentKey.Trim());Add(c,"description",r.Description?.Trim());Add(c,"type",r.SegmentType);Add(c,"criteria",r.Criteria.GetRawText());Add(c,"status",r.Status);Add(c,"user",Current.UserId);},ct);return Ok(Envelope(new{id}));}
}

[Route("api/marketing/campaigns")]
public sealed class MarketingCampaignsController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u)
{
 [HttpGet,RequirePermission("Marketing.Read")] public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select c.*,s.name segment_name,t.name template_name,l.title landing_title from barber.marketing_campaigns c join barber.marketing_segments s on s.id=c.segment_id left join barber.communication_templates t on t.id=c.template_id left join barber.marketing_landing_pages l on l.id=c.landing_page_id where c.tenant_id=@tenant and c.branch_id=@branch order by c.created_at desc",null,ct)));
 [HttpPost,RequirePermission("Marketing.Campaigns.Manage")] public Task<IActionResult> Create(CampaignRequest r,CancellationToken ct)=>Save(Guid.NewGuid(),r,false,ct);
 [HttpPut("{id:guid}"),RequirePermission("Marketing.Campaigns.Manage")] public Task<IActionResult> Update(Guid id,CampaignRequest r,CancellationToken ct)=>Save(id,r,true,ct);
 [HttpPost("{id:guid}/schedule"),RequirePermission("Marketing.Campaigns.Manage")] public Task<IActionResult> Schedule(Guid id,CancellationToken ct)=>Transition(id,"Scheduled",null,"Draft,Paused",ct);
 [HttpPost("{id:guid}/start"),RequirePermission("Marketing.Campaigns.Manage")] public async Task<IActionResult> Start(Guid id,CancellationToken ct){var ready=Convert.ToBoolean(await Data.ScalarAsync(@"select exists(select 1 from barber.marketing_campaigns c left join barber.communication_provider_settings p on p.tenant_id=c.tenant_id and p.branch_id=c.branch_id and p.channel_type=c.channel_type and p.status='Active' where c.id=@id and c.tenant_id=@tenant and c.branch_id=@branch and c.segment_id is not null and(c.channel_type in('InApp','PublicLink','Manual') or p.id is not null))",c=>Add(c,"id",id),ct));if(!ready)return Conflict(new{title="ProviderNotConfigured",status=409,traceId=HttpContext.TraceIdentifier,detail="A campanha não possui seleção válida ou provider configurado. Nenhum envio foi simulado."});return await Transition(id,"Running",null,"Scheduled,Paused",ct);}
 [HttpPost("{id:guid}/pause"),RequirePermission("Marketing.Campaigns.Manage")] public Task<IActionResult> Pause(Guid id,CancellationToken ct)=>Transition(id,"Paused",null,"Running,Scheduled",ct);
 [HttpPost("{id:guid}/cancel"),RequirePermission("Marketing.Campaigns.Manage")] public Task<IActionResult> Cancel(Guid id,ReasonRequest r,CancellationToken ct)=>string.IsNullOrWhiteSpace(r.Reason)?Task.FromResult(Invalid("reason","O cancelamento exige motivo.")):Transition(id,"Cancelled",r.Reason,"Draft,Scheduled,Running,Paused,Failed",ct);
 [HttpGet("{id:guid}/results"),RequirePermission("Marketing.Read")] public async Task<IActionResult> Results(Guid id,CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.marketing_campaign_results where tenant_id=@tenant and branch_id=@branch and campaign_id=@id order by snapshot_date",c=>Add(c,"id",id),ct)));
 async Task<IActionResult> Save(Guid id,CampaignRequest r,bool update,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||r.SegmentId==Guid.Empty||string.IsNullOrWhiteSpace(r.ChannelType)||(r.ChannelType is "Email" or "Sms" or "WhatsApp" or "Push")&&r.TemplateId is null)return Invalid("campaign","Nome, segmento, canal e template do canal são obrigatórios.");var sql=update?"update barber.marketing_campaigns set name=@name,objective=@objective,segment_id=@segment,channel_type=@channel,template_id=@template,coupon_id=@coupon,landing_page_id=@landing,starts_at=@starts,ends_at=@ends,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in('Draft','Scheduled','Paused')":"insert into barber.marketing_campaigns(id,tenant_id,branch_id,name,objective,segment_id,channel_type,template_id,coupon_id,landing_page_id,status,starts_at,ends_at,created_by) select @id,@tenant,@branch,@name,@objective,@segment,@channel,@template,@coupon,@landing,'Draft',@starts,@ends,@user where exists(select 1 from barber.marketing_segments where id=@segment and tenant_id=@tenant and branch_id=@branch)";await Data.WriteAsync(sql,"Marketing.CampaignSaved","marketing_campaigns",id,null,c=>{Add(c,"name",r.Name.Trim());Add(c,"objective",r.Objective);Add(c,"segment",r.SegmentId);Add(c,"channel",r.ChannelType);Add(c,"template",r.TemplateId);Add(c,"coupon",r.CouponId);Add(c,"landing",r.LandingPageId);Add(c,"starts",r.StartsAt);Add(c,"ends",r.EndsAt);Add(c,"user",Current.UserId);},ct);return Ok(Envelope(new{id,status="Draft"}));}
 async Task<IActionResult> Transition(Guid id,string status,string? reason,string from,CancellationToken ct){await Data.WriteAsync($"update barber.marketing_campaigns set status=@status,cancel_reason=@reason,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status=any(string_to_array('{from}',','))","Marketing.Campaign"+status,"marketing_campaigns",id,reason,c=>{Add(c,"status",status);Add(c,"reason",reason);},ct);return Ok(Envelope(new{id,status}));}
}

[Route("api/marketing/journeys")]
public sealed class MarketingJourneysController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u){[HttpGet,RequirePermission("Marketing.Read")]public async Task<IActionResult> List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.marketing_journeys where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by updated_at desc",null,ct)));[HttpPost,RequirePermission("Marketing.Journeys.Manage")]public Task<IActionResult>Create(JourneyRequest r,CancellationToken ct)=>Save(Guid.NewGuid(),r,false,ct);[HttpPut("{id:guid}"),RequirePermission("Marketing.Journeys.Manage")]public Task<IActionResult>Update(Guid id,JourneyRequest r,CancellationToken ct)=>Save(id,r,true,ct);[HttpPost("{id:guid}/activate"),RequirePermission("Marketing.Journeys.Manage")]public Task<IActionResult>Activate(Guid id,CancellationToken ct)=>State(id,"Active",ct);[HttpPost("{id:guid}/pause"),RequirePermission("Marketing.Journeys.Manage")]public Task<IActionResult>Pause(Guid id,CancellationToken ct)=>State(id,"Paused",ct);async Task<IActionResult>Save(Guid id,JourneyRequest r,bool update,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||string.IsNullOrWhiteSpace(r.TriggerType)||r.Steps.ValueKind!=JsonValueKind.Array||r.Steps.GetArrayLength()==0)return Invalid("steps","Informe nome, gatilho e ações da jornada.");var sql=update?"update barber.marketing_journeys set name=@name,trigger_type=@trigger,conditions_json=@conditions::jsonb,deduplication_hours=@window,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status<>'Archived'":"insert into barber.marketing_journeys(id,tenant_id,branch_id,name,trigger_type,conditions_json,deduplication_hours,status,created_by) values(@id,@tenant,@branch,@name,@trigger,@conditions::jsonb,@window,'Draft',@user)";await Data.WriteAsync(sql,"Marketing.JourneySaved","marketing_journeys",id,null,c=>{Add(c,"name",r.Name.Trim());Add(c,"trigger",r.TriggerType);Add(c,"conditions",r.Conditions.GetRawText());Add(c,"window",Math.Clamp(r.DeduplicationHours,1,8760));Add(c,"user",Current.UserId);},ct);return Ok(Envelope(new{id}));}async Task<IActionResult>State(Guid id,string status,CancellationToken ct){await Data.WriteAsync("update barber.marketing_journeys set status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in('Draft','Active','Paused')","Marketing.Journey"+status,"marketing_journeys",id,null,c=>Add(c,"status",status),ct);return Ok(Envelope(new{id,status}));}}

[Route("api/marketing/landing-pages")]
public sealed class MarketingLandingPagesController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u){[HttpGet,RequirePermission("Marketing.Read")]public async Task<IActionResult>List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.marketing_landing_pages where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by updated_at desc",null,ct)));[HttpPost,RequirePermission("Marketing.LandingPages.Manage")]public Task<IActionResult>Create(LandingRequest r,CancellationToken ct)=>Save(Guid.NewGuid(),r,false,ct);[HttpPut("{id:guid}"),RequirePermission("Marketing.LandingPages.Manage")]public Task<IActionResult>Update(Guid id,LandingRequest r,CancellationToken ct)=>Save(id,r,true,ct);[HttpPost("{id:guid}/publish"),RequirePermission("Marketing.LandingPages.Manage")]public Task<IActionResult>Publish(Guid id,CancellationToken ct)=>State(id,"Active",ct);[HttpPost("{id:guid}/archive"),RequirePermission("Marketing.LandingPages.Manage")]public Task<IActionResult>Archive(Guid id,CancellationToken ct)=>State(id,"Archived",ct);async Task<IActionResult>Save(Guid id,LandingRequest r,bool update,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Title)||!System.Text.RegularExpressions.Regex.IsMatch(r.Slug??"","^[a-z0-9]+(?:-[a-z0-9]+)*$")||r.CtaType!="None"&&string.IsNullOrWhiteSpace(r.CtaUrl))return Invalid("landing","Informe título, slug seguro e destino real do CTA.");var sql=update?"update barber.marketing_landing_pages set slug=@slug,title=@title,subtitle=@subtitle,body=@body,cta_label=@label,cta_type=@type,cta_url=@url,starts_at=@starts,ends_at=@ends,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status<>'Archived'":"insert into barber.marketing_landing_pages(id,tenant_id,branch_id,slug,title,subtitle,body,cta_label,cta_type,cta_url,status,starts_at,ends_at,created_by) values(@id,@tenant,@branch,@slug,@title,@subtitle,@body,@label,@type,@url,'Draft',@starts,@ends,@user)";await Data.WriteAsync(sql,"Marketing.LandingSaved","marketing_landing_pages",id,null,c=>{Add(c,"slug",r.Slug);Add(c,"title",r.Title.Trim());Add(c,"subtitle",r.Subtitle?.Trim());Add(c,"body",r.Body?.Trim());Add(c,"label",r.CtaLabel?.Trim());Add(c,"type",r.CtaType);Add(c,"url",r.CtaUrl?.Trim());Add(c,"starts",r.StartsAt);Add(c,"ends",r.EndsAt);Add(c,"user",Current.UserId);},ct);return Ok(Envelope(new{id}));}async Task<IActionResult>State(Guid id,string status,CancellationToken ct){await Data.WriteAsync("update barber.marketing_landing_pages set status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status<>'Archived'","Marketing.Landing"+status,"marketing_landing_pages",id,null,c=>Add(c,"status",status),ct);return Ok(Envelope(new{id,status}));}}

[Route("api/marketing/promo-links")]
public sealed class MarketingPromoLinksController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u){[HttpGet,RequirePermission("Marketing.Read")]public async Task<IActionResult>List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select id,public_slug,campaign_id,landing_page_id,destination_type,destination_url,status,valid_from,valid_until,created_at from barber.marketing_promo_links where tenant_id=@tenant and branch_id=@branch order by created_at desc",null,ct)));[HttpPost,RequirePermission("Marketing.Manage")]public async Task<IActionResult>Create(LinkRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.PublicSlug)||string.IsNullOrWhiteSpace(r.DestinationType)||string.IsNullOrWhiteSpace(r.DestinationUrl))return Invalid("link","Slug, tipo e destino são obrigatórios.");var id=Guid.NewGuid();var token=Convert.ToHexString(RandomNumberGenerator.GetBytes(32));var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(token))).ToLowerInvariant();await Data.WriteAsync("insert into barber.marketing_promo_links(id,tenant_id,branch_id,public_token_hash,public_slug,campaign_id,landing_page_id,destination_type,destination_url,status,valid_from,valid_until,created_by) values(@id,@tenant,@branch,@hash,@slug,@campaign,@landing,@type,@url,'Active',@from,@until,@user)","Marketing.LinkCreated","marketing_promo_links",id,null,c=>{Add(c,"hash",hash);Add(c,"slug",r.PublicSlug);Add(c,"campaign",r.CampaignId);Add(c,"landing",r.LandingPageId);Add(c,"type",r.DestinationType);Add(c,"url",r.DestinationUrl);Add(c,"from",r.ValidFrom);Add(c,"until",r.ValidUntil);Add(c,"user",Current.UserId);},ct);return Created($"/api/marketing/promo-links/{id}",Envelope(new{id,r.PublicSlug}));}[HttpPost("{id:guid}/deactivate"),RequirePermission("Marketing.Manage")]public async Task<IActionResult>Deactivate(Guid id,CancellationToken ct){await Data.WriteAsync("update barber.marketing_promo_links set status='Inactive',updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Active'","Marketing.LinkDeactivated","marketing_promo_links",id,null,null,ct);return Ok(Envelope(new{id,status="Inactive"}));}}

[Route("api/marketing/qr-codes")]
public sealed class MarketingQrCodesController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u){[HttpGet,RequirePermission("Marketing.Read")]public async Task<IActionResult>List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select q.id,q.name,q.display_payload_masked,q.status,q.created_at,l.public_slug from barber.marketing_qr_codes q join barber.marketing_promo_links l on l.id=q.promo_link_id where q.tenant_id=@tenant and q.branch_id=@branch and q.deleted_at is null order by q.created_at desc",null,ct)));[HttpPost,RequirePermission("Marketing.Manage")]public async Task<IActionResult>Create(QrRequest r,CancellationToken ct){if(r.PromoLinkId==Guid.Empty||string.IsNullOrWhiteSpace(r.Name))return Invalid("qrCode","Selecione um link e informe o nome.");var id=Guid.NewGuid();await Data.WriteAsync("insert into barber.marketing_qr_codes(id,tenant_id,branch_id,name,promo_link_id,qr_payload_hash,display_payload_masked,status,created_by) select @id,@tenant,@branch,@name,id,encode(digest('/go/'||public_slug,'sha256'),'hex'),'/go/'||left(public_slug,4)||'••••','Active',@user from barber.marketing_promo_links where id=@link and tenant_id=@tenant and branch_id=@branch and status='Active'","Marketing.QrCreated","marketing_qr_codes",id,null,c=>{Add(c,"name",r.Name.Trim());Add(c,"link",r.PromoLinkId);Add(c,"user",Current.UserId);},ct);return Created($"/api/marketing/qr-codes/{id}",Envelope(new{id}));}}

[Route("api/marketing/experiments")]
public sealed class MarketingExperimentsController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u){[HttpGet,RequirePermission("Marketing.Read")]public async Task<IActionResult>List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select e.*,coalesce(sum(v.views_count),0) views,coalesce(sum(v.clicks_count),0) clicks,coalesce(sum(v.conversions_count),0) conversions from barber.marketing_experiments e left join barber.marketing_experiment_variants v on v.experiment_id=e.id where e.tenant_id=@tenant and e.branch_id=@branch group by e.id order by e.created_at desc",null,ct)));[HttpPost,RequirePermission("Marketing.Manage")]public async Task<IActionResult>Create(ExperimentRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||r.Variants is not {Count:2}||r.Variants.Sum(x=>x.AllocationPercent)!=100||r.Variants.Any(x=>x.TemplateId==Guid.Empty))return Invalid("variants","Configure duas variações válidas cuja divisão totalize 100%.");var id=Guid.NewGuid();await Data.WriteAsync(@"insert into barber.marketing_experiments(id,tenant_id,branch_id,campaign_id,name,metric_key,status,starts_at,ends_at,created_by) select @id,@tenant,@branch,@campaign,@name,@metric,'Draft',@starts,@ends,@user where exists(select 1 from barber.marketing_campaigns where id=@campaign and tenant_id=@tenant and branch_id=@branch and status<>'Completed');insert into barber.marketing_experiment_variants(id,tenant_id,branch_id,experiment_id,variant_key,label,allocation_percent,template_id,settings_json) select gen_random_uuid(),@tenant,@branch,@id,x.key,x.label,x.allocation,x.template,'{}'::jsonb from jsonb_to_recordset(@variants::jsonb) x(key text,label text,allocation int,template uuid)","Marketing.ExperimentCreated","marketing_experiments",id,null,c=>{Add(c,"campaign",r.CampaignId);Add(c,"name",r.Name.Trim());Add(c,"metric",r.MetricKey);Add(c,"starts",r.StartsAt);Add(c,"ends",r.EndsAt);Add(c,"user",Current.UserId);Add(c,"variants",JsonSerializer.Serialize(r.Variants.Select(x=>new{key=x.VariantKey,label=x.Label,allocation=x.AllocationPercent,template=x.TemplateId})));},ct);return Created($"/api/marketing/experiments/{id}",Envelope(new{id}));}}

[Route("api/marketing/reports")]
public sealed class MarketingReportsController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u){[HttpGet("export"),RequirePermission("Marketing.Reports.Export")]public async Task<IActionResult>Export(CancellationToken ct){var rows=await Data.QueryAsync("select c.name,r.snapshot_date,r.sent_count,r.views_count,r.clicks_count,r.conversions_count,r.bookings_count,r.orders_count,r.revenue_amount from barber.marketing_campaign_results r join barber.marketing_campaigns c on c.id=r.campaign_id where r.tenant_id=@tenant and r.branch_id=@branch order by r.snapshot_date desc",null,ct);var csv=new StringBuilder("campanha;data;enviados;views;cliques;conversoes;agendamentos;pedidos;receita\r\n");foreach(var x in rows)csv.AppendLine(string.Join(';',x.Values.Select(v=>$"\"{Convert.ToString(v,CultureInfo.InvariantCulture)?.Replace("\"","\"\"")}\"")));return File(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv.ToString())).ToArray(),"text/csv",$"marketing-{DateTime.UtcNow:yyyyMMdd}.csv");}}

[Route("api/marketing/calendar")]
public sealed class MarketingCalendarController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u){[HttpGet,RequirePermission("Marketing.Read")]public async Task<IActionResult>List(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select * from barber.marketing_calendar_events where tenant_id=@tenant and branch_id=@branch order by starts_at",null,ct)));[HttpPost,RequirePermission("Marketing.Manage")]public async Task<IActionResult>Create(CalendarRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Title)||r.StartsAt==default)return Invalid("event","Título e início são obrigatórios.");var id=Guid.NewGuid();await Data.WriteAsync("insert into barber.marketing_calendar_events(id,tenant_id,branch_id,title,description,event_type,starts_at,ends_at,campaign_id,status,created_by) values(@id,@tenant,@branch,@title,@description,@type,@starts,@ends,@campaign,'Active',@user)","Marketing.CalendarCreated","marketing_calendar_events",id,null,c=>{Add(c,"title",r.Title.Trim());Add(c,"description",r.Description?.Trim());Add(c,"type",r.EventType);Add(c,"starts",r.StartsAt);Add(c,"ends",r.EndsAt);Add(c,"campaign",r.CampaignId);Add(c,"user",Current.UserId);},ct);return Created($"/api/marketing/calendar/{id}",Envelope(new{id}));}}

[Route("api/mobile/marketing")]
public sealed class MarketingMobileController(TeamDataService d,ICurrentUserContext u):MarketingControllerBase(d,u)
{
 [HttpGet("offers")]public async Task<IActionResult>Offers(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync(@"select l.slug,l.title,l.subtitle,l.cta_label,l.cta_type,l.cta_url,l.ends_at from barber.marketing_landing_pages l where l.tenant_id=@tenant and l.branch_id=@branch and l.status='Active' and(l.starts_at is null or l.starts_at<=now())and(l.ends_at is null or l.ends_at>=now()) order by l.created_at desc limit 30",null,ct)));
 [HttpGet("campaigns")]public async Task<IActionResult>Campaigns(CancellationToken ct)=>Ok(Envelope(await Data.QueryAsync("select name,objective,channel_type,starts_at,ends_at from barber.marketing_campaigns where tenant_id=@tenant and branch_id=@branch and status in('Scheduled','Running') order by starts_at nulls last",null,ct)));
 [HttpPost("track")]public async Task<IActionResult>Track(MobileTrackRequest r,CancellationToken ct){if(r.LandingPageId==Guid.Empty||r.EventType is not("View" or "Click" or "BookingStarted" or "BookingCompleted" or "OrderCreated" or "CouponRedeemed"))return Invalid("event","Selecione uma oferta e um evento válido.");var id=Guid.NewGuid();await Data.WriteAsync("insert into barber.marketing_tracking_events(id,tenant_id,branch_id,landing_page_id,event_type,source,metadata_json) select @id,@tenant,@branch,id,@event,'Mobile',@metadata::jsonb from barber.marketing_landing_pages where id=@landing and tenant_id=@tenant and branch_id=@branch and status='Active'","Marketing.MobileTracked","marketing_tracking_events",id,null,c=>{Add(c,"landing",r.LandingPageId);Add(c,"event",r.EventType);Add(c,"metadata",r.Metadata.ValueKind is JsonValueKind.Undefined?"{}":r.Metadata.GetRawText());},ct);return Accepted(Envelope(new{id}));}
}

[ApiController,AllowAnonymous,Route("api/marketing/public")]
public sealed class MarketingTrackingController(IConfiguration config):ControllerBase
{
 async Task<NpgsqlConnection> Open(CancellationToken ct){var c=new NpgsqlConnection(config.GetConnectionString("DefaultConnection"));await c.OpenAsync(ct);return c;}
 [HttpGet("landing/{slug}")]public async Task<IActionResult>Landing(string slug,CancellationToken ct){await using var c=await Open(ct);await using var q=new NpgsqlCommand("select id,tenant_id,branch_id,slug,title,subtitle,body,cta_label,cta_type,cta_url,ends_at from barber.marketing_landing_pages where slug=@slug and status='Active' and deleted_at is null and(starts_at is null or starts_at<=now())and(ends_at is null or ends_at>=now()) limit 1",c);q.Parameters.AddWithValue("slug",slug);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return NotFound(new{title="Oferta indisponível",traceId=HttpContext.TraceIdentifier});return Ok(new{success=true,data=new{slug=r.GetString(3),title=r.GetString(4),subtitle=r.IsDBNull(5)?null:r.GetString(5),body=r.IsDBNull(6)?null:r.GetString(6),ctaLabel=r.IsDBNull(7)?null:r.GetString(7),ctaType=r.GetString(8),ctaUrl=r.IsDBNull(9)?null:r.GetString(9)}});}
 [HttpGet("go/{slug}")]public async Task<IActionResult>Go(string slug,CancellationToken ct){await using var c=await Open(ct);await using var tx=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand("select id,tenant_id,branch_id,campaign_id,landing_page_id,destination_url from barber.marketing_promo_links where public_slug=@slug and status='Active' and(valid_from is null or valid_from<=now())and(valid_until is null or valid_until>=now()) for update",c,tx);q.Parameters.AddWithValue("slug",slug);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return NotFound();var id=r.GetGuid(0);var tenant=r.GetGuid(1);var branch=r.GetGuid(2);var campaign=r.IsDBNull(3)?(Guid?)null:r.GetGuid(3);var landing=r.IsDBNull(4)?(Guid?)null:r.GetGuid(4);var url=r.GetString(5);await r.CloseAsync();await using var ins=new NpgsqlCommand("insert into barber.marketing_tracking_events(id,tenant_id,branch_id,campaign_id,promo_link_id,landing_page_id,event_type,source,ip_address,user_agent)values(gen_random_uuid(),@tenant,@branch,@campaign,@link,@landing,'Click','PublicWeb',@ip,@ua)",c,tx);ins.Parameters.AddWithValue("tenant",tenant);ins.Parameters.AddWithValue("branch",branch);ins.Parameters.AddWithValue("campaign",(object?)campaign??DBNull.Value);ins.Parameters.AddWithValue("link",id);ins.Parameters.AddWithValue("landing",(object?)landing??DBNull.Value);ins.Parameters.AddWithValue("ip",(object?)HttpContext.Connection.RemoteIpAddress??DBNull.Value);ins.Parameters.AddWithValue("ua",Request.Headers.UserAgent.ToString());await ins.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);return Redirect(url);}
 [HttpPost("track")]public async Task<IActionResult>Track(PublicTrackRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Slug)||r.EventType is not("View" or "BookingStarted" or "BookingCompleted" or "OrderCreated" or "CouponRedeemed" or "PortalLogin" or "ReviewSubmitted"))return BadRequest(new{title="Evento inválido",traceId=HttpContext.TraceIdentifier});await using var c=await Open(ct);await using var q=new NpgsqlCommand(@"insert into barber.marketing_tracking_events(id,tenant_id,branch_id,landing_page_id,event_type,source,metadata_json,ip_address,user_agent) select gen_random_uuid(),tenant_id,branch_id,id,@event,@source,@metadata::jsonb,@ip,@ua from barber.marketing_landing_pages where slug=@slug and status='Active' and deleted_at is null",c);q.Parameters.AddWithValue("event",r.EventType);q.Parameters.AddWithValue("source",r.Source??"PublicWeb");q.Parameters.AddWithValue("metadata",r.Metadata.ValueKind is JsonValueKind.Undefined?"{}":r.Metadata.GetRawText());q.Parameters.AddWithValue("ip",(object?)HttpContext.Connection.RemoteIpAddress??DBNull.Value);q.Parameters.AddWithValue("ua",Request.Headers.UserAgent.ToString());q.Parameters.AddWithValue("slug",r.Slug);if(await q.ExecuteNonQueryAsync(ct)==0)return NotFound();return Accepted(new{success=true});}
}

public sealed record SegmentRequest(string Name,string SegmentKey,string SegmentType,JsonElement Criteria,string? Description,string Status="Draft");
public sealed record CampaignRequest(string Name,string Objective,Guid SegmentId,string ChannelType,Guid? TemplateId,Guid? CouponId,Guid? LandingPageId,DateTimeOffset? StartsAt,DateTimeOffset? EndsAt);
public sealed record ReasonRequest(string Reason); public sealed record JourneyRequest(string Name,string TriggerType,JsonElement Conditions,JsonElement Steps,int DeduplicationHours=168);
public sealed record LandingRequest(string Slug,string Title,string? Subtitle,string? Body,string? CtaLabel,string CtaType,string? CtaUrl,DateTimeOffset? StartsAt,DateTimeOffset? EndsAt);
public sealed record LinkRequest(string PublicSlug,Guid? CampaignId,Guid? LandingPageId,string DestinationType,string DestinationUrl,DateTimeOffset? ValidFrom,DateTimeOffset? ValidUntil);
public sealed record QrRequest(string Name,Guid PromoLinkId); public sealed record VariantRequest(string VariantKey,string Label,int AllocationPercent,Guid TemplateId);
public sealed record ExperimentRequest(Guid CampaignId,string Name,string MetricKey,List<VariantRequest> Variants,DateTimeOffset? StartsAt,DateTimeOffset? EndsAt);
public sealed record PublicTrackRequest(string Slug,string EventType,string? Source,JsonElement Metadata);
public sealed record CalendarRequest(string Title,string? Description,string EventType,DateTimeOffset StartsAt,DateTimeOffset? EndsAt,Guid? CampaignId);
public sealed record MobileTrackRequest(Guid LandingPageId,string EventType,JsonElement Metadata);
