using System.Data.Common;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BarberSync.Api.Security;
using BarberSync.Api.Services.Team;
using BarberSync.Application.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BarberSync.Api.Controllers;

[ApiController, Authorize, Route("api/partners")]
public sealed class PartnersController(TeamDataService data, ICurrentUserContext current) : ControllerBase
{
 static readonly HashSet<string> PartnerTypes=["Influencer","LocalBusiness","Supplier","ExternalProfessional","Agreement","Clinic","Gym","Hotel","Corporate","Marketplace","Other"];
 static void Add(DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
 object Out(object value)=>new{success=true,data=value,traceId=HttpContext.TraceIdentifier};
 IActionResult Invalid(string field,string detail)=>Problem(statusCode:422,title:"Dados de parceiros inválidos",detail:detail,extensions:new Dictionary<string,object?>{{"traceId",HttpContext.TraceIdentifier},{"errors",new Dictionary<string,string[]>{{field,[detail]}}}});
 [HttpGet("dashboard"),RequirePermission("Partners.Read")] public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(Out((await data.QueryAsync(@"select count(*) filter(where status='Active') active_partners,(select count(*) from barber.partner_referrals where tenant_id=@tenant and branch_id=@branch and created_at>=date_trunc('month',now())) leads,(select coalesce(sum(commission_amount),0) from barber.partner_commissions where tenant_id=@tenant and branch_id=@branch and status='Payable') commission_payable,(select coalesce(sum(base_amount),0) from barber.partner_commissions where tenant_id=@tenant and branch_id=@branch and status in('Payable','Paid')) attributed_revenue from barber.partner_profiles where tenant_id=@tenant and branch_id=@branch and deleted_at is null",null,ct)).Single()));
 [HttpGet("profiles"),RequirePermission("Partners.Read")] public async Task<IActionResult> Profiles(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select * from barber.partner_profiles where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by updated_at desc",null,ct)));
 [HttpPost("profiles"),RequirePermission("Partners.Manage")] public async Task<IActionResult> CreateProfile(ProfileRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||!PartnerTypes.Contains(r.PartnerType)||!Slug(r.Slug))return Invalid("profile","Informe nome, tipo e slug público seguro.");var id=Guid.NewGuid();await data.WriteAsync("insert into barber.partner_profiles(id,tenant_id,branch_id,name,partner_type,document,email,phone,slug,status,public_profile_enabled,notes,created_by) values(@id,@tenant,@branch,@name,@type,@document,@email,@phone,@slug,'Draft',@public,@notes,@user)","PartnerCreated","partner_profiles",id,null,c=>{Add(c,"name",r.Name.Trim());Add(c,"type",r.PartnerType);Add(c,"document",r.Document);Add(c,"email",r.Email);Add(c,"phone",r.Phone);Add(c,"slug",r.Slug);Add(c,"public",r.PublicProfileEnabled);Add(c,"notes",r.Notes);Add(c,"user",current.UserId);},ct);return Created($"/api/partners/profiles/{id}",Out(new{id,status="Draft"}));}
 [HttpPut("profiles/{id:guid}"),RequirePermission("Partners.Manage")] public async Task<IActionResult> UpdateProfile(Guid id,ProfileRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||!PartnerTypes.Contains(r.PartnerType)||!Slug(r.Slug))return Invalid("profile","Informe nome, tipo e slug público seguro.");await data.WriteAsync("update barber.partner_profiles set name=@name,partner_type=@type,document=@document,email=@email,phone=@phone,slug=@slug,public_profile_enabled=@public,notes=@notes,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status<>'Archived'","PartnerUpdated","partner_profiles",id,null,c=>{Add(c,"name",r.Name.Trim());Add(c,"type",r.PartnerType);Add(c,"document",r.Document);Add(c,"email",r.Email);Add(c,"phone",r.Phone);Add(c,"slug",r.Slug);Add(c,"public",r.PublicProfileEnabled);Add(c,"notes",r.Notes);},ct);return Ok(Out(new{id}));}
 [HttpPost("profiles/{id:guid}/activate"),RequirePermission("Partners.Manage")] public Task<IActionResult> Activate(Guid id,PartnerReasonRequest r,CancellationToken ct)=>ProfileState(id,"Active",r,ct);
 [HttpPost("profiles/{id:guid}/suspend"),RequirePermission("Partners.Manage")] public Task<IActionResult> Suspend(Guid id,PartnerReasonRequest r,CancellationToken ct)=>ProfileState(id,"Suspended",r,ct);
 [HttpPost("profiles/{id:guid}/archive"),RequirePermission("Partners.Manage")] public Task<IActionResult> Archive(Guid id,PartnerReasonRequest r,CancellationToken ct)=>ProfileState(id,"Archived",r,ct);
 async Task<IActionResult> ProfileState(Guid id,string status,PartnerReasonRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return Invalid("reason","A alteração de status exige motivo.");await data.WriteAsync("update barber.partner_profiles set status=@status,status_reason=@reason,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and deleted_at is null","PartnerStatusChanged","partner_profiles",id,r.Reason,c=>{Add(c,"status",status);Add(c,"reason",r.Reason.Trim());},ct);return Ok(Out(new{id,status}));}
 [HttpGet("affiliates"),RequirePermission("Partners.Read")] public async Task<IActionResult> Affiliates(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select a.id,a.partner_id,p.name partner_name,a.display_code_masked,a.public_slug,a.status,a.starts_at,a.ends_at from barber.partner_affiliates a join barber.partner_profiles p on p.id=a.partner_id where a.tenant_id=@tenant and a.branch_id=@branch order by a.created_at desc",null,ct)));
 [HttpPost("affiliates"),RequirePermission("Partners.Affiliates.Manage")] public async Task<IActionResult> Affiliate(AffiliateRequest r,CancellationToken ct){if(r.PartnerId==Guid.Empty||!Slug(r.PublicSlug))return Invalid("affiliate","Selecione um parceiro e informe slug seguro.");var id=Guid.NewGuid();var code=Convert.ToHexString(RandomNumberGenerator.GetBytes(24));var hash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(code))).ToLowerInvariant();await data.WriteAsync("insert into barber.partner_affiliates(id,tenant_id,branch_id,partner_id,affiliate_code_hash,display_code_masked,public_slug,status,starts_at,ends_at,created_by) select @newid,@tenant,@branch,id,@hash,@masked,@slug,'Active',@starts,@ends,@user from barber.partner_profiles where id=@partner and tenant_id=@tenant and branch_id=@branch and status='Active'","PartnerAffiliateCreated","partner_affiliates",id,null,c=>{Add(c,"newid",id);Add(c,"partner",r.PartnerId);Add(c,"hash",hash);Add(c,"masked",code[..4]+"••••");Add(c,"slug",r.PublicSlug);Add(c,"starts",r.StartsAt);Add(c,"ends",r.EndsAt);Add(c,"user",current.UserId);},ct);return Created($"/api/partners/affiliates/{id}",Out(new{id,r.PublicSlug}));}
 [HttpGet("links"),RequirePermission("Partners.Read")] public async Task<IActionResult> Links(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select l.*,p.name partner_name from barber.partner_links l join barber.partner_profiles p on p.id=l.partner_id where l.tenant_id=@tenant and l.branch_id=@branch order by l.created_at desc",null,ct)));
 [HttpPost("links"),RequirePermission("Partners.Affiliates.Manage")] public async Task<IActionResult> Link(PartnerLinkRequest r,CancellationToken ct){if(r.PartnerId==Guid.Empty||!Slug(r.PublicSlug)||!Uri.TryCreate(r.DestinationUrl,UriKind.RelativeOrAbsolute,out _))return Invalid("link","Selecione parceiro, slug e destino real.");var id=Guid.NewGuid();await data.WriteAsync("insert into barber.partner_links(id,tenant_id,branch_id,partner_id,affiliate_id,public_slug,destination_type,destination_url,status,valid_from,valid_until,created_by) select @newid,@tenant,@branch,id,@affiliate,@slug,@type,@url,'Active',@from,@until,@user from barber.partner_profiles where id=@partner and tenant_id=@tenant and branch_id=@branch and status='Active'","PartnerLinkCreated","partner_links",id,null,c=>{Add(c,"newid",id);Add(c,"partner",r.PartnerId);Add(c,"affiliate",r.AffiliateId);Add(c,"slug",r.PublicSlug);Add(c,"type",r.DestinationType);Add(c,"url",r.DestinationUrl);Add(c,"from",r.ValidFrom);Add(c,"until",r.ValidUntil);Add(c,"user",current.UserId);},ct);return Created($"/api/partners/links/{id}",Out(new{id}));}
 [HttpPost("links/{id:guid}/deactivate"),RequirePermission("Partners.Affiliates.Manage")] public async Task<IActionResult> DeactivateLink(Guid id,CancellationToken ct){await data.WriteAsync("update barber.partner_links set status='Inactive',updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Active'","PartnerLinkDeactivated","partner_links",id,null,null,ct);return Ok(Out(new{id,status="Inactive"}));}
 [HttpGet("referrals"),RequirePermission("Partners.Read")] public async Task<IActionResult> Referrals(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select r.*,p.name partner_name from barber.partner_referrals r join barber.partner_profiles p on p.id=r.partner_id where r.tenant_id=@tenant and r.branch_id=@branch order by r.created_at desc",null,ct)));
 [HttpPost("referrals"),RequirePermission("Partners.Referrals.Manage")] public async Task<IActionResult> Referral(ReferralRequest r,CancellationToken ct){if(r.PartnerId==Guid.Empty||string.IsNullOrWhiteSpace(r.LeadName)||string.IsNullOrWhiteSpace(r.LeadEmail)&&string.IsNullOrWhiteSpace(r.LeadPhone))return Invalid("referral","Selecione parceiro e informe nome e um contato.");var id=Guid.NewGuid();await data.WriteAsync(@"insert into barber.partner_referrals(id,tenant_id,branch_id,partner_id,affiliate_id,lead_name,lead_email,lead_phone,source_type,source_id,status) select @newid,@tenant,@branch,@partner,@affiliate,@name,@email,@phone,@source,@sourceid,'Captured' where exists(select 1 from barber.partner_profiles where id=@partner and tenant_id=@tenant and branch_id=@branch and status='Active') and not exists(select 1 from barber.partner_referrals where tenant_id=@tenant and branch_id=@branch and partner_id=@partner and source_type=@source and created_at>now()-interval '2 hours' and (nullif(@email,'') is not null and lower(lead_email)=lower(@email) or nullif(@phone,'') is not null and lead_phone=@phone))","PartnerReferralCaptured","partner_referrals",id,null,c=>{Add(c,"newid",id);Add(c,"partner",r.PartnerId);Add(c,"affiliate",r.AffiliateId);Add(c,"name",r.LeadName.Trim());Add(c,"email",r.LeadEmail);Add(c,"phone",r.LeadPhone);Add(c,"source",r.SourceType);Add(c,"sourceid",r.SourceId);},ct);return Created($"/api/partners/referrals/{id}",Out(new{id,status="Captured"}));}
 [HttpPost("referrals/{id:guid}/qualify"),RequirePermission("Partners.Referrals.Manage")] public Task<IActionResult> Qualify(Guid id,CancellationToken ct)=>ReferralState(id,"Qualified",null,ct);
 [HttpPost("referrals/{id:guid}/mark-lost"),RequirePermission("Partners.Referrals.Manage")] public Task<IActionResult> Lost(Guid id,PartnerReasonRequest r,CancellationToken ct)=>string.IsNullOrWhiteSpace(r.Reason)?Task.FromResult(Invalid("reason","A perda exige motivo.")):ReferralState(id,"Lost",r.Reason,ct);
 async Task<IActionResult> ReferralState(Guid id,string status,string? reason,CancellationToken ct){await data.WriteAsync("update barber.partner_referrals set status=@status,lost_reason=@reason,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in('Captured','Qualified','Booked')","PartnerReferralUpdated","partner_referrals",id,reason,c=>{Add(c,"status",status);Add(c,"reason",reason);},ct);return Ok(Out(new{id,status}));}
 [HttpGet("commission-rules"),RequirePermission("Partners.Read")] public async Task<IActionResult> Rules(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select r.*,p.name partner_name from barber.partner_commission_rules r join barber.partner_profiles p on p.id=r.partner_id where r.tenant_id=@tenant and r.branch_id=@branch and r.deleted_at is null order by r.created_at desc",null,ct)));
 [HttpPost("commission-rules"),RequirePermission("Partners.Commissions.Manage")] public async Task<IActionResult> Rule(RuleRequest r,CancellationToken ct){if(r.PartnerId==Guid.Empty||string.IsNullOrWhiteSpace(r.Name)||r.CommissionType=="Percentage"&&(r.Percent is<=0 or>100)||r.CommissionType=="FixedAmount"&&r.Amount<=0)return Invalid("rule","Configure parceiro, gatilho e valor válido.");var id=Guid.NewGuid();await data.WriteAsync("insert into barber.partner_commission_rules(id,tenant_id,branch_id,partner_id,affiliate_id,name,trigger_type,commission_type,amount,percent,max_amount,status,created_by) values(@id,@tenant,@branch,@partner,@affiliate,@name,@trigger,@type,@amount,@percent,@max,'Active',@user)","PartnerCommissionRuleCreated","partner_commission_rules",id,null,c=>{Add(c,"partner",r.PartnerId);Add(c,"affiliate",r.AffiliateId);Add(c,"name",r.Name.Trim());Add(c,"trigger",r.TriggerType);Add(c,"type",r.CommissionType);Add(c,"amount",r.Amount);Add(c,"percent",r.Percent);Add(c,"max",r.MaxAmount);Add(c,"user",current.UserId);},ct);return Created($"/api/partners/commission-rules/{id}",Out(new{id}));}
 [HttpGet("commissions"),RequirePermission("Partners.Read")] public async Task<IActionResult> Commissions(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select c.*,p.name partner_name,r.name rule_name from barber.partner_commissions c join barber.partner_profiles p on p.id=c.partner_id join barber.partner_commission_rules r on r.id=c.commission_rule_id where c.tenant_id=@tenant and c.branch_id=@branch order by c.created_at desc",null,ct)));
 [HttpPost("commissions/{id:guid}/mark-payable"),RequirePermission("Partners.Commissions.Manage")] public async Task<IActionResult> Payable(Guid id,CancellationToken ct){await data.WriteAsync(@"update barber.partner_commissions c set status='Payable',payable_at=now(),updated_at=now() where c.id=@id and c.tenant_id=@tenant and c.branch_id=@branch and c.status='Pending' and exists(select 1 from barber.partner_profiles p where p.id=c.partner_id and p.status='Active') and ((c.source_type in('OnlineSale','ServiceOrder','Membership') and exists(select 1 from barber.payments p where p.id=c.source_id and p.status in('Paid','Confirmed'))) or c.source_type='Appointment' and exists(select 1 from barber.appointments a where a.id=c.source_id and a.status='Completed') or c.source_type='Lead' and exists(select 1 from barber.partner_referrals r where r.id=c.referral_id and r.status in('Qualified','Booked','Converted')))","PartnerCommissionPayable","partner_commissions",id,null,null,ct);return Ok(Out(new{id,status="Payable"}));}
 [HttpPost("commissions/{id:guid}/reverse"),RequirePermission("Partners.Commissions.Manage")] public async Task<IActionResult> Reverse(Guid id,PartnerReasonRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))return Invalid("reason","O estorno exige motivo.");await data.WriteAsync("update barber.partner_commissions set status='Reversed',reason=@reason,reversed_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in('Payable','Paid')","PartnerCommissionReversed","partner_commissions",id,r.Reason,c=>Add(c,"reason",r.Reason.Trim()),ct);return Ok(Out(new{id,status="Reversed"}));}
 [HttpGet("payouts"),RequirePermission("Partners.Read")] public async Task<IActionResult> Payouts(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select x.*,p.name partner_name from barber.partner_commission_payouts x join barber.partner_profiles p on p.id=x.partner_id where x.tenant_id=@tenant and x.branch_id=@branch order by x.created_at desc",null,ct)));
 [HttpPost("payouts"),RequirePermission("Partners.Payouts.Manage")] public async Task<IActionResult> Payout(PartnerPayoutRequest r,CancellationToken ct){if(r.PartnerId==Guid.Empty||r.PeriodStart>r.PeriodEnd)return Invalid("payout","Selecione parceiro e período válido.");var id=Guid.NewGuid();await data.WriteAsync(@"insert into barber.partner_commission_payouts(id,tenant_id,branch_id,partner_id,status,period_start,period_end,total_amount,created_by) select @newid,@tenant,@branch,@partner,'Draft',@start,@end,coalesce(sum(commission_amount),0),@user from barber.partner_commissions where tenant_id=@tenant and branch_id=@branch and partner_id=@partner and status='Payable' and created_at::date between @start and @end having coalesce(sum(commission_amount),0)>0","PartnerPayoutCreated","partner_commission_payouts",id,null,c=>{Add(c,"newid",id);Add(c,"partner",r.PartnerId);Add(c,"start",r.PeriodStart);Add(c,"end",r.PeriodEnd);Add(c,"user",current.UserId);},ct);return Created($"/api/partners/payouts/{id}",Out(new{id,status="Draft"}));}
 [HttpPost("payouts/{id:guid}/approve"),RequirePermission("Partners.Payouts.Manage")] public Task<IActionResult> ApprovePayout(Guid id,CancellationToken ct)=>PayoutState(id,"Approved",null,null,ct);
 [HttpPost("payouts/{id:guid}/mark-paid"),RequirePermission("Partners.Payouts.Manage")] public Task<IActionResult> PaidPayout(Guid id,PartnerPaymentRequest r,CancellationToken ct)=>r.PaymentId==Guid.Empty?Task.FromResult(Invalid("payment","Selecione um pagamento confirmado.")):PayoutState(id,"Paid",r.PaymentId,null,ct);
 [HttpPost("payouts/{id:guid}/cancel"),RequirePermission("Partners.Payouts.Manage")] public Task<IActionResult> CancelPayout(Guid id,PartnerReasonRequest r,CancellationToken ct)=>string.IsNullOrWhiteSpace(r.Reason)?Task.FromResult(Invalid("reason","O cancelamento exige motivo.")):PayoutState(id,"Cancelled",null,r.Reason,ct);
 async Task<IActionResult> PayoutState(Guid id,string status,Guid? payment,string? reason,CancellationToken ct){await data.WriteAsync(@"update barber.partner_commission_payouts x set status=@status,payment_id=coalesce(@payment,payment_id),approved_by=case when @status='Approved' then @user else approved_by end,approved_at=case when @status='Approved' then now() else approved_at end,paid_by=case when @status='Paid' then @user else paid_by end,paid_at=case when @status='Paid' then now() else paid_at end,cancelled_at=case when @status='Cancelled' then now() else cancelled_at end,cancel_reason=@reason where id=@id and tenant_id=@tenant and branch_id=@branch and ((@status='Approved' and status in('Draft','PendingApproval')) or (@status='Paid' and status='Approved' and exists(select 1 from barber.payments p where p.id=@payment and p.status in('Paid','Confirmed'))) or (@status='Cancelled' and status<>'Paid'))","PartnerPayoutStatusChanged","partner_commission_payouts",id,reason,c=>{Add(c,"status",status);Add(c,"payment",payment);Add(c,"user",current.UserId);Add(c,"reason",reason);},ct);return Ok(Out(new{id,status}));}
 [HttpGet("contracts"),RequirePermission("Partners.Read")] public async Task<IActionResult> Contracts(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select c.*,p.name partner_name from barber.partner_contracts c join barber.partner_profiles p on p.id=c.partner_id where c.tenant_id=@tenant and c.branch_id=@branch order by c.created_at desc",null,ct)));
 [HttpPost("contracts"),RequirePermission("Partners.Contracts.Manage")] public async Task<IActionResult> Contract(PartnerContractRequest r,CancellationToken ct){if(r.PartnerId==Guid.Empty||string.IsNullOrWhiteSpace(r.Title)||(r.StartsAt.HasValue&&r.EndsAt.HasValue&&r.EndsAt.Value<r.StartsAt.Value))return Invalid("contract","Selecione parceiro, título e vigência coerente.");var id=Guid.NewGuid();await data.WriteAsync("insert into barber.partner_contracts(id,tenant_id,branch_id,partner_id,title,contract_type,starts_at,ends_at,terms_json,status,created_by) values(@id,@tenant,@branch,@partner,@title,@type,@starts,@ends,@terms::jsonb,'Draft',@user)","PartnerContractCreated","partner_contracts",id,null,c=>{Add(c,"partner",r.PartnerId);Add(c,"title",r.Title.Trim());Add(c,"type",r.ContractType);Add(c,"starts",r.StartsAt);Add(c,"ends",r.EndsAt);Add(c,"terms",r.Terms.GetRawText());Add(c,"user",current.UserId);},ct);return Created($"/api/partners/contracts/{id}",Out(new{id}));}
 [HttpGet("marketplace-items"),RequirePermission("Partners.Read")] public async Task<IActionResult> Items(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select * from barber.partner_marketplace_items where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by sort_order,title",null,ct)));
 [HttpPost("marketplace-items"),RequirePermission("Partners.Marketplace.Manage")] public async Task<IActionResult> Item(PartnerItemRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Title)||r.PublicPrice<0)return Invalid("item","Selecione o item e informe título/preço público válido.");var id=Guid.NewGuid();await data.WriteAsync("insert into barber.partner_marketplace_items(id,tenant_id,branch_id,partner_id,item_type,service_id,product_id,package_id,combo_id,club_plan_id,landing_page_id,title,description,public_price,status,sort_order) values(@id,@tenant,@branch,@partner,@type,@service,@product,@package,@combo,@club,@landing,@title,@description,@price,'Draft',@sort)","PartnerMarketplaceItemCreated","partner_marketplace_items",id,null,c=>{Add(c,"partner",r.PartnerId);Add(c,"type",r.ItemType);Add(c,"service",r.ServiceId);Add(c,"product",r.ProductId);Add(c,"package",r.PackageId);Add(c,"combo",r.ComboId);Add(c,"club",r.ClubPlanId);Add(c,"landing",r.LandingPageId);Add(c,"title",r.Title.Trim());Add(c,"description",r.Description);Add(c,"price",r.PublicPrice);Add(c,"sort",r.SortOrder);},ct);return Created($"/api/partners/marketplace-items/{id}",Out(new{id}));}
 [HttpGet("supplier-terms"),RequirePermission("Partners.Read")] public async Task<IActionResult> Terms(CancellationToken ct)=>Ok(Out(await data.QueryAsync("select t.*,p.name partner_name,s.name supplier_name,i.name product_name from barber.partner_supplier_terms t join barber.partner_profiles p on p.id=t.partner_id join barber.suppliers s on s.id=t.supplier_id join barber.products i on i.id=t.product_id where t.tenant_id=@tenant and t.branch_id=@branch and t.deleted_at is null",null,ct)));
 [HttpPost("supplier-terms"),RequirePermission("Partners.Manage")] public async Task<IActionResult> Term(SupplierTermRequest r,CancellationToken ct){if(r.PartnerId==Guid.Empty||r.SupplierId==Guid.Empty||r.ProductId==Guid.Empty||r.NegotiatedPrice<0||r.MinimumOrderQuantity<=0)return Invalid("supplierTerm","Selecione parceiro, fornecedor, produto e condições válidas.");var id=Guid.NewGuid();await data.WriteAsync("insert into barber.partner_supplier_terms(id,tenant_id,branch_id,partner_id,supplier_id,product_id,negotiated_price,lead_time_days,minimum_order_quantity,status,created_by) values(@id,@tenant,@branch,@partner,@supplier,@product,@price,@lead,@moq,'Active',@user)","PartnerSupplierTermCreated","partner_supplier_terms",id,null,c=>{Add(c,"partner",r.PartnerId);Add(c,"supplier",r.SupplierId);Add(c,"product",r.ProductId);Add(c,"price",r.NegotiatedPrice);Add(c,"lead",r.LeadTimeDays);Add(c,"moq",r.MinimumOrderQuantity);Add(c,"user",current.UserId);},ct);return Created($"/api/partners/supplier-terms/{id}",Out(new{id}));}
 [HttpGet("filter-options"),RequirePermission("Partners.Read")] public async Task<IActionResult> Options(CancellationToken ct)=>Ok(Out(new{partners=await data.QueryAsync("select id,name from barber.partner_profiles where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null order by name",null,ct),affiliates=await data.QueryAsync("select id,public_slug name from barber.partner_affiliates where tenant_id=@tenant and branch_id=@branch and status='Active' order by public_slug",null,ct),services=await data.QueryAsync("select id,name from barber.services where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by name",null,ct),products=await data.QueryAsync("select id,name from barber.products where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by name",null,ct),suppliers=await data.QueryAsync("select id,name from barber.suppliers where tenant_id=@tenant and branch_id=@branch and status='Active' order by name",null,ct),payments=await data.QueryAsync("select id,concat(method,' · ',amount,' · ',created_at) name from barber.payments where tenant_id=@tenant and branch_id=@branch and status in('Paid','Confirmed') order by created_at desc limit 100",null,ct)}));
 [HttpGet("reports/export"),RequirePermission("Partners.Reports.Export")] public async Task<IActionResult> Export(CancellationToken ct){var rows=await data.QueryAsync("select p.name,c.status,c.source_type,c.base_amount,c.commission_amount,c.created_at from barber.partner_commissions c join barber.partner_profiles p on p.id=c.partner_id where c.tenant_id=@tenant and c.branch_id=@branch order by c.created_at desc",null,ct);var csv=new StringBuilder("parceiro;status;origem;base;comissao;data\r\n");foreach(var x in rows)csv.AppendLine(string.Join(';',x.Values.Select(v=>$"\"{Convert.ToString(v)?.Replace("\"","\"\"")}\"")));return File(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv.ToString())).ToArray(),"text/csv",$"parceiros-{DateTime.UtcNow:yyyyMMdd}.csv");}
 static bool Slug(string? value)=>System.Text.RegularExpressions.Regex.IsMatch(value??"","^[a-z0-9]+(?:-[a-z0-9]+)*$");
}

[ApiController, AllowAnonymous, Route("api/partners/public")]
public sealed class PartnerPublicController(TeamDataService data):ControllerBase
{
 static void Add(DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
 [HttpGet("marketplace")] public async Task<IActionResult> Marketplace(CancellationToken ct)=>Ok(new{success=true,data=await data.QueryAsync("select i.item_type,i.title,i.description,i.public_price,p.name partner_name,p.slug partner_slug from barber.partner_marketplace_items i left join barber.partner_profiles p on p.id=i.partner_id where i.tenant_id=@tenant and i.branch_id=@branch and i.status='Active' and i.deleted_at is null and (p.id is null or p.status='Active' and p.public_profile_enabled) order by i.sort_order,i.title",null,ct),traceId=HttpContext.TraceIdentifier});
 [HttpGet("partner/{slug}")] public async Task<IActionResult> Partner(string slug,CancellationToken ct)=>Ok(new{success=true,data=(await data.QueryAsync("select name,partner_type,slug,notes from barber.partner_profiles where tenant_id=@tenant and branch_id=@branch and slug=@slug and status='Active' and public_profile_enabled and deleted_at is null",c=>Add(c,"slug",slug),ct)).SingleOrDefault(),traceId=HttpContext.TraceIdentifier});
 [HttpPost("track")] public async Task<IActionResult> Track(PartnerPublicTrackRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Slug)||string.IsNullOrWhiteSpace(r.EventType))return Problem(statusCode:422,title:"Tracking inválido",extensions:new Dictionary<string,object?>{{"traceId",HttpContext.TraceIdentifier}});var id=Guid.NewGuid();await data.WriteAsync(@"insert into barber.marketing_tracking_events(id,tenant_id,branch_id,promo_link_id,event_type,source,occurred_at,metadata_json) select @newid,l.tenant_id,l.branch_id,m.id,@event,'Partner',now(),jsonb_build_object('partnerLinkId',l.id,'partnerId',l.partner_id) from barber.partner_links l left join barber.marketing_promo_links m on m.tenant_id=l.tenant_id and m.branch_id=l.branch_id and m.public_slug=l.public_slug where l.public_slug=@slug and l.status='Active' and (l.valid_from is null or l.valid_from<=now()) and (l.valid_until is null or l.valid_until>=now()) and not exists(select 1 from barber.marketing_tracking_events e where e.tenant_id=l.tenant_id and e.branch_id=l.branch_id and e.event_type=@event and e.metadata_json->>'partnerLinkId'=l.id::text and e.created_at>now()-interval '5 minutes')","PartnerPublicTracked","marketing_tracking_events",id,null,c=>{Add(c,"newid",id);Add(c,"slug",r.Slug);Add(c,"event",r.EventType);},ct);return Accepted(new{success=true,traceId=HttpContext.TraceIdentifier});}
}
[ApiController, Authorize, Route("api/mobile/partners")]
public sealed class MobilePartnersController(TeamDataService data):ControllerBase
{
 [HttpGet("marketplace")] public Task<IActionResult> Marketplace(CancellationToken ct)=>Offers(ct);
 [HttpGet("offers")] public async Task<IActionResult> Offers(CancellationToken ct)=>Ok(new{success=true,data=await data.QueryAsync("select item_type,title,description,public_price from barber.partner_marketplace_items where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null order by sort_order,title",null,ct),sourceStatus="available",traceId=HttpContext.TraceIdentifier});
 [HttpPost("track")] public IActionResult Track()=>Problem(statusCode:501,title:"Tracking mobile requer atribuição pública válida",detail:"Envie o slug assinado pelo fluxo público; nenhum tracking foi simulado.",extensions:new Dictionary<string,object?>{{"traceId",HttpContext.TraceIdentifier}});
}
public sealed record ProfileRequest(string Name,string PartnerType,string Slug,string? Document,string? Email,string? Phone,bool PublicProfileEnabled,string? Notes);
public sealed record PartnerReasonRequest(string Reason); public sealed record PartnerPaymentRequest(Guid PaymentId);
public sealed record AffiliateRequest(Guid PartnerId,string PublicSlug,DateTimeOffset? StartsAt,DateTimeOffset? EndsAt);
public sealed record PartnerLinkRequest(Guid PartnerId,Guid? AffiliateId,string PublicSlug,string DestinationType,string DestinationUrl,DateTimeOffset? ValidFrom,DateTimeOffset? ValidUntil);
public sealed record ReferralRequest(Guid PartnerId,Guid? AffiliateId,string LeadName,string? LeadEmail,string? LeadPhone,string SourceType,Guid? SourceId);
public sealed record RuleRequest(Guid PartnerId,Guid? AffiliateId,string Name,string TriggerType,string CommissionType,decimal? Amount,decimal? Percent,decimal? MaxAmount);
public sealed record PartnerPayoutRequest(Guid PartnerId,DateOnly PeriodStart,DateOnly PeriodEnd);
public sealed record PartnerContractRequest(Guid PartnerId,string Title,string ContractType,DateOnly? StartsAt,DateOnly? EndsAt,JsonElement Terms);
public sealed record PartnerItemRequest(Guid? PartnerId,string ItemType,Guid? ServiceId,Guid? ProductId,Guid? PackageId,Guid? ComboId,Guid? ClubPlanId,Guid? LandingPageId,string Title,string? Description,decimal? PublicPrice,int SortOrder);
public sealed record SupplierTermRequest(Guid PartnerId,Guid SupplierId,Guid ProductId,decimal NegotiatedPrice,int LeadTimeDays,decimal MinimumOrderQuantity);
public sealed record PartnerPublicTrackRequest(string Slug,string EventType);
