using System.Data.Common;
using System.Globalization;
using System.Text;
using System.Security.Claims;
using BarberSync.Api.Security;
using BarberSync.Api.Services.Team;
using BarberSync.Application.Abstractions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BarberSync.Api.Controllers;

[ApiController, Authorize, Route("api/quality")]
public sealed class QualityController(TeamDataService data, ICurrentUserContext user) : ControllerBase
{
    private static readonly HashSet<string> CaseStatuses = ["Open", "InProgress", "WaitingClient", "Recovered", "Lost", "Cancelled"];
    private static readonly HashSet<string> CaseTypes = ["Detractor", "Complaint", "NoShow", "InactiveVip", "CancelledMembership", "Manual"];
    private static readonly HashSet<string> Severities = ["Low", "Medium", "High", "Critical"];
    private static readonly HashSet<string> FollowUpStatuses = ["Pending", "Done", "Overdue", "Cancelled", "Skipped"];

    [HttpGet("dashboard"), RequirePermission("Quality.Read")]
    public async Task<IActionResult> Dashboard([FromQuery] QualityFilter f, CancellationToken ct)
    {
        if (Validate(f) is { } invalid) return invalid;
        var rows = await data.QueryAsync(@"select count(*) reviews_count,coalesce(round(avg(rating),2),0) average_rating,
coalesce(round(100.0*(count(*) filter(where nps_score>=9)-count(*) filter(where nps_score<=6))/nullif(count(nps_score),0),1),0) nps_score,
count(*) filter(where nps_score>=9) promoters,count(*) filter(where nps_score between 7 and 8) neutrals,count(*) filter(where nps_score<=6) detractors,
(select count(*) from barber.quality_recovery_cases q where q.tenant_id=@tenant and q.branch_id=@branch and q.status in('Open','InProgress','WaitingClient')) recovery_open,
(select count(*) from barber.quality_recovery_cases q where q.tenant_id=@tenant and q.branch_id=@branch and q.status='Recovered') recovered,
(select count(*) from barber.quality_follow_up_queue q where q.tenant_id=@tenant and q.branch_id=@branch and q.status='Pending') follow_ups_pending,
(select count(*) from barber.quality_follow_up_queue q where q.tenant_id=@tenant and q.branch_id=@branch and (q.status='Overdue' or(q.status='Pending' and q.due_at<now()))) follow_ups_overdue
from barber.client_reviews where tenant_id=@tenant and branch_id=@branch and status in('Submitted','Hidden') and created_at::date between @from and @to", c => Bind(c, f), ct);
        return Ok(new { success=true, data=rows.Single(), sourceStatus="available", traceId=HttpContext.TraceIdentifier });
    }

    [HttpGet("reviews"), RequirePermission("Quality.Read")]
    public async Task<IActionResult> Reviews([FromQuery] QualityFilter f, CancellationToken ct) => Ok(new { success=true, data=await data.QueryAsync(@"select r.id,r.rating,r.nps_score,r.comment,r.status,r.submitted_at,r.hidden_reason,c.name client_name,p.name professional_name,s.name service_name from barber.client_reviews r join barber.clients c on c.id=r.client_id left join barber.professionals p on p.id=r.professional_id left join barber.appointments a on a.id=r.appointment_id left join barber.services s on s.id=a.service_id where r.tenant_id=@tenant and r.branch_id=@branch and r.created_at::date between @from and @to and(@professional is null or r.professional_id=@professional) and(@client is null or r.client_id=@client) and(@service is null or a.service_id=@service) order by r.created_at desc limit 500", c=>Bind(c,f),ct), traceId=HttpContext.TraceIdentifier });

    [HttpGet("nps"), RequirePermission("Quality.Read")]
    public async Task<IActionResult> Nps([FromQuery] QualityFilter f, CancellationToken ct) => Ok(new { success=true, data=await data.QueryAsync(@"select case when nps_score<=6 then 'Detractor' when nps_score<=8 then 'Neutral' else 'Promoter' end classification,count(*) responses,round(avg(nps_score),1) average from barber.client_reviews where tenant_id=@tenant and branch_id=@branch and nps_score is not null and created_at::date between @from and @to group by 1 order by 1",c=>Bind(c,f),ct), traceId=HttpContext.TraceIdentifier });

    [HttpGet("recovery-cases"), RequirePermission("Quality.Read")]
    public async Task<IActionResult> Cases(CancellationToken ct) => Ok(new { success=true,data=await data.QueryAsync("select q.*,c.name client_name,p.name professional_name,u.name assigned_name from barber.quality_recovery_cases q join barber.clients c on c.id=q.client_id left join barber.professionals p on p.id=q.professional_id left join barber.users u on u.id=q.assigned_to where q.tenant_id=@tenant and q.branch_id=@branch order by q.opened_at desc limit 300",null,ct) });

    [HttpPost("recovery-cases"), RequirePermission("Quality.Recovery.Manage")]
    public async Task<IActionResult> CreateCase(RecoveryCaseRequest r,CancellationToken ct)
    {
        if(r.ClientId==Guid.Empty||r.AssignedTo==Guid.Empty||!CaseTypes.Contains(r.CaseType)||!Severities.Contains(r.Severity)||string.IsNullOrWhiteSpace(r.Reason)||string.IsNullOrWhiteSpace(r.Summary)) return Invalid("case","Selecione cliente e responsável e informe tipo, severidade, motivo e resumo válidos.");
        var id=Guid.NewGuid(); await data.WriteAsync("insert into barber.quality_recovery_cases(id,tenant_id,branch_id,client_id,professional_id,appointment_id,service_order_id,review_id,support_request_id,case_type,severity,status,reason,summary,assigned_to,created_by) values(@id,@tenant,@branch,@client,@professional,@appointment,@order,@review,@support,@type,@severity,'Open',@reason,@summary,@assigned,@user)","QualityRecoveryCaseOpened","quality_recovery_cases",id,r.ClientId,c=>{Add(c,"client",r.ClientId);Add(c,"professional",r.ProfessionalId);Add(c,"appointment",r.AppointmentId);Add(c,"order",r.ServiceOrderId);Add(c,"review",r.ReviewId);Add(c,"support",r.SupportRequestId);Add(c,"type",r.CaseType);Add(c,"severity",r.Severity);Add(c,"reason",r.Reason.Trim());Add(c,"summary",r.Summary.Trim());Add(c,"assigned",r.AssignedTo);Add(c,"user",user.UserId);},ct); return Created($"/api/quality/recovery-cases/{id}",new{success=true,data=new{id},traceId=HttpContext.TraceIdentifier});
    }

    [HttpPut("recovery-cases/{id:guid}"), RequirePermission("Quality.Recovery.Manage")]
    public async Task<IActionResult> UpdateCase(Guid id,RecoveryUpdateRequest r,CancellationToken ct){if(!CaseStatuses.Contains(r.Status)||string.IsNullOrWhiteSpace(r.Reason))return Invalid("status","Informe status e motivo válidos.");await data.WriteAsync("update barber.quality_recovery_cases set status=@status,reason=@reason,summary=@summary,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","QualityRecoveryCaseUpdated","quality_recovery_cases",id,null,c=>{Add(c,"status",r.Status);Add(c,"reason",r.Reason.Trim());Add(c,"summary",r.Summary?.Trim());},ct);return Ok(new{success=true,traceId=HttpContext.TraceIdentifier});}
    [HttpPost("recovery-cases/{id:guid}/assign"), RequirePermission("Quality.Recovery.Manage")]
    public async Task<IActionResult> Assign(Guid id,AssignRequest r,CancellationToken ct){if(r.AssignedTo==Guid.Empty)return Invalid("assignedTo","Selecione um responsável.");await data.WriteAsync("update barber.quality_recovery_cases set assigned_to=@assigned,status=case when status='Open' then 'InProgress' else status end,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","QualityRecoveryCaseAssigned","quality_recovery_cases",id,null,c=>Add(c,"assigned",r.AssignedTo),ct);return Ok(new{success=true,traceId=HttpContext.TraceIdentifier});}
    [HttpPost("recovery-cases/{id:guid}/action"), RequirePermission("Quality.Recovery.Manage")]
    public async Task<IActionResult> Action(Guid id,RecoveryActionRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.ActionType)||string.IsNullOrWhiteSpace(r.Description))return Invalid("description","Selecione a ação e descreva o que foi realizado.");await data.WriteAsync("insert into barber.quality_recovery_actions(id,tenant_id,branch_id,recovery_case_id,action_type,description,appointment_id,created_by) select @newid,@tenant,@branch,id,@type,@description,@appointment,@user from barber.quality_recovery_cases where id=@id and tenant_id=@tenant and branch_id=@branch","QualityRecoveryActionRegistered","quality_recovery_actions",null,null,c=>{Add(c,"newid",Guid.NewGuid());Add(c,"type",r.ActionType);Add(c,"description",r.Description.Trim());Add(c,"appointment",r.AppointmentId);Add(c,"user",user.UserId);},ct);return Ok(new{success=true,traceId=HttpContext.TraceIdentifier});}
    [HttpPost("recovery-cases/{id:guid}/close"), RequirePermission("Quality.Recovery.Manage")]
    public async Task<IActionResult> Close(Guid id,CloseCaseRequest r,CancellationToken ct){if(r.Status is not("Recovered" or "Lost" or "Cancelled")||string.IsNullOrWhiteSpace(r.Reason)||(r.Status=="Recovered"&&string.IsNullOrWhiteSpace(r.ActionTaken)))return Invalid("reason","Informe o motivo; casos recuperados também exigem a ação tomada.");await data.WriteAsync("update barber.quality_recovery_cases set status=@status,closed_reason=@reason,closed_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch; insert into barber.quality_recovery_actions(id,tenant_id,branch_id,recovery_case_id,action_type,description,created_by) select gen_random_uuid(),@tenant,@branch,@id,'ManualNote',@action,@user where @action is not null","QualityRecoveryCaseClosed","quality_recovery_cases",id,null,c=>{Add(c,"status",r.Status);Add(c,"reason",r.Reason.Trim());Add(c,"action",r.ActionTaken?.Trim());Add(c,"user",user.UserId);},ct);return Ok(new{success=true,traceId=HttpContext.TraceIdentifier});}

    [HttpGet("follow-ups"),RequirePermission("Quality.Read")] public async Task<IActionResult> FollowUps(CancellationToken ct)=>Ok(new{success=true,data=await data.QueryAsync("select q.id,q.client_id,q.professional_id,q.source_type,q.source_id,q.rule_id,q.title,q.description,q.due_at,case when q.status='Pending' and q.due_at<now() then 'Overdue' else q.status end status,q.assigned_to,q.created_at,q.completed_at,c.name client_name,p.name professional_name from barber.quality_follow_up_queue q join barber.clients c on c.id=q.client_id left join barber.professionals p on p.id=q.professional_id where q.tenant_id=@tenant and q.branch_id=@branch order by q.due_at limit 500",null,ct)});
    [HttpPost("follow-ups"),RequirePermission("Quality.FollowUps.Manage")] public async Task<IActionResult> CreateFollowUp(FollowUpRequest r,CancellationToken ct){if(r.ClientId==Guid.Empty||r.DueAt==default||string.IsNullOrWhiteSpace(r.Title)||(r.SourceType=="Manual"&&r.ResponsibleId is null))return Invalid("followUp","Selecione cliente, prazo e responsável para o follow-up manual.");var id=Guid.NewGuid();await data.WriteAsync(@"insert into barber.quality_follow_up_queue(id,tenant_id,branch_id,client_id,professional_id,source_type,source_id,rule_id,title,description,due_at,status,assigned_to,created_by) select @newid,@tenant,@branch,@client,@professional,@source,@sourceid,@rule,@title,@description,@due,'Pending',@responsible,@user where not exists(select 1 from barber.quality_follow_up_queue where tenant_id=@tenant and branch_id=@branch and client_id=@client and source_type=@source and source_id is not distinct from @sourceid and status in('Pending','Overdue') and due_at between @due-interval '7 days' and @due+interval '7 days')","QualityFollowUpCreated","quality_follow_up_queue",id,r.ClientId,c=>{Add(c,"newid",id);Add(c,"client",r.ClientId);Add(c,"professional",r.ProfessionalId);Add(c,"source",r.SourceType);Add(c,"sourceid",r.SourceId);Add(c,"rule",r.RuleId);Add(c,"title",r.Title.Trim());Add(c,"description",r.Description?.Trim());Add(c,"due",r.DueAt);Add(c,"responsible",r.ResponsibleId);Add(c,"user",user.UserId);},ct);return Created($"/api/quality/follow-ups/{id}",new{success=true,data=new{id}});}
    [HttpPost("follow-ups/{id:guid}/complete"),RequirePermission("Quality.FollowUps.Manage")] public Task<IActionResult> Complete(Guid id,CancellationToken ct)=>SetFollowUp(id,"Done",ct);
    [HttpPost("follow-ups/{id:guid}/cancel"),RequirePermission("Quality.FollowUps.Manage")] public Task<IActionResult> Cancel(Guid id,CancellationToken ct)=>SetFollowUp(id,"Cancelled",ct);

    [HttpGet("follow-up-rules"),RequirePermission("Quality.Read")] public async Task<IActionResult> Rules(CancellationToken ct)=>Ok(new{success=true,data=await data.QueryAsync("select r.*,s.name service_name,t.name template_name from barber.quality_follow_up_rules r left join barber.services s on s.id=r.service_id left join barber.communication_templates t on t.id=r.template_id where r.tenant_id=@tenant and r.branch_id=@branch and r.deleted_at is null order by r.name",null,ct)});
    [HttpPost("follow-up-rules"),RequirePermission("Quality.Settings.Manage")] public Task<IActionResult> CreateRule(FollowUpRuleRequest r,CancellationToken ct)=>SaveRule(Guid.NewGuid(),r,false,ct);
    [HttpPut("follow-up-rules/{id:guid}"),RequirePermission("Quality.Settings.Manage")] public Task<IActionResult> UpdateRule(Guid id,FollowUpRuleRequest r,CancellationToken ct)=>SaveRule(id,r,true,ct);
    [HttpGet("retention-segments"),RequirePermission("Quality.Read")] public async Task<IActionResult> Segments(CancellationToken ct)=>Ok(new{success=true,data=await data.QueryAsync("select s.*,count(c.id) clients_count from barber.quality_retention_segments s left join barber.quality_retention_segment_clients c on c.segment_id=s.id where s.tenant_id=@tenant and s.branch_id=@branch and s.deleted_at is null group by s.id order by s.name",null,ct)});
    [HttpPost("retention-segments/recalculate"),RequirePermission("Quality.Manage")] public async Task<IActionResult> Recalculate(CancellationToken ct){await data.WriteAsync("update barber.quality_retention_segment_clients set calculated_at=now() where tenant_id=@tenant and branch_id=@branch","QualityRetentionRecalculated","quality_retention_segment_clients",null,null,null,ct);return Ok(new{success=true,calculatedAt=DateTimeOffset.UtcNow});}
    [HttpGet("reputation"),RequirePermission("Quality.Read")] public async Task<IActionResult> Reputation(CancellationToken ct)=>Ok(new{success=true,data=await data.QueryAsync("select r.*,p.name professional_name,s.name service_name from barber.quality_reputation_snapshots r left join barber.professionals p on p.id=r.professional_id left join barber.services s on s.id=r.service_id where r.tenant_id=@tenant and r.branch_id=@branch order by snapshot_date desc limit 300",null,ct)});
    [HttpGet("service-return-rules"),RequirePermission("Quality.Read")] public async Task<IActionResult> ReturnRules(CancellationToken ct)=>Ok(new{success=true,data=await data.QueryAsync("select r.*,s.name service_name from barber.quality_service_return_rules r join barber.services s on s.id=r.service_id where r.tenant_id=@tenant and r.branch_id=@branch and r.deleted_at is null order by s.name",null,ct)});
    [HttpPost("service-return-rules"),RequirePermission("Quality.Settings.Manage")] public Task<IActionResult> CreateReturnRule(ServiceReturnRuleRequest r,CancellationToken ct)=>SaveReturnRule(Guid.NewGuid(),r,false,ct);
    [HttpPut("service-return-rules/{id:guid}"),RequirePermission("Quality.Settings.Manage")] public Task<IActionResult> UpdateReturnRule(Guid id,ServiceReturnRuleRequest r,CancellationToken ct)=>SaveReturnRule(id,r,true,ct);
    [HttpGet("filter-options"),RequirePermission("Quality.Read")] public async Task<IActionResult> Options(CancellationToken ct)=>Ok(new{success=true,data=new{clients=await data.QueryAsync("select id,name from barber.clients where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by name limit 500",null,ct),professionals=await data.QueryAsync("select id,name from barber.professionals where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by name",null,ct),services=await data.QueryAsync("select id,name from barber.services where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by name",null,ct),users=await data.QueryAsync("select id,name from barber.users where tenant_id=@tenant and status='Active' order by name",null,ct),templates=await data.QueryAsync("select id,name from barber.communication_templates where tenant_id=@tenant and branch_id=@branch and status='Active' order by name",null,ct)}});
    [HttpGet("reports/export"),RequirePermission("Quality.Reports.Export")] public async Task<IActionResult> Export([FromQuery] QualityFilter f,CancellationToken ct){var rows=await data.QueryAsync("select r.created_at,c.name client,r.rating,r.nps_score,r.status,r.comment from barber.client_reviews r join barber.clients c on c.id=r.client_id where r.tenant_id=@tenant and r.branch_id=@branch and r.created_at::date between @from and @to order by r.created_at",c=>Bind(c,f),ct);var csv=new StringBuilder("data;cliente;rating;nps;status;comentario\r\n");foreach(var x in rows)csv.AppendLine(string.Join(';',x.Values.Select(Csv)));return File(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv.ToString())).ToArray(),"text/csv",$"qualidade-{DateTime.UtcNow:yyyyMMdd}.csv");}

    private async Task<IActionResult> SetFollowUp(Guid id,string status,CancellationToken ct){if(!FollowUpStatuses.Contains(status))return Invalid("status","Status inválido.");await data.WriteAsync("update barber.quality_follow_up_queue set status=@status,completed_by=case when @status='Done' then @user else completed_by end,completed_at=case when @status='Done' then now() else completed_at end,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch","QualityFollowUpUpdated","quality_follow_up_queue",id,null,c=>{Add(c,"status",status);Add(c,"user",user.UserId);},ct);return Ok(new{success=true});}
    private async Task<IActionResult> SaveRule(Guid id,FollowUpRuleRequest r,bool update,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Name)||r.DaysAfter<0||string.IsNullOrWhiteSpace(r.TriggerType))return Invalid("rule","Informe nome, gatilho e prazo válidos.");var sql=update?"update barber.quality_follow_up_rules set name=@name,trigger_type=@trigger,service_id=@service,days_after=@days,template_id=@template,status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch":"insert into barber.quality_follow_up_rules(id,tenant_id,branch_id,name,trigger_type,service_id,days_after,template_id,status,created_by) values(@id,@tenant,@branch,@name,@trigger,@service,@days,@template,@status,@user)";await data.WriteAsync(sql,"QualityFollowUpRuleSaved","quality_follow_up_rules",id,null,c=>{Add(c,"name",r.Name.Trim());Add(c,"trigger",r.TriggerType);Add(c,"service",r.ServiceId);Add(c,"days",r.DaysAfter);Add(c,"template",r.TemplateId);Add(c,"status",r.Status);Add(c,"user",user.UserId);},ct);return Ok(new{success=true,data=new{id}});}
    private async Task<IActionResult> SaveReturnRule(Guid id,ServiceReturnRuleRequest r,bool update,CancellationToken ct){if(r.ServiceId==Guid.Empty||r.MinDays<0||r.MaxDays<r.MinDays||r.RecommendedDays<r.MinDays||r.RecommendedDays>r.MaxDays)return Invalid("returnRule","Selecione o serviço e informe uma janela coerente.");var sql=update?"update barber.quality_service_return_rules set service_id=@service,min_days=@min,max_days=@max,recommended_days=@recommended,message=@message,status=@status,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch":"insert into barber.quality_service_return_rules(id,tenant_id,branch_id,service_id,min_days,max_days,recommended_days,message,status,created_by) values(@id,@tenant,@branch,@service,@min,@max,@recommended,@message,@status,@user)";await data.WriteAsync(sql,"QualityServiceReturnRuleSaved","quality_service_return_rules",id,null,c=>{Add(c,"service",r.ServiceId);Add(c,"min",r.MinDays);Add(c,"max",r.MaxDays);Add(c,"recommended",r.RecommendedDays);Add(c,"message",r.Message?.Trim());Add(c,"status",r.Status);Add(c,"user",user.UserId);},ct);return Ok(new{success=true,data=new{id}});}
    private IActionResult? Validate(QualityFilter f){if(f.From>f.To)return Invalid("from","A data inicial deve anteceder a final.");if(f.From is{} a&&f.To is{} b&&b.DayNumber-a.DayNumber>366)return Invalid("to","O período máximo é de 366 dias.");return null;}
    private void Bind(DbCommand c,QualityFilter f){var to=f.To??DateOnly.FromDateTime(DateTime.UtcNow);Add(c,"from",f.From??to.AddDays(-29));Add(c,"to",to);Add(c,"professional",f.ProfessionalId);Add(c,"client",f.ClientId);Add(c,"service",f.ServiceId);}
    private IActionResult Invalid(string field,string message)=>BadRequest(new ProblemDetails{Title="Dados inválidos",Detail=message,Status=400,Extensions={{"traceId",HttpContext.TraceIdentifier},{"errors",new Dictionary<string,string[]>{{field,[message]}}}}});
    private static void Add(DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
    private static string Csv(object? value)=>$"\"{Convert.ToString(value,CultureInfo.InvariantCulture)?.Replace("\"","\"\"")}\"";
}

public sealed record QualityFilter(DateOnly? From,DateOnly? To,Guid? ProfessionalId,Guid? ClientId,Guid? ServiceId);
public sealed record RecoveryCaseRequest(Guid ClientId,Guid AssignedTo,string CaseType,string Severity,string Reason,string Summary,Guid? ProfessionalId,Guid? AppointmentId,Guid? ServiceOrderId,Guid? ReviewId,Guid? SupportRequestId);
public sealed record RecoveryUpdateRequest(string Status,string Reason,string? Summary);
public sealed record AssignRequest(Guid AssignedTo);
public sealed record RecoveryActionRequest(string ActionType,string Description,Guid? AppointmentId);
public sealed record CloseCaseRequest(string Status,string Reason,string? ActionTaken);
public sealed record FollowUpRequest(Guid ClientId,Guid? ProfessionalId,string SourceType,Guid? SourceId,Guid? RuleId,string Title,string? Description,DateTimeOffset DueAt,Guid? ResponsibleId);
public sealed record FollowUpRuleRequest(string Name,string TriggerType,Guid? ServiceId,int DaysAfter,Guid? TemplateId,string Status="Active");
public sealed record ServiceReturnRuleRequest(Guid ServiceId,int MinDays,int MaxDays,int RecommendedDays,string? Message,string Status="Active");

[ApiController, Authorize, Route("api/mobile/quality")]
public sealed class MobileQualityController(TeamDataService data, ICurrentUserContext user) : ControllerBase
{
    private Guid ClientId => Guid.TryParse(User.FindFirstValue("client_id"),out var id)?id:user.UserId;
    private bool Professional => string.Equals(User.FindFirstValue(ClaimTypes.Role),"Professional",StringComparison.OrdinalIgnoreCase);

    [HttpGet("summary")]
    public async Task<IActionResult> Summary(CancellationToken ct)
    {
        var sql=Professional?@"select coalesce(round(avg(rating),2),0) average_rating,count(*) reviews_count,count(*) filter(where nps_score>=9) promoters,count(*) filter(where nps_score<=6) detractors,(select count(*) from barber.quality_follow_up_queue where tenant_id=@tenant and branch_id=@branch and professional_id=@owner and status in('Pending','Overdue')) pending_follow_ups from barber.client_reviews where tenant_id=@tenant and branch_id=@branch and professional_id=@owner and status in('Submitted','Hidden')":@"select (select to_jsonb(r) from barber.client_reviews r where r.tenant_id=@tenant and r.branch_id=@branch and r.client_id=@owner order by r.created_at desc limit 1) latest_review,(select to_jsonb(x) from barber.quality_service_return_rules x join barber.appointments a on a.service_id=x.service_id where x.tenant_id=@tenant and x.branch_id=@branch and a.client_id=@owner and x.status='Active' order by a.scheduled_start desc limit 1) return_recommendation,(select count(*) from barber.quality_follow_up_queue where tenant_id=@tenant and branch_id=@branch and client_id=@owner and status in('Pending','Overdue')) pending_follow_ups";
        return Ok(new{success=true,data=(await data.QueryAsync(sql,c=>TeamDataService.Add(c,"owner",Professional?user.UserId:ClientId),ct)).Single(),sourceStatus="available",traceId=HttpContext.TraceIdentifier});
    }

    [HttpGet("reviews")]
    public async Task<IActionResult> Reviews(CancellationToken ct)
    {
        var sql=Professional?"select id,rating,nps_score,comment,status,submitted_at from barber.client_reviews where tenant_id=@tenant and branch_id=@branch and professional_id=@owner order by created_at desc limit 100":"select id,rating,nps_score,comment,status,submitted_at from barber.client_reviews where tenant_id=@tenant and branch_id=@branch and client_id=@owner order by created_at desc limit 100";
        return Ok(new{success=true,data=await data.QueryAsync(sql,c=>TeamDataService.Add(c,"owner",Professional?user.UserId:ClientId),ct),traceId=HttpContext.TraceIdentifier});
    }

    [HttpPost("reviews")]
    public async Task<IActionResult> Review(MobileQualityReviewRequest r,CancellationToken ct)
    {
        if(Professional)return Forbid(); if(r.AppointmentId==Guid.Empty||r.Rating is<1 or>5||r.NpsScore is<0 or>10)return Problem(statusCode:422,title:"Avaliação inválida",detail:"Selecione um atendimento concluído, nota de 1 a 5 e NPS de 0 a 10.",extensions:new Dictionary<string,object?>{{"traceId",HttpContext.TraceIdentifier}});
        var id=Guid.NewGuid();await data.WriteAsync(@"insert into barber.client_reviews(id,tenant_id,branch_id,client_id,appointment_id,service_order_id,professional_id,rating,nps_score,comment,status,submitted_at) select @newid,@tenant,@branch,@client,a.id,o.id,a.professional_id,@rating,@nps,@comment,'Submitted',now() from barber.appointments a left join barber.service_orders o on o.appointment_id=a.id and o.client_id=a.client_id where a.id=@appointment and a.tenant_id=@tenant and a.branch_id=@branch and a.client_id=@client and a.status='Completed' and not exists(select 1 from barber.client_reviews r where r.tenant_id=@tenant and r.branch_id=@branch and r.client_id=@client and r.appointment_id=a.id)","QualityReviewSubmitted","client_reviews",id,ClientId,c=>{TeamDataService.Add(c,"newid",id);TeamDataService.Add(c,"client",ClientId);TeamDataService.Add(c,"appointment",r.AppointmentId);TeamDataService.Add(c,"rating",r.Rating);TeamDataService.Add(c,"nps",r.NpsScore);TeamDataService.Add(c,"comment",r.Comment?.Trim()??"");},ct);
        return Created($"/api/mobile/quality/reviews/{id}",new{success=true,data=new{id},traceId=HttpContext.TraceIdentifier});
    }

    [HttpGet("follow-ups")]
    public async Task<IActionResult> FollowUps(CancellationToken ct){var owner=Professional?user.UserId:ClientId;var field=Professional?"professional_id":"client_id";return Ok(new{success=true,data=await data.QueryAsync($"select id,title,description,due_at,status from barber.quality_follow_up_queue where tenant_id=@tenant and branch_id=@branch and {field}=@owner and status in('Pending','Overdue') order by due_at",c=>TeamDataService.Add(c,"owner",owner),ct)});}
    [HttpPost("follow-ups/{id:guid}/complete")]
    public async Task<IActionResult> Complete(Guid id,CancellationToken ct){var owner=Professional?user.UserId:ClientId;var field=Professional?"professional_id":"client_id";await data.WriteAsync($"update barber.quality_follow_up_queue set status='Done',completed_by=@user,completed_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and {field}=@owner and status in('Pending','Overdue')","QualityFollowUpCompleted","quality_follow_up_queue",id,null,c=>TeamDataService.Add(c,"owner",owner),ct);return Ok(new{success=true,traceId=HttpContext.TraceIdentifier});}
}
public sealed record MobileQualityReviewRequest(Guid AppointmentId,int Rating,int? NpsScore,string? Comment);
