using System.Text;
using BarberSync.Api.Security;
using BarberSync.Api.Services.ServiceExecution;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
namespace BarberSync.Api.Controllers;

[ApiController,Authorize]
public abstract class ServiceExecutionControllerBase(ServiceExecutionStore store):ControllerBase{protected ServiceExecutionStore Store=>store;protected object Out(object x)=>new{success=true,data=x,traceId=HttpContext.TraceIdentifier};}
[Route("api/service-execution")]
public sealed class ServiceExecutionController(ServiceExecutionStore store,ServiceExecutionOrchestrator flow):ServiceExecutionControllerBase(store){
 [HttpGet("dashboard"),RequirePermission("ServiceExecution.Read")]public async Task<IActionResult> Dashboard(CancellationToken ct)=>Ok(Out((await Store.Query("select count(*) filter(where status='CheckedIn') checked_in,count(*) filter(where status='InService') in_service,count(*) filter(where status in ('Open','ServiceCompleted','Checkout')) open_orders,coalesce(sum(total) filter(where status in ('Paid','Closed')),0) revenue from barber.service_orders where tenant_id=@tenant and branch_id=@branch and created_at::date=current_date",null,ct)).Single()));
 [HttpGet("today"),RequirePermission("ServiceExecution.Read")]public async Task<IActionResult> Today(CancellationToken ct)=>Ok(Out(await Store.Query("select a.id appointment_id,a.scheduled_start,a.status,c.name client_name,p.name professional_name,s.name service_name,o.id service_order_id,o.status order_status,o.total from barber.appointments a left join barber.clients c on c.id=a.client_id left join barber.professionals p on p.id=a.professional_id left join barber.services s on s.id=a.service_id left join barber.service_orders o on o.appointment_id=a.id and o.deleted_at is null where a.tenant_id=@tenant and a.branch_id=@branch and a.scheduled_start::date=current_date and a.deleted_at is null order by a.scheduled_start",null,ct)));
 [HttpPost("check-in"),RequirePermission("ServiceExecution.CheckIn")]public async Task<IActionResult> CheckIn(CheckInRequest r,CancellationToken ct)=>Ok(Out(await flow.CheckInAppointmentAsync(r,ct)));
 [HttpGet("filter-options"),RequirePermission("ServiceExecution.Read")]public async Task<IActionResult> Options(CancellationToken ct)=>Ok(Out(new{appointments=await Store.Query("select a.id,c.name||' · '||to_char(a.scheduled_start,'HH24:MI') name from barber.appointments a join barber.clients c on c.id=a.client_id where a.tenant_id=@tenant and a.branch_id=@branch and a.status in ('Scheduled','Confirmed') and a.scheduled_start::date=current_date order by a.scheduled_start",null,ct),services=await Store.Query("select s.id,s.name from barber.services s join barber.catalog_service_profiles p on p.service_id=s.id and p.status='Active' where s.tenant_id=@tenant and s.branch_id=@branch and s.deleted_at is null",null,ct),products=await Store.Query("select x.id,x.name from barber.products x join barber.catalog_product_profiles p on p.product_id=x.id and p.status='Active' where x.tenant_id=@tenant and x.branch_id=@branch and x.deleted_at is null",null,ct),professionals=await Store.Query("select id,name from barber.professionals where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null",null,ct)}));}
[Route("api/service-execution/orders")]
public sealed class ServiceExecutionOrdersController(ServiceExecutionStore store,ServiceExecutionOrchestrator flow):ServiceExecutionControllerBase(store){[HttpPost("from-appointment"),RequirePermission("ServiceExecution.Orders.Manage")]public async Task<IActionResult> Open(OpenOrderFromAppointmentRequest r,CancellationToken ct)=>Ok(Out(await flow.OpenServiceOrderFromAppointmentAsync(r,ct)));[HttpGet,RequirePermission("ServiceExecution.Read")]public async Task<IActionResult> List(CancellationToken ct)=>Ok(Out(await Store.Query("select o.*,c.name client_name from barber.service_orders o left join barber.clients c on c.id=o.client_id where o.tenant_id=@tenant and o.branch_id=@branch and o.deleted_at is null order by o.created_at desc limit 300",null,ct)));[HttpGet("{id:guid}"),RequirePermission("ServiceExecution.Read")]public async Task<IActionResult> One(Guid id,CancellationToken ct)=>Ok(Out(await Store.Query("select o.*,coalesce(jsonb_agg(s.*) filter(where s.id is not null),'[]') pricing from barber.service_orders o left join barber.service_order_pricing_snapshots s on s.service_order_id=o.id where o.id=@id and o.tenant_id=@tenant and o.branch_id=@branch group by o.id",c=>ServiceExecutionStore.Add(c,"id",id),ct)));[HttpPost("{id:guid}/services"),RequirePermission("ServiceExecution.Orders.Manage")]public async Task<IActionResult>AddService(Guid id,AddServiceToOrderRequest r,CancellationToken ct)=>Ok(Out(await flow.AddServiceToOrderAsync(r with{ServiceOrderId=id},ct)));[HttpPost("{id:guid}/products"),RequirePermission("ServiceExecution.Orders.Manage")]public async Task<IActionResult>AddProduct(Guid id,AddProductToOrderRequest r,CancellationToken ct)=>Ok(Out(await flow.AddProductToOrderAsync(r with{ServiceOrderId=id},ct)));[HttpPost("{id:guid}/start-service"),RequirePermission("ServiceExecution.Orders.Manage")]public async Task<IActionResult>Start(Guid id,StartServiceRequest r,CancellationToken ct)=>Ok(Out(await flow.StartServiceAsync(r with{ServiceOrderId=id},ct)));[HttpPost("{id:guid}/complete-service"),RequirePermission("ServiceExecution.Orders.Manage")]public async Task<IActionResult>Complete(Guid id,CompleteServiceRequest r,CancellationToken ct)=>Ok(Out(await flow.CompleteServiceAsync(r with{ServiceOrderId=id},ct)));[HttpPost("{id:guid}/cancel-service"),RequirePermission("ServiceExecution.Orders.Manage")]public async Task<IActionResult>Cancel(Guid id,CancelServiceRequest r,CancellationToken ct)=>Ok(Out(await flow.CancelServiceAsync(r with{ServiceOrderId=id},ct)));}
[Route("api/service-execution/checkout")]
public sealed class ServiceExecutionCheckoutController(ServiceExecutionStore store,CheckoutOrchestrationService checkout):ServiceExecutionControllerBase(store){[HttpPost("preview"),RequirePermission("ServiceExecution.Checkout.Manage")]public async Task<IActionResult>Preview(CheckoutPreviewRequest r,CancellationToken ct)=>Ok(Out(await checkout.PreviewCheckoutAsync(r,ct)));[HttpPost("apply-discount"),RequirePermission("ServiceExecution.Checkout.Manage")]public async Task<IActionResult>Discount(ApplyDiscountRequest r,CancellationToken ct)=>Ok(Out(await checkout.ApplyDiscountAsync(r,ct)));[HttpPost("apply-benefit"),RequirePermission("ServiceExecution.Checkout.Manage")]public async Task<IActionResult>Benefit(ApplyBenefitRequest r,CancellationToken ct)=>Ok(Out(await checkout.ApplyBenefitAsync(r,ct)));[HttpPost("create-payment-intent"),RequirePermission("ServiceExecution.Checkout.Manage")]public async Task<IActionResult>Intent(CreatePaymentIntentRequest r,CancellationToken ct)=>Ok(Out(await checkout.CreatePaymentIntentAsync(r,ct)));[HttpPost("confirm"),RequirePermission("ServiceExecution.Checkout.Manage")]public async Task<IActionResult>Confirm(ConfirmCheckoutRequest r,CancellationToken ct)=>Ok(Out(await checkout.ConfirmCheckoutAsync(r,ct)));[HttpPost("cancel"),RequirePermission("ServiceExecution.Checkout.Manage")]public async Task<IActionResult>Cancel(CancelCheckoutRequest r,CancellationToken ct)=>Ok(Out(await checkout.CancelCheckoutAsync(r,ct)));}
[Route("api/service-execution/cashier")]
public sealed class ServiceExecutionCashierController(ServiceExecutionStore store,CashSessionService cash):ServiceExecutionControllerBase(store){[HttpGet("current"),RequirePermission("ServiceExecution.Read")]public async Task<IActionResult>Current(CancellationToken ct)=>Ok(Out(await Store.Query("select * from barber.cash_sessions where tenant_id=@tenant and branch_id=@branch and operator_user_id=@user and status='Open'",null,ct)));[HttpPost("open"),RequirePermission("ServiceExecution.Cashier.Manage")]public async Task<IActionResult>Open(OpenCashSessionRequest r,CancellationToken ct)=>Ok(Out(await cash.OpenCashSessionAsync(r,ct)));[HttpPost("close"),RequirePermission("ServiceExecution.Cashier.Manage")]public async Task<IActionResult>Close(CloseCashSessionRequest r,CancellationToken ct)=>Ok(Out(await cash.CloseCashSessionAsync(r,ct)));[HttpPost("adjust"),RequirePermission("ServiceExecution.Cashier.Manage")]public async Task<IActionResult>Adjust(CashAdjustmentRequest r,CancellationToken ct)=>Ok(Out(await cash.RegisterCashAdjustmentAsync(r,ct)));}
[Route("api/service-execution/commissions")]
public sealed class ServiceExecutionCommissionsController(ServiceExecutionStore store,CommissionAccrualService service):ServiceExecutionControllerBase(store){[HttpGet,RequirePermission("ServiceExecution.Commissions.Read")]public async Task<IActionResult>List(CancellationToken ct)=>Ok(Out(await Store.Query("select * from barber.commission_accrual_events where tenant_id=@tenant and branch_id=@branch order by created_at desc limit 500",null,ct)));[HttpPost("preview"),RequirePermission("ServiceExecution.Commissions.Read")]public async Task<IActionResult>Preview(CommissionPreviewRequest r,CancellationToken ct)=>Ok(Out(await service.PreviewCommissionsAsync(r,ct)));[HttpPost("reverse"),RequirePermission("ServiceExecution.Commissions.Read")]public async Task<IActionResult>Reverse(ReverseCommissionRequest r,CancellationToken ct)=>Ok(Out(await service.ReverseCommissionAsync(r,ct)));}
[Route("api/service-execution/inventory-consumption")]
public sealed class ServiceExecutionInventoryController(ServiceExecutionStore store,InventoryConsumptionService service):ServiceExecutionControllerBase(store){[HttpGet,RequirePermission("ServiceExecution.Read")]public async Task<IActionResult>List(CancellationToken ct)=>Ok(Out(await Store.Query("select s.*,p.name product_name from barber.inventory_consumption_snapshots s left join barber.products p on p.id=s.product_id where s.tenant_id=@tenant and s.branch_id=@branch order by s.created_at desc limit 500",null,ct)));[HttpPost("preview"),RequirePermission("ServiceExecution.Inventory.Manage")]public async Task<IActionResult>Preview(ConsumptionPreviewRequest r,CancellationToken ct)=>Ok(Out(await service.PreviewConsumptionAsync(r,ct)));[HttpPost("reverse"),RequirePermission("ServiceExecution.Inventory.Manage")]public async Task<IActionResult>Reverse(ReverseConsumptionRequest r,CancellationToken ct)=>Ok(Out(await service.ReverseConsumptionAsync(r,ct)));}
[Route("api/service-execution/audit")]
public sealed class ServiceExecutionAuditController(ServiceExecutionStore store):ServiceExecutionControllerBase(store){[HttpGet,RequirePermission("ServiceExecution.Read")]public async Task<IActionResult>List(CancellationToken ct)=>Ok(Out(await Store.Query("select * from barber.service_execution_events where tenant_id=@tenant and branch_id=@branch order by created_at desc limit 500",null,ct)));}
[Route("api/service-execution/reports")]
public sealed class ServiceExecutionReportsController(ServiceExecutionStore store):ServiceExecutionControllerBase(store){[HttpGet("export"),RequirePermission("ServiceExecution.Reports.Export")]public async Task<IActionResult>Export(CancellationToken ct){var rows=await Store.Query("select created_at,event_type,status,description,service_order_id from barber.service_execution_events where tenant_id=@tenant and branch_id=@branch order by created_at desc",null,ct);var csv=new StringBuilder("data;evento;status;descricao;comanda\r\n");foreach(var row in rows)csv.AppendLine(string.Join(';',row.Values.Select(x=>$"\"{Convert.ToString(x)?.Replace("\"","\"\"")}\"")));return File(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv.ToString())).ToArray(),"text/csv",$"atendimento-360-{DateTime.UtcNow:yyyyMMdd}.csv");}}
[Route("api/mobile/service-execution")]
public sealed class MobileServiceExecutionController(ServiceExecutionStore store,ServiceExecutionOrchestrator flow,CheckoutOrchestrationService checkout):ServiceExecutionControllerBase(store){[HttpGet("today")]public async Task<IActionResult>Today(CancellationToken ct)=>Ok(Out(await Store.Query("select a.id,a.scheduled_start,a.status,c.name client_name from barber.appointments a left join barber.clients c on c.id=a.client_id where a.tenant_id=@tenant and a.branch_id=@branch and a.scheduled_start::date=current_date and a.deleted_at is null order by a.scheduled_start",null,ct)));[HttpGet("orders")]public async Task<IActionResult>Orders(CancellationToken ct)=>Ok(Out(await Store.Query("select id,number,status,total,created_at from barber.service_orders where tenant_id=@tenant and branch_id=@branch and deleted_at is null order by created_at desc limit 100",null,ct)));[HttpPost("check-in")]public async Task<IActionResult>CheckIn(CheckInRequest r,CancellationToken ct)=>Ok(Out(await flow.CheckInAppointmentAsync(r,ct)));[HttpPost("orders/{id:guid}/complete-service")]public async Task<IActionResult>Complete(Guid id,CompleteServiceRequest r,CancellationToken ct)=>Ok(Out(await flow.CompleteServiceAsync(r with{ServiceOrderId=id},ct)));[HttpPost("checkout/preview")]public async Task<IActionResult>Preview(CheckoutPreviewRequest r,CancellationToken ct)=>Ok(Out(await checkout.PreviewCheckoutAsync(r,ct)));}
