using System.Data.Common;
using BarberSync.Api.Security;
using BarberSync.Api.Services.Team;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BarberSync.Api.Controllers;

[ApiController, Authorize, Route("api")]
public sealed class TeamController(TeamDataService team, ILogger<TeamController> logger) : ControllerBase
{
    [HttpGet("team/dashboard"), RequirePermission("Professional.Read")]
    public Task<IActionResult> Dashboard(CancellationToken ct) => Safe(async () => Ok(Envelope((await team.QueryAsync(@"select
(select count(*) from barber.professionals where tenant_id=@tenant and branch_id=@branch and deleted_at is null and is_active) active_professionals,
(select count(distinct professional_id) from barber.professional_working_hours where tenant_id=@tenant and branch_id=@branch and is_active and day_of_week=extract(isodow from current_date)) available_today,
(select coalesce(sum(total),0) from barber.service_orders where tenant_id=@tenant and branch_id=@branch and status in ('Paid','Closed') and created_at::date=date_trunc('month',current_date)::date) team_revenue,
(select coalesce(sum(amount),0) from barber.commissions where tenant_id=@tenant and branch_id=@branch and status='Available') open_commissions,
(select coalesce(sum(amount),0) from barber.professional_payouts where tenant_id=@tenant and branch_id=@branch and status='Paid' and paid_at::date>=date_trunc('month',current_date)::date) paid_commissions,
(select count(*) from barber.professional_goals where tenant_id=@tenant and branch_id=@branch and status='Active' and current_value>=target_value) goals_achieved", null, ct)).Single())));

    [HttpGet("professionals/{id:guid}/profile"), RequirePermission("Professional.Read")]
    public Task<IActionResult> Profile(Guid id,CancellationToken ct)=>Safe(async()=>Result(await team.QueryAsync("select * from barber.professional_profiles where tenant_id=@tenant and branch_id=@branch and professional_id=@professional and deleted_at is null",c=>TeamDataService.Add(c,"professional",id),ct)));
    [HttpPut("professionals/{id:guid}/profile"), RequirePermission("Professional.Update")]
    public Task<IActionResult> UpdateProfile(Guid id,ProfileRequest request,CancellationToken ct)=>Safe(async()=>{if(string.IsNullOrWhiteSpace(request.DisplayName))return ValidationProblem("Nome de exibição obrigatório.");var profileId=await team.WriteAsync(@"insert into barber.professional_profiles(id,tenant_id,branch_id,professional_id,display_name,document_number,phone,email,bio,photo_url,hire_date,termination_date,status,employment_type,specialties_json,settings_json)
values(@id,@tenant,@branch,@professional,@name,@document,@phone,@email,@bio,@photo,@hire,@termination,@status,@employment,@specialties::jsonb,@settings::jsonb)
on conflict(tenant_id,branch_id,professional_id) where deleted_at is null do update set display_name=excluded.display_name,document_number=excluded.document_number,phone=excluded.phone,email=excluded.email,bio=excluded.bio,photo_url=excluded.photo_url,hire_date=excluded.hire_date,termination_date=excluded.termination_date,status=excluded.status,employment_type=excluded.employment_type,specialties_json=excluded.specialties_json,settings_json=excluded.settings_json,updated_at=now()", "Professional.ProfileUpdated","professional_profiles",null,null,c=>{TeamDataService.Add(c,"professional",id);TeamDataService.Add(c,"name",request.DisplayName.Trim());TeamDataService.Add(c,"document",request.DocumentNumber);TeamDataService.Add(c,"phone",request.Phone);TeamDataService.Add(c,"email",request.Email);TeamDataService.Add(c,"bio",request.Bio);TeamDataService.Add(c,"photo",request.PhotoUrl);TeamDataService.Add(c,"hire",request.HireDate);TeamDataService.Add(c,"termination",request.TerminationDate);TeamDataService.Add(c,"status",request.Status);TeamDataService.Add(c,"employment",request.EmploymentType);TeamDataService.Add(c,"specialties",request.SpecialtiesJson);TeamDataService.Add(c,"settings",request.SettingsJson);},ct);return Ok(Envelope(new{id=profileId}));});
    [HttpGet("professionals/{id:guid}/services"), RequirePermission("Professional.Read")]
    public Task<IActionResult> Services(Guid id,CancellationToken ct)=>Safe(async()=>Ok(Envelope(await team.QueryAsync("select ps.service_id,s.name,ps.price_override,ps.duration_override_minutes,ps.commission_percent,ps.status from barber.professional_services ps join barber.services s on s.id=ps.service_id where ps.tenant_id=@tenant and ps.branch_id=@branch and ps.professional_id=@professional order by s.name",c=>TeamDataService.Add(c,"professional",id),ct))));
    [HttpPost("professionals/{id:guid}/services"), RequirePermission("Professional.Update")]
    [HttpPut("professionals/{id:guid}/services/{serviceId:guid}"), RequirePermission("Professional.Update")]
    public Task<IActionResult> LinkService(Guid id,ServiceLinkRequest request,CancellationToken ct,Guid? serviceId=null)=>Safe(async()=>{var target=serviceId??request.ServiceId;await team.WriteAsync(@"insert into barber.professional_services(professional_id,service_id,tenant_id,branch_id,price_override,duration_override_minutes,commission_percent,status) select @professional,id,@tenant,@branch,@price,@duration,@commission,@status from barber.services where id=@service and tenant_id=@tenant and (branch_id=@branch or branch_id is null) and deleted_at is null on conflict(professional_id,service_id) do update set price_override=excluded.price_override,duration_override_minutes=excluded.duration_override_minutes,commission_percent=excluded.commission_percent,status=excluded.status,updated_at=now()","Professional.ServiceLinked","professional_services",null,null,c=>{TeamDataService.Add(c,"professional",id);TeamDataService.Add(c,"service",target);TeamDataService.Add(c,"price",request.PriceOverride);TeamDataService.Add(c,"duration",request.DurationOverrideMinutes);TeamDataService.Add(c,"commission",request.CommissionPercentOverride);TeamDataService.Add(c,"status",request.Status);},ct);return Ok(Envelope(new{serviceId=target}));});
    [HttpGet("professionals/{id:guid}/schedule"), RequirePermission("Professional.Read")]
    public Task<IActionResult> Schedule(Guid id,CancellationToken ct)=>Safe(async()=>Ok(Envelope(await team.QueryAsync("select id,day_of_week,start_time,end_time,break_start,break_end,effective_from,effective_to,is_active from barber.professional_working_hours where tenant_id=@tenant and branch_id=@branch and professional_id=@professional order by effective_from desc,day_of_week",c=>TeamDataService.Add(c,"professional",id),ct))));
    [HttpGet("professionals/{id:guid}/time-off"), RequirePermission("Professional.Read")]
    public Task<IActionResult> TimeOff(Guid id,CancellationToken ct)=>Safe(async()=>Ok(Envelope(await team.QueryAsync("select * from barber.professional_time_off where tenant_id=@tenant and branch_id=@branch and professional_id=@professional order by starts_at desc",c=>TeamDataService.Add(c,"professional",id),ct))));
    [HttpPost("professionals/{id:guid}/time-off"), RequirePermission("Professional.Update")]
    [HttpPut("professionals/{id:guid}/time-off/{timeOffId:guid}"), RequirePermission("Professional.Update")]
    public Task<IActionResult> SaveTimeOff(Guid id,TimeOffRequest request,CancellationToken ct,Guid? timeOffId=null)=>Safe(async()=>{if(request.EndsAt<=request.StartsAt||string.IsNullOrWhiteSpace(request.Reason))return ValidationProblem("Período e motivo são obrigatórios.");var key=await team.WriteAsync(@"insert into barber.professional_time_off(id,tenant_id,branch_id,professional_id,type,starts_at,ends_at,reason,status,approved_by,approved_at) values(@id,@tenant,@branch,@professional,@type,@start,@end,@reason,@status,@approver,case when @status='Approved' then now() end) on conflict(id) do update set type=excluded.type,starts_at=excluded.starts_at,ends_at=excluded.ends_at,reason=excluded.reason,status=excluded.status,approved_by=excluded.approved_by,approved_at=excluded.approved_at,updated_at=now() where professional_time_off.tenant_id=@tenant and professional_time_off.branch_id=@branch","Professional.TimeOffChanged","professional_time_off",timeOffId,request.Reason,c=>{TeamDataService.Add(c,"professional",id);TeamDataService.Add(c,"type",request.Type);TeamDataService.Add(c,"start",request.StartsAt);TeamDataService.Add(c,"end",request.EndsAt);TeamDataService.Add(c,"reason",request.Reason.Trim());TeamDataService.Add(c,"status",request.Status);TeamDataService.Add(c,"approver",UserId());},ct);return Ok(Envelope(new{id=key}));});
    [HttpGet("professionals/{id:guid}/performance"), RequirePermission("Professional.Read")]
    public Task<IActionResult> Performance(Guid id,[FromQuery]DateOnly? from,[FromQuery]DateOnly? to,CancellationToken ct)=>Safe(async()=>Ok(Envelope((await team.QueryAsync(@"select count(*) filter(where a.status in ('Finished','Completed')) appointments,coalesce(sum(so.total),0) revenue,coalesce(avg(so.total),0) average_ticket,coalesce(sum(c.amount),0) commissions_generated,coalesce(sum(c.amount) filter(where c.status='Paid'),0) commissions_paid from barber.professionals p left join barber.appointments a on a.professional_id=p.id and a.scheduled_start::date between @from and @to left join barber.service_orders so on so.appointment_id=a.id and so.status in ('Paid','Closed') left join barber.commissions c on c.professional_id=p.id and c.created_at::date between @from and @to where p.id=@professional and p.tenant_id=@tenant and p.branch_id=@branch group by p.id",c=>{TeamDataService.Add(c,"professional",id);TeamDataService.Add(c,"from",from??new DateOnly(DateTime.UtcNow.Year,DateTime.UtcNow.Month,1));TeamDataService.Add(c,"to",to??DateOnly.FromDateTime(DateTime.UtcNow));},ct)).SingleOrDefault())));

    private Guid UserId()=>Guid.TryParse(User.FindFirst("sub")?.Value,out var id)?id:Guid.Empty;
    private IActionResult Result(IReadOnlyList<Dictionary<string,object?>> rows)=>rows.Count==0?NotFound(Error("Perfil profissional não encontrado.")):Ok(Envelope(rows[0]));
    private async Task<IActionResult> Safe(Func<Task<IActionResult>> action){try{return await action();}catch(ArgumentException ex){return BadRequest(Error(ex.Message));}catch(InvalidOperationException ex){return Conflict(Error(ex.Message));}catch(Exception ex){logger.LogError(ex,"Falha no módulo Equipe");return StatusCode(500,Error("Não foi possível concluir a operação."));}}
    private object Envelope(object? data)=>new{success=true,data}; private object Error(string message)=>new{success=false,message,traceId=HttpContext.TraceIdentifier};
    public sealed record ProfileRequest(string DisplayName,string? DocumentNumber,string? Phone,string? Email,string? Bio,string? PhotoUrl,DateOnly? HireDate,DateOnly? TerminationDate,string Status="Active",string EmploymentType="Partner",string SpecialtiesJson="[]",string SettingsJson="{}");
    public sealed record ServiceLinkRequest(Guid ServiceId,decimal? PriceOverride,int? DurationOverrideMinutes,decimal? CommissionPercentOverride,string Status="Active");
    public sealed record TimeOffRequest(string Type,DateTimeOffset StartsAt,DateTimeOffset EndsAt,string Reason,string Status="Approved");
}
