using BarberSync.Api.Security;
using BarberSync.Api.Services.Team;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BarberSync.Api.Controllers;

[ApiController, Authorize, Route("api")]
public sealed class TeamFinanceController(TeamDataService team, ILogger<TeamFinanceController> logger) : ControllerBase
{
    [HttpGet("commissions/rules"), RequirePermission("Professional.Read")]
    public Task<IActionResult> Rules(CancellationToken ct)=>Safe(async()=>Ok(Wrap(await team.QueryAsync("select id,professional_id,service_id,product_id,package_id,rule_type,percentage,fixed_value,valid_from,valid_until,is_active from barber.commission_rules where tenant_id=@tenant and branch_id=@branch order by valid_from desc",null,ct))));
    [HttpPost("commissions/rules"), RequirePermission("Professional.Update")]
    [HttpPut("commissions/rules/{id:guid}"), RequirePermission("Professional.Update")]
    public Task<IActionResult> SaveRule(RuleRequest request,CancellationToken ct,Guid? id=null)=>Safe(async()=>{if(request.Percentage is <0 or >100||request.FixedValue<0)return ValidationProblem("Valores de comissão inválidos.");var key=await team.WriteAsync(@"insert into barber.commission_rules(id,tenant_id,branch_id,professional_id,service_id,product_id,package_id,rule_type,percentage,fixed_value,valid_from,valid_until,is_active) values(@id,@tenant,@branch,@professional,@service,@product,@package,@type,@percentage,@fixed,@from,@to,@active) on conflict(id) do update set professional_id=excluded.professional_id,service_id=excluded.service_id,product_id=excluded.product_id,package_id=excluded.package_id,rule_type=excluded.rule_type,percentage=excluded.percentage,fixed_value=excluded.fixed_value,valid_from=excluded.valid_from,valid_until=excluded.valid_until,is_active=excluded.is_active,updated_at=now() where commission_rules.tenant_id=@tenant and commission_rules.branch_id=@branch","Commission.RuleChanged","commission_rules",id,null,c=>{TeamDataService.Add(c,"professional",request.ProfessionalId);TeamDataService.Add(c,"service",request.ServiceId);TeamDataService.Add(c,"product",request.ProductId);TeamDataService.Add(c,"package",request.PackageId);TeamDataService.Add(c,"type",request.RuleType);TeamDataService.Add(c,"percentage",request.Percentage??0);TeamDataService.Add(c,"fixed",request.FixedValue);TeamDataService.Add(c,"from",request.StartsAt);TeamDataService.Add(c,"to",request.EndsAt);TeamDataService.Add(c,"active",request.Active);},ct);return Ok(Wrap(new{id=key}));});
    [HttpGet("commissions/settlements"), RequirePermission("Professional.Read")]
    public Task<IActionResult> Settlements([FromQuery]Guid? professionalId,[FromQuery]string? status,CancellationToken ct)=>Safe(async()=>Ok(Wrap(await team.QueryAsync("select * from barber.commission_settlements where tenant_id=@tenant and branch_id=@branch and (@professional is null or professional_id=@professional) and (@status is null or status=@status) order by period_end desc",c=>{TeamDataService.Add(c,"professional",professionalId);TeamDataService.Add(c,"status",status);},ct))));
    [HttpPost("commissions/settlements"), RequirePermission("Professional.Update")]
    public Task<IActionResult> Close(SettlementRequest request,CancellationToken ct)=>Safe(async()=>{var id=await team.CreateSettlement(request.ProfessionalId,request.PeriodStart,request.PeriodEnd,request.DiscountAmount,request.AdjustmentReason,ct);return Created($"/api/commissions/settlements/{id}",Wrap(new{id}));});
    [HttpPost("commissions/settlements/{id:guid}/approve"), RequirePermission("Professional.Update")]
    public Task<IActionResult> Approve(Guid id,CancellationToken ct)=>Safe(async()=>{await team.MarkSettlement(id,false,null,null,ct);return Ok(Wrap(new{id,status="Approved"}));});
    [HttpPost("commissions/settlements/{id:guid}/mark-paid"), RequirePermission("Professional.Update")]
    public Task<IActionResult> Pay(Guid id,PaymentRequest request,CancellationToken ct)=>Safe(async()=>{await team.MarkSettlement(id,true,request.PaymentMethod,request.Reference,ct);return Ok(Wrap(new{id,status="Paid"}));});
    [HttpGet("professional-goals"), RequirePermission("Professional.Read")]
    public Task<IActionResult> Goals([FromQuery]Guid? professionalId,CancellationToken ct)=>Safe(async()=>Ok(Wrap(await team.QueryAsync("select * from barber.professional_goals where tenant_id=@tenant and branch_id=@branch and (@professional is null or professional_id=@professional) order by period_start desc",c=>TeamDataService.Add(c,"professional",professionalId),ct))));
    [HttpPost("professional-goals"), RequirePermission("Professional.Update")]
    [HttpPut("professional-goals/{id:guid}"), RequirePermission("Professional.Update")]
    public Task<IActionResult> SaveGoal(GoalRequest request,CancellationToken ct,Guid? id=null)=>Safe(async()=>{if(request.PeriodEnd<request.PeriodStart||request.TargetValue<0)return ValidationProblem("Período ou meta inválida.");var key=await team.WriteAsync(@"insert into barber.professional_goals(id,tenant_id,branch_id,professional_id,period_type,period_start,period_end,goal_type,target_value,current_value,status) values(@id,@tenant,@branch,@professional,@periodType,@from,@to,@goalType,@target,@current,@status) on conflict(id) do update set period_type=excluded.period_type,period_start=excluded.period_start,period_end=excluded.period_end,goal_type=excluded.goal_type,target_value=excluded.target_value,current_value=excluded.current_value,status=excluded.status,updated_at=now() where professional_goals.tenant_id=@tenant and professional_goals.branch_id=@branch","Professional.GoalChanged","professional_goals",id,request.Reason,c=>{TeamDataService.Add(c,"professional",request.ProfessionalId);TeamDataService.Add(c,"periodType",request.PeriodType);TeamDataService.Add(c,"from",request.PeriodStart);TeamDataService.Add(c,"to",request.PeriodEnd);TeamDataService.Add(c,"goalType",request.GoalType);TeamDataService.Add(c,"target",request.TargetValue);TeamDataService.Add(c,"current",request.CurrentValue);TeamDataService.Add(c,"status",request.Status);},ct);return Ok(Wrap(new{id=key}));});
    [HttpGet("professional-payouts"), RequirePermission("Professional.Read")]
    public Task<IActionResult> Payouts([FromQuery]Guid? professionalId,CancellationToken ct)=>Safe(async()=>Ok(Wrap(await team.QueryAsync("select * from barber.professional_payouts where tenant_id=@tenant and branch_id=@branch and (@professional is null or professional_id=@professional) order by paid_at desc",c=>TeamDataService.Add(c,"professional",professionalId),ct))));
    [HttpPost("professional-payouts"), RequirePermission("Professional.Update")]
    public Task<IActionResult> Payout(PayoutRequest request,CancellationToken ct)=>Safe(async()=>{await team.MarkSettlement(request.SettlementId,true,request.PaymentMethod,request.Reference,ct);return Ok(Wrap(new{request.SettlementId,status="Paid"}));});
    private async Task<IActionResult> Safe(Func<Task<IActionResult>> action){try{return await action();}catch(ArgumentException ex){return BadRequest(Error(ex.Message));}catch(InvalidOperationException ex){return Conflict(Error(ex.Message));}catch(Exception ex){logger.LogError(ex,"Falha no fechamento de equipe");return StatusCode(500,Error("Não foi possível concluir a operação."));}}
    private static object Wrap(object? data)=>new{success=true,data};private object Error(string message)=>new{success=false,message,traceId=HttpContext.TraceIdentifier};
    public sealed record RuleRequest(Guid? ProfessionalId,Guid? ServiceId,Guid? ProductId,Guid? PackageId,string RuleType,decimal? Percentage,decimal? FixedValue,DateOnly StartsAt,DateOnly? EndsAt,bool Active=true);
    public sealed record SettlementRequest(Guid ProfessionalId,DateOnly PeriodStart,DateOnly PeriodEnd,decimal DiscountAmount=0,string? AdjustmentReason=null);
    public sealed record PaymentRequest(string PaymentMethod,string Reference);
    public sealed record GoalRequest(Guid ProfessionalId,string PeriodType,DateOnly PeriodStart,DateOnly PeriodEnd,string GoalType,decimal TargetValue,decimal CurrentValue=0,string Status="Active",string? Reason=null);
    public sealed record PayoutRequest(Guid SettlementId,string PaymentMethod,string Reference);
}
