using System.Globalization;
using System.Text;
using BarberSync.Api.Services.Team;

namespace BarberSync.Api.Services.Finance360;

internal static class FinanceRules
{
    internal static void Money(decimal amount){if(amount<=0)throw new ArgumentException("O valor deve ser maior que zero.");}
    internal static void Period(DateOnly from,DateOnly to){if(to<from)throw new ArgumentException("Período financeiro inválido.");}
    internal static void Settlement(Guid? payment,bool manual,string? reason){if(payment is null&&(!manual||string.IsNullOrWhiteSpace(reason)))throw new ArgumentException("Informe um pagamento confirmado ou uma baixa manual autorizada com motivo.");}
    internal static decimal Value(Dictionary<string,object?> row,string key)=>Convert.ToDecimal(row[key]??0,CultureInfo.InvariantCulture);
}

public sealed class AccountsReceivableService(TeamDataService data)
{
    public async Task<ReceivableResult> CreateReceivableAsync(CreateReceivableRequest r,CancellationToken ct){FinanceRules.Money(r.Amount);if(string.IsNullOrWhiteSpace(r.Description))throw new ArgumentException("Descrição obrigatória.");var id=await data.WriteAsync(@"insert into barber.finance_receivables(id,tenant_id,branch_id,client_id,source_type,source_id,description,amount,due_at,created_by) values(@id,@tenant,@branch,@client,@source,@sourceId,@description,@amount,@due,@user) on conflict(tenant_id,branch_id,source_type,source_id) do nothing","Finance360.ReceivableCreated","finance_receivables",null,null,c=>{Add(c,"client",r.ClientId);Add(c,"source",r.SourceType);Add(c,"sourceId",r.SourceId);Add(c,"description",r.Description.Trim());Add(c,"amount",r.Amount);Add(c,"due",r.DueAt);Add(c,"user",Guid.Empty);},ct);return new(id,"Open",r.Amount,0);}
    public Task<ReceivableResult> MarkReceivablePaidAsync(MarkReceivablePaidRequest r,CancellationToken ct)=>Settle(r.Id,r.PaymentId,r.ManualSettlement,r.Reason,r.Amount,true,ct);
    public Task<ReceivableResult> MarkReceivablePartiallyPaidAsync(MarkReceivablePartiallyPaidRequest r,CancellationToken ct)=>Settle(r.Id,r.PaymentId,r.ManualSettlement,r.Reason,r.Amount,false,ct);
    private async Task<ReceivableResult> Settle(Guid id,Guid? payment,bool manual,string? reason,decimal amount,bool full,CancellationToken ct){FinanceRules.Money(amount);FinanceRules.Settlement(payment,manual,reason);var rows=await data.QueryAsync("select amount,paid_amount,status from barber.finance_receivables where id=@rid and tenant_id=@tenant and branch_id=@branch",c=>Add(c,"rid",id),ct);if(rows.Count!=1)throw new InvalidOperationException("Recebível não encontrado.");var total=FinanceRules.Value(rows[0],"amount");var paid=FinanceRules.Value(rows[0],"paid_amount");var applied=full?total-paid:amount;if(applied<=0||paid+applied>total)throw new InvalidOperationException("Valor de baixa excede o saldo.");var status=paid+applied==total?"Paid":"PartiallyPaid";await data.WriteAsync(@"update barber.finance_receivables set paid_amount=paid_amount+@amount,status=@status,payment_id=@payment,paid_at=case when @status='Paid' then now() else paid_at end,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','PartiallyPaid','Overdue') and (@payment is null or exists(select 1 from barber.payments p where p.id=@payment and p.tenant_id=@tenant and p.branch_id=@branch and p.status in ('Confirmed','Paid'))) ",manual?"Finance360.ReceivableManualSettlement":"Finance360.ReceivablePayment","finance_receivables",id,reason,c=>{Add(c,"amount",applied);Add(c,"status",status);Add(c,"payment",payment);},ct);return new(id,status,total,paid+applied);}
    public async Task<ReceivableResult> MarkReceivableOverdueAsync(MarkReceivableOverdueRequest r,CancellationToken ct){await data.WriteAsync("update barber.finance_receivables set status='Overdue',updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','PartiallyPaid') and due_at<now()","Finance360.ReceivableOverdue","finance_receivables",r.Id,null,null,ct);return new(r.Id,"Overdue",0,0);}
    public async Task<ReceivableResult> CancelReceivableAsync(CancelReceivableRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Motivo obrigatório.");await data.WriteAsync("update barber.finance_receivables set status='Cancelled',cancel_reason=@reason,cancelled_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','PartiallyPaid','Overdue')","Finance360.ReceivableCancelled","finance_receivables",r.Id,r.Reason,c=>Add(c,"reason",r.Reason),ct);return new(r.Id,"Cancelled",0,0);}
    public async Task<ReceivableAgingResult> GetReceivableAgingAsync(ReceivableAgingRequest r,CancellationToken ct){FinanceRules.Period(r.From,r.To);return new(await data.QueryAsync("select case when due_at>=now() then 'current' when due_at>=now()-interval '30 days' then '1-30' when due_at>=now()-interval '60 days' then '31-60' else '61+' end bucket,sum(amount-paid_amount) amount,count(*) count from barber.finance_receivables where tenant_id=@tenant and branch_id=@branch and status in ('Open','PartiallyPaid','Overdue') and due_at::date between @from and @to group by 1 order by 1",c=>{Add(c,"from",r.From);Add(c,"to",r.To);},ct));}
    private static void Add(System.Data.Common.DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
}

public sealed class AccountsPayableService(TeamDataService data)
{
    public async Task<PayableResult> CreatePayableAsync(CreatePayableRequest r,CancellationToken ct){FinanceRules.Money(r.Amount);var status=r.Scheduled?"Scheduled":"Open";var id=await data.WriteAsync(@"insert into barber.finance_payables(id,tenant_id,branch_id,supplier_id,partner_id,professional_id,source_type,source_id,description,amount,due_at,status,created_by) values(@id,@tenant,@branch,@supplier,@partner,@professional,@source,@sourceId,@description,@amount,@due,@status,@user) on conflict(tenant_id,branch_id,source_type,source_id) do nothing","Finance360.PayableCreated","finance_payables",null,null,c=>{Add(c,"supplier",r.SupplierId);Add(c,"partner",r.PartnerId);Add(c,"professional",r.ProfessionalId);Add(c,"source",r.SourceType);Add(c,"sourceId",r.SourceId);Add(c,"description",r.Description.Trim());Add(c,"amount",r.Amount);Add(c,"due",r.DueAt);Add(c,"status",status);Add(c,"user",Guid.Empty);},ct);return new(id,status,r.Amount,0);}
    public async Task<PayableResult> SchedulePayableAsync(SchedulePayableRequest r,CancellationToken ct){await data.WriteAsync("update barber.finance_payables set status='Scheduled',due_at=@due,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status='Open'","Finance360.PayableScheduled","finance_payables",r.Id,null,c=>Add(c,"due",r.DueAt),ct);return new(r.Id,"Scheduled",0,0);}
    public Task<PayableResult> MarkPayablePaidAsync(MarkPayablePaidRequest r,CancellationToken ct)=>Settle(r.Id,r.PaymentId,r.ManualSettlement,r.Reason,r.Amount,true,ct);
    public Task<PayableResult> MarkPayablePartiallyPaidAsync(MarkPayablePartiallyPaidRequest r,CancellationToken ct)=>Settle(r.Id,r.PaymentId,r.ManualSettlement,r.Reason,r.Amount,false,ct);
    private async Task<PayableResult> Settle(Guid id,Guid? payment,bool manual,string? reason,decimal amount,bool full,CancellationToken ct){FinanceRules.Money(amount);FinanceRules.Settlement(payment,manual,reason);var rows=await data.QueryAsync("select amount,paid_amount from barber.finance_payables where id=@pid and tenant_id=@tenant and branch_id=@branch",c=>Add(c,"pid",id),ct);if(rows.Count!=1)throw new InvalidOperationException("Pagável não encontrado.");var total=FinanceRules.Value(rows[0],"amount");var paid=FinanceRules.Value(rows[0],"paid_amount");var applied=full?total-paid:amount;if(applied<=0||paid+applied>total)throw new InvalidOperationException("Valor de baixa excede o saldo.");var status=paid+applied==total?"Paid":"PartiallyPaid";await data.WriteAsync("update barber.finance_payables set paid_amount=paid_amount+@amount,status=@status,payment_id=@payment,paid_at=case when @status='Paid' then now() else paid_at end,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','Scheduled','PartiallyPaid','Overdue') and (@payment is null or exists(select 1 from barber.payments p where p.id=@payment and p.tenant_id=@tenant and p.branch_id=@branch and p.status in ('Confirmed','Paid')))",manual?"Finance360.PayableManualSettlement":"Finance360.PayablePayment","finance_payables",id,reason,c=>{Add(c,"amount",applied);Add(c,"status",status);Add(c,"payment",payment);},ct);return new(id,status,total,paid+applied);}
    public async Task<PayableResult> MarkPayableOverdueAsync(MarkPayableOverdueRequest r,CancellationToken ct){await data.WriteAsync("update barber.finance_payables set status='Overdue',updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','Scheduled','PartiallyPaid') and due_at<now()","Finance360.PayableOverdue","finance_payables",r.Id,null,null,ct);return new(r.Id,"Overdue",0,0);}
    public async Task<PayableResult> CancelPayableAsync(CancelPayableRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Motivo obrigatório.");await data.WriteAsync("update barber.finance_payables set status='Cancelled',cancel_reason=@reason,cancelled_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and status in ('Open','Scheduled','PartiallyPaid','Overdue')","Finance360.PayableCancelled","finance_payables",r.Id,r.Reason,c=>Add(c,"reason",r.Reason),ct);return new(r.Id,"Cancelled",0,0);}
    public async Task<PayableAgingResult> GetPayableAgingAsync(PayableAgingRequest r,CancellationToken ct){FinanceRules.Period(r.From,r.To);return new(await data.QueryAsync("select status,sum(amount-paid_amount) amount,count(*) count from barber.finance_payables where tenant_id=@tenant and branch_id=@branch and status in ('Open','Scheduled','PartiallyPaid','Overdue') and due_at::date between @from and @to group by status",c=>{Add(c,"from",r.From);Add(c,"to",r.To);},ct));}
    private static void Add(System.Data.Common.DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
}

public sealed class FinancialPostingService(TeamDataService data)
{
    public Task<FinancialPostingResult> PostCheckoutAsync(PostCheckoutRequest r,CancellationToken ct)=>Post(r,"Revenue","Credit",ct); public Task<FinancialPostingResult> PostPaymentAsync(PostPaymentRequest r,CancellationToken ct)=>Post(r,"Revenue","Credit",ct); public Task<FinancialPostingResult> PostRefundAsync(PostRefundRequest r,CancellationToken ct)=>Post(r,"Refund","Debit",ct); public Task<FinancialPostingResult> PostCommissionAsync(PostCommissionRequest r,CancellationToken ct)=>Post(r,"Commission","Debit",ct); public Task<FinancialPostingResult> PostPayrollSettlementAsync(PostPayrollSettlementRequest r,CancellationToken ct)=>Post(r,"Payroll","Debit",ct); public Task<FinancialPostingResult> PostPartnerPayoutAsync(PostPartnerPayoutRequest r,CancellationToken ct)=>Post(r,"PartnerPayout","Debit",ct);
    private async Task<FinancialPostingResult> Post(PostingRequest r,string type,string direction,CancellationToken ct){FinanceRules.Money(r.Amount);if(string.IsNullOrWhiteSpace(r.IdempotencyKey))throw new ArgumentException("Chave de idempotência obrigatória.");var existing=await data.QueryAsync("select id,status from barber.finance_postings where tenant_id=@tenant and branch_id=@branch and idempotency_key=@key",c=>Add(c,"key",r.IdempotencyKey),ct);if(existing.Count>0)return new((Guid)existing[0]["id"]!,existing[0]["status"]?.ToString()??"Confirmed",true);var id=await data.WriteAsync(@"insert into barber.finance_postings(id,tenant_id,branch_id,posting_type,source_type,source_id,account_id,category_id,cost_center_id,amount,direction,status,idempotency_key,posted_at,created_by) select @id,@tenant,@branch,@type,@source,@sourceId,@account,@category,@cost,@amount,@direction,'Confirmed',@key,now(),@user where @payment is null or exists(select 1 from barber.payments p where p.id=@payment and p.tenant_id=@tenant and p.branch_id=@branch and p.status in ('Confirmed','Paid'))","Finance360.PostingConfirmed","finance_postings",null,null,c=>{Add(c,"type",type);Add(c,"source",r.SourceType);Add(c,"sourceId",r.SourceId);Add(c,"account",r.AccountId);Add(c,"category",r.CategoryId);Add(c,"cost",r.CostCenterId);Add(c,"amount",r.Amount);Add(c,"direction",direction);Add(c,"key",r.IdempotencyKey);Add(c,"payment",r.PaymentId);Add(c,"user",Guid.Empty);},ct);return new(id,"Confirmed");}
    public async Task<FinancialPostingResult> ReversePostingAsync(ReversePostingRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason)||string.IsNullOrWhiteSpace(r.IdempotencyKey))throw new ArgumentException("Motivo e chave de idempotência obrigatórios.");var id=await data.WriteAsync(@"insert into barber.finance_postings(id,tenant_id,branch_id,posting_type,source_type,source_id,account_id,category_id,cost_center_id,amount,direction,status,idempotency_key,posted_at,created_by,metadata_json) select @id,tenant_id,branch_id,'Reversal','FinancePosting',id,account_id,category_id,cost_center_id,amount,case direction when 'Debit' then 'Credit' else 'Debit' end,'Confirmed',@key,now(),@user,jsonb_build_object('reason',@reason) from barber.finance_postings where id=@original and tenant_id=@tenant and branch_id=@branch and status='Confirmed'; update barber.finance_postings set status='Reversed' where id=@original and tenant_id=@tenant and branch_id=@branch","Finance360.PostingReversed","finance_postings",null,r.Reason,c=>{Add(c,"original",r.PostingId);Add(c,"key",r.IdempotencyKey);Add(c,"reason",r.Reason);Add(c,"user",Guid.Empty);},ct);return new(id,"Confirmed");}
    private static void Add(System.Data.Common.DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
}

public sealed class ReconciliationService(TeamDataService data)
{
    public async Task<ReconciliationPreviewResult> PreviewReconciliationAsync(ReconciliationPreviewRequest r,CancellationToken ct){var rows=await data.QueryAsync(@"select p.status payment_status,fp.amount expected from barber.payments p join barber.finance_postings fp on fp.id=@posting and fp.tenant_id=p.tenant_id and fp.branch_id=p.branch_id where p.id=@payment and p.tenant_id=@tenant and p.branch_id=@branch and fp.status='Confirmed'",c=>{Add(c,"payment",r.PaymentId);Add(c,"posting",r.PostingId);},ct);if(rows.Count!=1)throw new InvalidOperationException("Pagamento ou lançamento confirmado não encontrado.");var expected=FinanceRules.Value(rows[0],"expected");var difference=r.ActualAmount-expected;var paymentStatus=rows[0]["payment_status"]?.ToString()??"Unknown";var suggested=(paymentStatus is "Confirmed" or "Paid")&&Math.Abs(difference)<=r.Tolerance?"Matched":"Divergent";return new(expected,r.ActualAmount,difference,suggested,paymentStatus);}
    public async Task<ReconciliationResult> ReconcilePaymentAsync(ReconcilePaymentRequest r,CancellationToken ct){var preview=await PreviewReconciliationAsync(new(r.PaymentId,r.PostingId,r.AccountId,r.ActualAmount,r.Tolerance),ct);if(preview.PaymentStatus is not ("Confirmed" or "Paid"))throw new InvalidOperationException("Pagamento pendente não pode ser conciliado.");if(Math.Abs(preview.Difference)>r.Tolerance)throw new InvalidOperationException("Diferença fora da tolerância; registre como divergente.");return await Save(r.PaymentId,r.PostingId,r.AccountId,preview,"Matched",null,ct);}
    public async Task<ReconciliationResult> MarkAsDivergentAsync(MarkReconciliationDivergentRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Motivo obrigatório.");var p=await PreviewReconciliationAsync(new(r.PaymentId,r.PostingId,r.AccountId,r.ActualAmount),ct);return await Save(r.PaymentId,r.PostingId,r.AccountId,p,"Divergent",r.Reason,ct);}
    private async Task<ReconciliationResult> Save(Guid payment,Guid posting,Guid account,ReconciliationPreviewResult p,string status,string? reason,CancellationToken ct){var id=await data.WriteAsync("insert into barber.finance_reconciliations(id,tenant_id,branch_id,payment_id,finance_posting_id,account_id,expected_amount,actual_amount,difference_amount,status,reason,reconciled_by,reconciled_at) values(@id,@tenant,@branch,@payment,@posting,@account,@expected,@actual,@difference,@status,@reason,@user,now())","Finance360.Reconciliation"+status,"finance_reconciliations",null,reason,c=>{Add(c,"payment",payment);Add(c,"posting",posting);Add(c,"account",account);Add(c,"expected",p.ExpectedAmount);Add(c,"actual",p.ActualAmount);Add(c,"difference",p.Difference);Add(c,"status",status);Add(c,"reason",reason);Add(c,"user",Guid.Empty);},ct);return new(id,status,p.Difference);}
    public async Task<ReconciliationResult> ReverseReconciliationAsync(ReverseReconciliationRequest r,CancellationToken ct){if(string.IsNullOrWhiteSpace(r.Reason))throw new ArgumentException("Motivo obrigatório.");var id=await data.WriteAsync(@"insert into barber.finance_reconciliations(id,tenant_id,branch_id,payment_id,finance_posting_id,account_id,expected_amount,actual_amount,difference_amount,status,reason,reconciled_by,reconciled_at,metadata_json) select @id,tenant_id,branch_id,payment_id,finance_posting_id,account_id,expected_amount,actual_amount,difference_amount,'Reversed',@reason,@user,now(),jsonb_build_object('reverses',id) from barber.finance_reconciliations where id=@original and tenant_id=@tenant and branch_id=@branch and status in ('Matched','Divergent')","Finance360.ReconciliationReversed","finance_reconciliations",null,r.Reason,c=>{Add(c,"original",r.Id);Add(c,"reason",r.Reason);Add(c,"user",Guid.Empty);},ct);return new(id,"Reversed",0);}
    private static void Add(System.Data.Common.DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
}

public sealed class CashFlowService(TeamDataService data)
{
    public async Task<CashFlowProjectionResult> GetProjectionAsync(CashFlowProjectionRequest r,CancellationToken ct){FinanceRules.Period(r.From,r.To);var row=(await data.QueryAsync(@"select coalesce((select sum(amount-paid_amount) from barber.finance_receivables where tenant_id=@tenant and branch_id=@branch and status in ('Open','PartiallyPaid','Overdue') and due_at::date between @from and @to),0) projected_in,coalesce((select sum(amount-paid_amount) from barber.finance_payables where tenant_id=@tenant and branch_id=@branch and status in ('Open','Scheduled','PartiallyPaid','Overdue') and due_at::date between @from and @to),0) projected_out",c=>Bind(c,r.From,r.To),ct)).Single();return new(FinanceRules.Value(row,"projected_in"),FinanceRules.Value(row,"projected_out"),"Available");}
    public async Task<CashFlowRealizedResult> GetRealizedAsync(CashFlowRealizedRequest r,CancellationToken ct){FinanceRules.Period(r.From,r.To);var row=(await data.QueryAsync("select coalesce(sum(amount) filter(where direction='Credit'),0) realized_in,coalesce(sum(amount) filter(where direction='Debit'),0) realized_out from barber.finance_postings where tenant_id=@tenant and branch_id=@branch and status='Confirmed' and posted_at::date between @from and @to",c=>Bind(c,r.From,r.To),ct)).Single();return new(FinanceRules.Value(row,"realized_in"),FinanceRules.Value(row,"realized_out"),"Available");}
    public async Task<CashFlowComparisonResult> GetProjectedVsRealizedAsync(CashFlowComparisonRequest r,CancellationToken ct)=>new(await GetProjectionAsync(new(r.From,r.To),ct),await GetRealizedAsync(new(r.From,r.To),ct));
    public async Task<CashFlowSnapshotResult> CreateSnapshotAsync(CreateCashFlowSnapshotRequest r,CancellationToken ct){var values=await GetProjectedVsRealizedAsync(new(r.From,r.To),ct);var id=await data.WriteAsync("insert into barber.finance_cash_flow_snapshots(id,tenant_id,branch_id,snapshot_date,projected_in,projected_out,realized_in,realized_out,net_projected,net_realized) values(@id,@tenant,@branch,@date,@pi,@po,@ri,@ro,@pi-@po,@ri-@ro)","Finance360.CashFlowSnapshot","finance_cash_flow_snapshots",null,null,c=>{Add(c,"date",r.SnapshotDate);Add(c,"pi",values.Projected.ProjectedIn);Add(c,"po",values.Projected.ProjectedOut);Add(c,"ri",values.Realized.RealizedIn);Add(c,"ro",values.Realized.RealizedOut);},ct);return new(id,values);}
    private static void Bind(System.Data.Common.DbCommand c,DateOnly f,DateOnly t){Add(c,"from",f);Add(c,"to",t);} private static void Add(System.Data.Common.DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
}

public sealed class DreService(TeamDataService data)
{
    public async Task<DreResult> GetDreAsync(DreRequest r,CancellationToken ct){FinanceRules.Period(r.From,r.To);var row=(await data.QueryAsync(@"select coalesce(sum(amount) filter(where direction='Credit' and posting_type='Revenue'),0) gross_revenue,coalesce(sum(amount) filter(where posting_type='Adjustment'),0) discounts,coalesce(sum(amount) filter(where posting_type='Cost'),0) costs,coalesce(sum(amount) filter(where posting_type='Commission'),0) commissions,coalesce(sum(amount) filter(where posting_type='Payroll'),0) payroll,coalesce(sum(amount) filter(where posting_type='PartnerPayout'),0) partners,coalesce(sum(amount) filter(where posting_type='Expense'),0) expenses from barber.finance_postings where tenant_id=@tenant and branch_id=@branch and status='Confirmed' and posted_at::date between @from and @to",c=>{Add(c,"from",r.From);Add(c,"to",r.To);},ct)).Single();var gross=V(row,"gross_revenue");var discounts=V(row,"discounts");var costs=V(row,"costs");var commissions=V(row,"commissions");var payroll=V(row,"payroll");var partners=V(row,"partners");var expenses=V(row,"expenses");var net=gross-discounts;return new(gross,discounts,net,costs,0,commissions,payroll,partners,expenses,net-costs,net-costs-commissions-payroll-partners-expenses,"Available");}
    public async Task<DreSnapshotResult> CreateDreSnapshotAsync(CreateDreSnapshotRequest r,CancellationToken ct){var v=await GetDreAsync(new(r.From,r.To),ct);var id=await data.WriteAsync(@"insert into barber.finance_dre_snapshots(id,tenant_id,branch_id,period_start,period_end,gross_revenue,discounts,net_revenue,service_costs,product_costs,commissions,payroll_costs,partner_payouts,operational_expenses,gross_profit,net_result) values(@id,@tenant,@branch,@from,@to,@gross,@discounts,@net,@service,@product,@commissions,@payroll,@partners,@expenses,@profit,@result)","Finance360.DreSnapshot","finance_dre_snapshots",null,null,c=>{Add(c,"from",r.From);Add(c,"to",r.To);Add(c,"gross",v.GrossRevenue);Add(c,"discounts",v.Discounts);Add(c,"net",v.NetRevenue);Add(c,"service",v.ServiceCosts);Add(c,"product",v.ProductCosts);Add(c,"commissions",v.Commissions);Add(c,"payroll",v.PayrollCosts);Add(c,"partners",v.PartnerPayouts);Add(c,"expenses",v.OperationalExpenses);Add(c,"profit",v.GrossProfit);Add(c,"result",v.NetResult);},ct);return new(id,v);}
    public async Task<DreExportResult> ExportDreAsync(DreExportRequest r,CancellationToken ct){var v=await GetDreAsync(new(r.From,r.To),ct);var csv=$"indicador;valor\nReceita bruta;{v.GrossRevenue.ToString(CultureInfo.InvariantCulture)}\nReceita líquida;{v.NetRevenue.ToString(CultureInfo.InvariantCulture)}\nResultado líquido;{v.NetResult.ToString(CultureInfo.InvariantCulture)}\n";return new(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv)).ToArray(),$"dre-{r.From:yyyyMMdd}-{r.To:yyyyMMdd}.csv");}
    private static decimal V(Dictionary<string,object?> r,string k)=>FinanceRules.Value(r,k);private static void Add(System.Data.Common.DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
}

public sealed class FinanceAuditService(TeamDataService data)
{
    public async Task<FinanceAuditResult> RegisterEventAsync(RegisterFinanceAuditEventRequest r,CancellationToken ct){var id=await data.WriteAsync("insert into barber.finance_audit_events(id,tenant_id,branch_id,event_type,source_type,source_id,description,old_status,new_status,amount,metadata_json,created_by) values(@id,@tenant,@branch,@event,@source,@sourceId,@description,@old,@new,@amount,coalesce(@metadata,'{}')::jsonb,@user)","Finance360.AuditRegistered","finance_audit_events",null,r.Description,c=>{Add(c,"event",r.EventType);Add(c,"source",r.SourceType);Add(c,"sourceId",r.SourceId);Add(c,"description",r.Description);Add(c,"old",r.OldStatus);Add(c,"new",r.NewStatus);Add(c,"amount",r.Amount);Add(c,"metadata",r.MetadataJson);Add(c,"user",Guid.Empty);},ct);return new(id);}
    public async Task<FinanceAuditSearchResult> SearchAsync(FinanceAuditSearchRequest r,CancellationToken ct){FinanceRules.Period(r.From,r.To);return new(await data.QueryAsync("select id,event_type,source_type,source_id,description,old_status,new_status,amount,created_by,created_at from barber.finance_audit_events where tenant_id=@tenant and branch_id=@branch and created_at::date between @from and @to and (@event is null or event_type=@event) order by created_at desc",c=>{Add(c,"from",r.From);Add(c,"to",r.To);Add(c,"event",r.EventType);},ct));}
    public async Task<FinanceAuditExportResult> ExportAsync(FinanceAuditExportRequest r,CancellationToken ct){var result=await SearchAsync(new(r.From,r.To,r.EventType),ct);var csv=new StringBuilder("evento;origem;descricao;data\n");foreach(var x in result.Events)csv.AppendLine($"\"{x["event_type"]}\";\"{x["source_type"]}\";\"{x["description"]?.ToString()?.Replace("\"","\"\"")}\";\"{x["created_at"]}\"");return new(Encoding.UTF8.GetPreamble().Concat(Encoding.UTF8.GetBytes(csv.ToString())).ToArray(),$"finance-audit-{r.From:yyyyMMdd}-{r.To:yyyyMMdd}.csv");}
    private static void Add(System.Data.Common.DbCommand c,string n,object? v)=>TeamDataService.Add(c,n,v);
}
