using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Npgsql;

namespace BarberSync.Api.Services.ClientPortal;

public sealed record PortalScope(Guid TenantId, Guid BranchId, Guid ClientId, Guid SessionId);
public sealed record AccessCodeResult(string DeliveryStatus, string Message, string? DevelopmentCode = null);

public sealed class ClientPortalStore(IConfiguration configuration, IWebHostEnvironment environment)
{
    private readonly string connectionString = configuration.GetConnectionString("DefaultConnection")
        ?? throw new InvalidOperationException("ConnectionStrings:DefaultConnection não foi configurada.");
    private readonly bool deliveryConfigured = configuration.GetValue<bool>("ClientPortal:DeliveryConfigured");
    private readonly bool exposeDevelopmentCode = configuration.GetValue<bool>("ClientPortal:ExposeDevelopmentCode");

    public async Task<AccessCodeResult> RequestCode(string branchCode, string destination, string destinationType, HttpContext http, CancellationToken ct)
    {
        var neutral = "Se seus dados estiverem cadastrados, enviaremos um código de acesso.";
        if (string.IsNullOrWhiteSpace(branchCode) || string.IsNullOrWhiteSpace(destination)) return new("ManualDeliveryRequired", neutral);
        await using var c = await Open(ct);
        await using var find = new NpgsqlCommand(@"select c.tenant_id,c.branch_id,c.id from barber.clients c join barber.branches b on b.id=c.branch_id
where lower(b.code)=lower(@branch) and c.deleted_at is null and c.is_active and
(lower(coalesce(c.email,''))=lower(@destination) or regexp_replace(coalesce(c.phone,c.whatsapp,''),'\D','','g')=regexp_replace(@destination,'\D','','g')) limit 1", c);
        find.Parameters.AddWithValue("branch", branchCode.Trim()); find.Parameters.AddWithValue("destination", destination.Trim());
        await using var reader = await find.ExecuteReaderAsync(ct);
        if (!await reader.ReadAsync(ct)) return new(deliveryConfigured ? "Accepted" : "ProviderNotConfigured", neutral);
        var tenant = reader.GetGuid(0); var branch = reader.GetGuid(1); var client = reader.GetGuid(2); await reader.CloseAsync();
        var code = RandomNumberGenerator.GetInt32(100000, 1000000).ToString(); var hash = Hash(code);
        await using var insert = new NpgsqlCommand(@"insert into barber.client_portal_access_codes(tenant_id,branch_id,client_id,destination_type,destination_masked,code_hash,purpose,status,expires_at,ip_address,user_agent)
values(@tenant,@branch,@client,@type,@masked,@hash,'Login','Pending',now()+interval '10 minutes',@ip::inet,@agent)", c);
        insert.Parameters.AddWithValue("tenant",tenant); insert.Parameters.AddWithValue("branch",branch); insert.Parameters.AddWithValue("client",client);
        insert.Parameters.AddWithValue("type", destinationType is "Phone" ? "Phone" : "Email"); insert.Parameters.AddWithValue("masked", Mask(destination)); insert.Parameters.AddWithValue("hash",hash);
        insert.Parameters.AddWithValue("ip", http.Connection.RemoteIpAddress?.ToString() ?? "127.0.0.1"); insert.Parameters.AddWithValue("agent", http.Request.Headers.UserAgent.ToString()); await insert.ExecuteNonQueryAsync(ct);
        await Event(c, tenant, branch, client, "ClientPortalAccessRequested", "AccessCode", null, http, ct);
        if (!deliveryConfigured)
            return new("ProviderNotConfigured", "O canal de entrega ainda não está configurado. Entre em contato com a unidade.", environment.IsDevelopment() && exposeDevelopmentCode ? code : null);
        // A provider integration must consume Pending codes. We never claim delivery merely because the row was created.
        return new("ManualDeliveryRequired", neutral, environment.IsDevelopment() && exposeDevelopmentCode ? code : null);
    }

    public async Task<string?> VerifyCode(string branchCode, string destination, string code, HttpContext http, CancellationToken ct)
    {
        if (code.Length != 6 || !code.All(char.IsDigit)) return null;
        await using var c=await Open(ct); await using var tx=await c.BeginTransactionAsync(ct);
        await using var cmd=new NpgsqlCommand(@"select ac.id,ac.tenant_id,ac.branch_id,ac.client_id,ac.code_hash,ac.attempts,ac.max_attempts
from barber.client_portal_access_codes ac join barber.branches b on b.id=ac.branch_id join barber.clients cl on cl.id=ac.client_id
where lower(b.code)=lower(@branch) and ac.status='Pending' and ac.expires_at>now() and
(lower(coalesce(cl.email,''))=lower(@destination) or regexp_replace(coalesce(cl.phone,cl.whatsapp,''),'\D','','g')=regexp_replace(@destination,'\D','','g')) order by ac.created_at desc limit 1 for update",c,tx);
        cmd.Parameters.AddWithValue("branch",branchCode.Trim());cmd.Parameters.AddWithValue("destination",destination.Trim()); await using var r=await cmd.ExecuteReaderAsync(ct);
        if(!await r.ReadAsync(ct)) return null; var accessId=r.GetGuid(0);var tenant=r.GetGuid(1);var branch=r.GetGuid(2);var client=r.GetGuid(3);var expected=r.GetString(4);var attempts=r.GetInt32(5)+1;var max=r.GetInt32(6);await r.CloseAsync();
        if(!CryptographicOperations.FixedTimeEquals(Convert.FromHexString(expected),Convert.FromHexString(Hash(code)))) { await Exec(c,tx,"update barber.client_portal_access_codes set attempts=@attempts,status=case when @attempts>=max_attempts then 'Cancelled' else status end where id=@id",("attempts",attempts),("id",accessId)); await tx.CommitAsync(ct); return null; }
        var token=Convert.ToBase64String(RandomNumberGenerator.GetBytes(48)).Replace('+','-').Replace('/','_').TrimEnd('=');var sessionId=Guid.NewGuid();
        await Exec(c,tx,"update barber.client_portal_access_codes set attempts=@attempts,status='Used',used_at=now() where id=@id",("attempts",attempts),("id",accessId));
        await Exec(c,tx,"insert into barber.client_portal_sessions(id,tenant_id,branch_id,client_id,session_hash,status,expires_at,last_seen_at,ip_address,user_agent) values(@id,@tenant,@branch,@client,@hash,'Active',now()+interval '8 hours',now(),@ip::inet,@agent)",("id",sessionId),("tenant",tenant),("branch",branch),("client",client),("hash",Hash(token)),("ip",http.Connection.RemoteIpAddress?.ToString()??"127.0.0.1"),("agent",http.Request.Headers.UserAgent.ToString()));
        await tx.CommitAsync(ct); await Event(c,tenant,branch,client,"ClientPortalLoginSucceeded","Session",sessionId,http,ct); return token;
    }

    public async Task<PortalScope?> Authenticate(HttpContext http,CancellationToken ct)
    { var token=http.Request.Headers.Authorization.ToString();if(token.StartsWith("Bearer ",StringComparison.OrdinalIgnoreCase))token=token[7..].Trim();if(string.IsNullOrWhiteSpace(token))return null;await using var c=await Open(ct);await using var cmd=new NpgsqlCommand("update barber.client_portal_sessions set last_seen_at=now() where session_hash=@hash and status='Active' and expires_at>now() returning tenant_id,branch_id,client_id,id",c);cmd.Parameters.AddWithValue("hash",Hash(token));await using var r=await cmd.ExecuteReaderAsync(ct);return await r.ReadAsync(ct)?new(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetGuid(3)):null;}
    public async Task Logout(PortalScope s,CancellationToken ct){await using var c=await Open(ct);await using var cmd=new NpgsqlCommand("update barber.client_portal_sessions set status='Revoked',revoked_at=now() where id=@id and client_id=@client",c);cmd.Parameters.AddWithValue("id",s.SessionId);cmd.Parameters.AddWithValue("client",s.ClientId);await cmd.ExecuteNonQueryAsync(ct);}

    public Task<JsonElement> Home(PortalScope s,CancellationToken ct)=>Json(s,@"select jsonb_build_object('profile',(select jsonb_build_object('name',name,'email',email,'phone',phone) from barber.clients where id=@client),'nextAppointment',(select jsonb_build_object('when',a.scheduled_start,'status',a.status,'service',sv.name,'professional',p.name) from barber.appointments a left join barber.services sv on sv.id=a.service_id left join barber.professionals p on p.id=a.professional_id where a.client_id=@client and a.tenant_id=@tenant and a.branch_id=@branch and a.scheduled_start>=now() and a.status not in('Cancelled','Completed','NoShow') order by a.scheduled_start limit 1),'pendingPayments',(select count(*) from barber.client_payment_requests where client_id=@client and tenant_id=@tenant and branch_id=@branch and status='Pending'),'pendingBudgets',(select count(*) from barber.client_budgets where client_id=@client and tenant_id=@tenant and branch_id=@branch and status='Presented'),'pendingConsents',(select count(*) from barber.client_consent_terms t where t.tenant_id=@tenant and t.branch_id=@branch and t.status='Active' and not exists(select 1 from barber.client_consent_acceptances a where a.consent_term_id=t.id and a.client_id=@client and a.status='Active')))",ct);
    public Task<JsonElement> List(PortalScope s,string kind,CancellationToken ct)=>Json(s,kind switch {
        "appointments"=>"select coalesce(jsonb_agg(jsonb_build_object('actionKey',a.id,'when',a.scheduled_start,'endsAt',a.scheduled_end,'status',a.status,'service',sv.name,'professional',p.name) order by a.scheduled_start desc),'[]') from barber.appointments a left join barber.services sv on sv.id=a.service_id left join barber.professionals p on p.id=a.professional_id where a.tenant_id=@tenant and a.branch_id=@branch and a.client_id=@client and a.deleted_at is null",
        "history"=>"select coalesce(jsonb_agg(x order by x->>'when' desc),'[]') from (select jsonb_build_object('when',a.scheduled_start,'title',sv.name,'professional',p.name,'status',a.status) x from barber.appointments a left join barber.services sv on sv.id=a.service_id left join barber.professionals p on p.id=a.professional_id where a.tenant_id=@tenant and a.branch_id=@branch and a.client_id=@client and a.status='Completed' union all select jsonb_build_object('when',v.created_at,'title',v.title,'description',v.description,'status','Compartilhado') from barber.client_visual_records v where v.tenant_id=@tenant and v.branch_id=@branch and v.client_id=@client and v.privacy_status='SharedWithClient') q",
        "consents"=>"select coalesce(jsonb_agg(jsonb_build_object('actionKey',t.id,'title',t.title,'body',t.body,'version',t.version,'status',coalesce(a.status,'Pending')) order by t.created_at desc),'[]') from barber.client_consent_terms t left join lateral(select status from barber.client_consent_acceptances where consent_term_id=t.id and client_id=@client order by created_at desc limit 1)a on true where t.tenant_id=@tenant and t.branch_id=@branch and t.status='Active'",
        "anamnesis"=>"select coalesce(jsonb_agg(jsonb_build_object('actionKey',id,'type',form_type,'status',status,'createdAt',created_at) order by created_at desc),'[]') from barber.client_anamnesis_forms where tenant_id=@tenant and branch_id=@branch and client_id=@client",
        "budgets"=>"select coalesce(jsonb_agg(jsonb_build_object('actionKey',id,'title',title,'description',description,'status',status,'validUntil',valid_until,'total',total) order by created_at desc),'[]') from barber.client_budgets where tenant_id=@tenant and branch_id=@branch and client_id=@client and status<>'Draft'",
        "treatment-plans"=>"select coalesce(jsonb_agg(jsonb_build_object('title',title,'objective',objective,'status',status,'startDate',start_date,'endDate',end_date,'estimatedTotal',estimated_total) order by created_at desc),'[]') from barber.client_treatment_plans where tenant_id=@tenant and branch_id=@branch and client_id=@client and status<>'Draft'",
        "payments"=>"select coalesce(jsonb_agg(jsonb_build_object('actionKey',id,'sourceType',source_type,'amount',amount,'status',status,'expiresAt',expires_at) order by created_at desc),'[]') from barber.client_payment_requests where tenant_id=@tenant and branch_id=@branch and client_id=@client",
        "benefits"=>"select jsonb_build_object('loyalty',coalesce((select jsonb_build_object('points',points,'cashback',cashback_balance) from barber.loyalty_accounts where tenant_id=@tenant and branch_id=@branch and client_id=@client and deleted_at is null limit 1),'{}'),'wallet',coalesce((select jsonb_build_object('credit',credit_balance,'cashback',cashback_balance,'gift',gift_balance) from barber.client_wallets where tenant_id=@tenant and branch_id=@branch and client_id=@client limit 1),'{}'),'memberships',coalesce((select jsonb_agg(jsonb_build_object('plan',p.name,'status',m.status,'endsAt',m.ends_at)) from barber.client_memberships m join barber.club_plans p on p.id=m.club_plan_id where m.tenant_id=@tenant and m.branch_id=@branch and m.client_id=@client),'[]'))",
        "reviews"=>"select coalesce(jsonb_agg(jsonb_build_object('rating',rating,'npsScore',nps_score,'comment',comment,'status',status,'submittedAt',submitted_at) order by created_at desc),'[]') from barber.client_reviews where tenant_id=@tenant and branch_id=@branch and client_id=@client",
        "preferences"=>"select coalesce(jsonb_object_agg(preference_key,preference_value),'{}') from barber.client_public_preferences where tenant_id=@tenant and branch_id=@branch and client_id=@client",
        "support"=>"select coalesce(jsonb_agg(jsonb_build_object('actionKey',r.id,'subject',r.subject,'category',r.category,'priority',r.priority,'status',r.status,'createdAt',r.created_at,'messages',coalesce((select jsonb_agg(jsonb_build_object('sender',m.sender_type,'message',m.message,'createdAt',m.created_at) order by m.created_at) from barber.client_support_messages m where m.support_request_id=r.id and m.visibility='PublicToClient'),'[]')) order by r.created_at desc),'[]') from barber.client_support_requests r where r.tenant_id=@tenant and r.branch_id=@branch and r.client_id=@client",
        _=>throw new ArgumentOutOfRangeException(nameof(kind))},ct);

    public async Task Act(PortalScope s,string kind,Guid id,JsonElement body,HttpContext http,CancellationToken ct)
    { await using var c=await Open(ct);var reason=Text(body,"reason");string sql;string ev;switch(kind){
        case "cancel": sql=@"update barber.appointments a set status='Cancelled',cancellation_reason=@text,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and client_id=@client and status not in('Completed','Cancelled','NoShow') and scheduled_start>now()+coalesce((select cancellation_limit_minutes from barber.scheduling_policies where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null limit 1),120)*interval '1 minute'";ev="ClientPortalAppointmentCancelled";break;
        case "reschedule": if(!DateTimeOffset.TryParse(Text(body,"startsAt"),out var starts))throw new PortalValidationException("Escolha uma nova data e horário.");sql=@"update barber.appointments a set scheduled_end=@starts+(scheduled_end-scheduled_start),scheduled_start=@starts,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and client_id=@client and status not in('Completed','Cancelled','NoShow') and scheduled_start>now()+coalesce((select reschedule_limit_minutes from barber.scheduling_policies where tenant_id=@tenant and branch_id=@branch and status='Active' and deleted_at is null limit 1),120)*interval '1 minute' and not exists(select 1 from barber.appointments conflict where conflict.tenant_id=a.tenant_id and conflict.branch_id=a.branch_id and conflict.professional_id=a.professional_id and conflict.id<>a.id and conflict.status not in('Cancelled','NoShow') and tstzrange(conflict.scheduled_start,conflict.scheduled_end,'[)') && tstzrange(@starts,@starts+(a.scheduled_end-a.scheduled_start),'[)'))";ev="ClientPortalAppointmentRescheduled";break;
        case "consent-accept":sql=@"insert into barber.client_consent_acceptances(tenant_id,branch_id,client_id,consent_term_id,acceptance_channel,ip_address,user_agent,status) select @tenant,@branch,@client,id,'Public',@ip::inet,@agent,'Active' from barber.client_consent_terms where id=@id and tenant_id=@tenant and branch_id=@branch and status='Active' on conflict do nothing";ev="ClientPortalConsentAccepted";break;
        case "consent-revoke":if(string.IsNullOrWhiteSpace(reason))throw new PortalValidationException("Confirme a revogação informando o motivo.");sql="update barber.client_consent_acceptances set status='Revoked',revoked_at=now(),revoked_reason=@text where consent_term_id=@id and tenant_id=@tenant and branch_id=@branch and client_id=@client and status='Active'";ev="ClientPortalConsentRevoked";break;
        case "budget-approve":sql="update barber.client_budgets set status='Approved',approved_at=now(),updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and client_id=@client and status='Presented' and (valid_until is null or valid_until>=current_date)";ev="ClientPortalBudgetApproved";break;
        case "budget-reject":sql="update barber.client_budgets set status='Rejected',rejected_at=now(),rejection_reason=@text,updated_at=now() where id=@id and tenant_id=@tenant and branch_id=@branch and client_id=@client and status='Presented'";ev="ClientPortalBudgetRejected";break;
        case "payment-intent":sql="update barber.client_payment_requests set updated_at=now(),metadata_json=jsonb_set(metadata_json,'{intentConfirmedAt}',to_jsonb(now())) where id=@id and tenant_id=@tenant and branch_id=@branch and client_id=@client and status='Pending'";ev="ClientPortalPaymentIntentCreated";break;
        default:throw new PortalValidationException("Ação não reconhecida.");}
        await using var cmd=new NpgsqlCommand(sql,c);Scope(cmd,s);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("text",reason??"");cmd.Parameters.AddWithValue("ip",http.Connection.RemoteIpAddress?.ToString()??"127.0.0.1");cmd.Parameters.AddWithValue("agent",http.Request.Headers.UserAgent.ToString());if(kind=="reschedule")cmd.Parameters.AddWithValue("starts",DateTimeOffset.Parse(Text(body,"startsAt")!));if(await cmd.ExecuteNonQueryAsync(ct)==0)throw new PortalValidationException("Esta ação não está disponível. Confira o status, prazo e disponibilidade.");await Event(c,s.TenantId,s.BranchId,s.ClientId,ev,kind,id,http,ct); }

    public async Task CreateReview(PortalScope s,JsonElement b,HttpContext http,CancellationToken ct){if(!Guid.TryParse(Text(b,"appointmentKey"),out var appointment)||!int.TryParse(Text(b,"rating"),out var rating)||rating is<1 or>5)throw new PortalValidationException("Selecione o atendimento concluído e uma nota de 1 a 5.");int? nps=int.TryParse(Text(b,"npsScore"),out var n)?n:null;if(nps is <0 or >10)throw new PortalValidationException("O NPS deve estar entre 0 e 10.");await using var c=await Open(ct);await using var cmd=new NpgsqlCommand(@"insert into barber.client_reviews(tenant_id,branch_id,client_id,appointment_id,service_order_id,professional_id,rating,nps_score,comment,status,submitted_at) select @tenant,@branch,@client,a.id,so.id,a.professional_id,@rating,@nps,@comment,'Submitted',now() from barber.appointments a left join barber.service_orders so on so.appointment_id=a.id and so.client_id=a.client_id where a.id=@appointment and a.tenant_id=@tenant and a.branch_id=@branch and a.client_id=@client and a.status='Completed' on conflict(tenant_id,branch_id,client_id,appointment_id) do nothing",c);Scope(cmd,s);cmd.Parameters.AddWithValue("appointment",appointment);cmd.Parameters.AddWithValue("rating",rating);cmd.Parameters.AddWithValue("nps",(object?)nps??DBNull.Value);cmd.Parameters.AddWithValue("comment",Text(b,"comment")??"");if(await cmd.ExecuteNonQueryAsync(ct)==0)throw new PortalValidationException("Este atendimento não pode ser avaliado ou já recebeu sua avaliação.");if(rating<=3||nps<=6){await using var recovery=new NpgsqlCommand(@"insert into barber.quality_recovery_cases(tenant_id,branch_id,client_id,professional_id,appointment_id,service_order_id,review_id,case_type,severity,status,reason,summary,assigned_to) select r.tenant_id,r.branch_id,r.client_id,r.professional_id,r.appointment_id,r.service_order_id,r.id,'Detractor',case when r.nps_score<=3 or r.rating<=2 then 'High' else 'Medium' end,'Open','Avaliação abaixo do limite',coalesce(nullif(r.comment,''),'Cliente solicitou atenção pós-atendimento'),u.id from barber.client_reviews r cross join lateral(select id from barber.users where tenant_id=r.tenant_id and status='Active' order by created_at limit 1)u where r.tenant_id=@tenant and r.branch_id=@branch and r.client_id=@client and r.appointment_id=@appointment and not exists(select 1 from barber.quality_recovery_cases q where q.review_id=r.id)",c);Scope(recovery,s);recovery.Parameters.AddWithValue("appointment",appointment);await recovery.ExecuteNonQueryAsync(ct);}await Event(c,s.TenantId,s.BranchId,s.ClientId,"QualityReviewSubmitted","Appointment",appointment,http,ct);}
    public async Task SavePreferences(PortalScope s,JsonElement b,HttpContext http,CancellationToken ct){var allowed=new[]{"email","sms","whatsapp","push","appointmentReminders","marketing"};await using var c=await Open(ct);foreach(var key in allowed){if(!b.TryGetProperty(key,out var value))continue;await using var cmd=new NpgsqlCommand("insert into barber.client_public_preferences(tenant_id,branch_id,client_id,preference_key,preference_value) values(@tenant,@branch,@client,@key,@value) on conflict(tenant_id,branch_id,client_id,preference_key) do update set preference_value=excluded.preference_value,updated_at=now()",c);Scope(cmd,s);cmd.Parameters.AddWithValue("key",key);cmd.Parameters.AddWithValue("value",value.ToString());await cmd.ExecuteNonQueryAsync(ct);}await Event(c,s.TenantId,s.BranchId,s.ClientId,"ClientPortalPreferencesUpdated","Preferences",null,http,ct);}
    public async Task OpenSupport(PortalScope s,JsonElement b,HttpContext http,CancellationToken ct){var subject=Text(b,"subject");var message=Text(b,"message");var category=Text(b,"category");if(string.IsNullOrWhiteSpace(subject)||string.IsNullOrWhiteSpace(message)||!new[]{"Appointment","Payment","Service","Product","Complaint","Compliment","Other"}.Contains(category))throw new PortalValidationException("Preencha assunto, categoria e mensagem.");await using var c=await Open(ct);await using var tx=await c.BeginTransactionAsync(ct);var id=Guid.NewGuid();await Exec(c,tx,"insert into barber.client_support_requests(id,tenant_id,branch_id,client_id,subject,category,priority,status) values(@id,@tenant,@branch,@client,@subject,@category,'Normal','Open')",("id",id),("tenant",s.TenantId),("branch",s.BranchId),("client",s.ClientId),("subject",subject),("category",category!));await Exec(c,tx,"insert into barber.client_support_messages(tenant_id,branch_id,support_request_id,sender_type,sender_client_id,message,visibility) values(@tenant,@branch,@id,'Client',@client,@message,'PublicToClient')",("tenant",s.TenantId),("branch",s.BranchId),("id",id),("client",s.ClientId),("message",message));if(category=="Complaint")await Exec(c,tx,@"insert into barber.quality_recovery_cases(tenant_id,branch_id,client_id,support_request_id,case_type,severity,status,reason,summary,assigned_to) select @tenant,@branch,@client,@id,'Complaint','High','Open',@subject,@message,u.id from barber.users u where u.tenant_id=@tenant and u.status='Active' order by u.created_at limit 1",("tenant",s.TenantId),("branch",s.BranchId),("client",s.ClientId),("id",id),("subject",subject),("message",message));await tx.CommitAsync(ct);await Event(c,s.TenantId,s.BranchId,s.ClientId,category=="Complaint"?"QualityRecoveryCaseOpened":"ClientPortalSupportOpened","Support",id,http,ct);}
    public async Task SupportMessage(PortalScope s,Guid id,string message,HttpContext http,CancellationToken ct){if(string.IsNullOrWhiteSpace(message))throw new PortalValidationException("Escreva uma mensagem.");await using var c=await Open(ct);await using var cmd=new NpgsqlCommand("insert into barber.client_support_messages(tenant_id,branch_id,support_request_id,sender_type,sender_client_id,message,visibility) select @tenant,@branch,r.id,'Client',@client,@message,'PublicToClient' from barber.client_support_requests r where r.id=@id and r.tenant_id=@tenant and r.branch_id=@branch and r.client_id=@client and r.status not in('Resolved','Cancelled')",c);Scope(cmd,s);cmd.Parameters.AddWithValue("id",id);cmd.Parameters.AddWithValue("message",message);if(await cmd.ExecuteNonQueryAsync(ct)==0)throw new PortalValidationException("Esta solicitação não aceita novas mensagens.");}
    private async Task<JsonElement> Json(PortalScope s,string sql,CancellationToken ct){await using var c=await Open(ct);await using var cmd=new NpgsqlCommand(sql,c);Scope(cmd,s);var v=await cmd.ExecuteScalarAsync(ct);return JsonDocument.Parse(v?.ToString()??"null").RootElement.Clone();}
    private async Task<NpgsqlConnection> Open(CancellationToken ct){var c=new NpgsqlConnection(connectionString);await c.OpenAsync(ct);return c;}
    private static void Scope(NpgsqlCommand c,PortalScope s){c.Parameters.AddWithValue("tenant",s.TenantId);c.Parameters.AddWithValue("branch",s.BranchId);c.Parameters.AddWithValue("client",s.ClientId);}
    private static async Task Exec(NpgsqlConnection c,NpgsqlTransaction tx,string sql,params (string,object)[] values){await using var cmd=new NpgsqlCommand(sql,c,tx);foreach(var(x,v)in values)cmd.Parameters.AddWithValue(x,v);await cmd.ExecuteNonQueryAsync();}
    private static async Task Event(NpgsqlConnection c,Guid tenant,Guid branch,Guid client,string type,string source,Guid? sourceId,HttpContext http,CancellationToken ct){await using var cmd=new NpgsqlCommand("insert into barber.client_portal_events(tenant_id,branch_id,client_id,event_type,source_type,source_id,description,ip_address,user_agent) values(@tenant,@branch,@client,@type,@source,@sourceId,@type,@ip::inet,@agent)",c);cmd.Parameters.AddWithValue("tenant",tenant);cmd.Parameters.AddWithValue("branch",branch);cmd.Parameters.AddWithValue("client",client);cmd.Parameters.AddWithValue("type",type);cmd.Parameters.AddWithValue("source",source);cmd.Parameters.AddWithValue("sourceId",(object?)sourceId??DBNull.Value);cmd.Parameters.AddWithValue("ip",http.Connection.RemoteIpAddress?.ToString()??"127.0.0.1");cmd.Parameters.AddWithValue("agent",http.Request.Headers.UserAgent.ToString());await cmd.ExecuteNonQueryAsync(ct);}
    private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
    private static string Mask(string value){var at=value.IndexOf('@');if(at>1)return $"{value[0]}***{value[(at-1)..]}";var digits=new string(value.Where(char.IsDigit).ToArray());return digits.Length>4?$"***{digits[^4..]}":"***";}
    private static string? Text(JsonElement b,string n)=>b.TryGetProperty(n,out var v)?v.ToString():null;
}
public sealed class PortalValidationException(string message):Exception(message);
